### ISSUE TITLE
Auto restart app after a crash

### ISSUE THREAD

**Issue by PowerfulPony** [Valkirie/HandheldCompanion#1001]
**Is your feature request related to a problem? Please describe.**
Yes, the application crashes (random reasons, resolution change, hibernation, connecting a new device) and the virtual controller will stop working in the middle of a full-screen game, depriving us of the ability to interact with the device.

**Describe the solution you'd like**
The most important thing when using a virtual controller is its trouble-free operation. I want the application to restart at least the controller agent or completely restart itself. It is important to downgrade random application failure issues from "blocking" to "high".
Automatic restart if the application was not closed through menu items

**Describe alternatives you've considered**
The only alternative can be perfect, fail-safe code, but that doesn’t happen.

**Comment by CasperH2O** [comment]
While obviously HC should never crash and we do our utmost to make sure this is the case, it unfortunately does happen.

A simple deamon or service could be made. A simple bat script, started with Windows could also do the trick. See for an example: https://superuser.com/questions/1678947/check-if-process-is-running-if-not-start-it

**Comment by CasperH2O** [comment]
@PowerfulPony I'm closing this one as a won't fix/not planned. You make a valid point, but to be fair, I'd rather spend energy on fixing the actual reasons for the crashes then implement such a restart mechanism.
