### ISSUE TITLE
 json flagged as virus Atc4.detection

### ISSUE THREAD

**Issue by aminoginji** [Valkirie/HandheldCompanion#1002]
**Handheld Companinion Version**
20.4.1

**Describe the bug**
A lot of files in handheld companion are being flagged as virus/malware by Bitdefender mainly the json files

**Screenshots**
![image](https://github.com/Valkirie/HandheldCompanion/assets/1223153/3fe945de-d81a-45c1-bcf3-d043aca1f091)

**Comment by CasperH2O** [comment]
Strange, I have Bitdefender as standard anto virus on my devices and it has never complained about this 

Recommend you flag them as false positives.

**Comment by CasperH2O** [comment]
@aminoginji can you share one of those files or paste it's content here?

**Comment by CasperH2O** [comment]
Unable to reproduce and original issue creator has not replied to request for files. Closing.
