### ISSUE TITLE
HC Is killing roblox 💀

### ISSUE THREAD

**Issue by Taboulet** [Valkirie/HandheldCompanion#1003]
**Device manufacturer**
- [x] VALVE

**Device model**
Steam deck LCD

**Handheld Companinion Version**
0.20.4.1

**Describe the bug**
When launching the roblox player after like 30sec it will crash because of hc, this doesn't happen when HC is not launched

**To Reproduce**
1. Launch HC
2. Go to roblow
3. Wait 30sec/1 minute

**Expected behavior**
Nothing should happen and the game should run normaly

**Screenshots**
Yes ![Capture d'écran 2024-02-27 143819](https://github.com/Valkirie/HandheldCompanion/assets/127585065/74a45c08-9c11-4955-bf18-2d33da07f667)
**Logs file**
I can't find it

Note : This happened to me in the past but i just thought valve's hardware didn't work well with roblox and i started using the microsoft store version of roblox which don't crash but has poor stability. And when i tried today it showed for the first time a notification (screenshoot) which proved that it was caused by HC. Btw i tried launching roblox without HC and using keyboard and mouse and it worked fine

**Comment by Taboulet** [comment]
I just saw that someone asked the same thing 6 month ago and you closed it because of roblox anticheat being random and not giving information on why. Maybe this notification and some other information i gived can help ?

**Comment by CasperH2O** [comment]
Hey @Taboulet sorry to hear you can't use HC with your game. While the error message clearly states which app it doesn't like, we can only guess as to why. In a similar vein I closed the other ticket.

You could try disabling all or most options in HC, like virtual controller usage, layout remapping and TDP control to see if that helps. Other then that we can't do much I'm afraid.

**Comment by Taboulet** [comment]
After verifying, when lauching roblox in administrator mode the game doesn't crash. I guess this is a temporary fix but i think it's because HC is modifying roblox (the suspender maybe) and that doesn't like it. Maybe you should try to but roblox on a modify blacklist or something ?

**Comment by CasperH2O** [comment]
@Taboulet in what way would HC modify Roblox, you mention the suspender?

**Comment by CasperH2O** [comment]
@Taboulet , I am closing this issue as a won't fix, although you have already found a solution by running Roblox as admin.
