### ISSUE TITLE
Cannot unlock windows at all and controls are not working except for volume button

### ISSUE THREAD

**Issue by UntrndSpartn** [Valkirie/HandheldCompanion#1004]
VALVE

**Device model**
Steamdeck 64GB

**Handheld Companinion Version**
Newest as of march 6th

**Comment by CasperH2O** [comment]
Hey @UntrndSpartn the information you provide is not a lot to go on, but it reads like a soft brick issue we had some time ago.

Did you uninstall or update HC prior to this happening?

**Comment by CasperH2O** [comment]
Sorry to read you are having trouble.

If you connect an external mouse and keyboard, do those also not work?

Here are the recovery instructions for a soft brick: https://docs.nefarius.at/projects/HidHide/fixing-a-bricked-system/

**Comment by CasperH2O** [comment]
Original issue creator has not responded, initial help has been provided based on limited provided information. Closing ticket. If you still need help @UntrndSpartn feel free to reopen.

**Comment by UntrndSpartn** [comment]
> Hey @UntrndSpartn the information you provide is not a lot to go on, but it reads like a soft brick issue we had some time ago.
> 
> Did you uninstall or update HC prior to this happening?

Nope, i downloaded it after i found out about it and could not use the touchscreen, or controls except for volume up and down
