### ISSUE TITLE
Xbox guide button mapping on Legion Go

### ISSUE THREAD

**Issue by philipobenito** [Valkirie/HandheldCompanion#1010]
Sorry if this is something that already exists or is possible but I've searched through issues and tried to search Google/Reddit too.

I'd love to see the Xbox guide button either automatically mapped to one of the physical buttons on the Legion Go, or to have the ability to map it manually.

**Comment by MSeys** [comment]
You can map it yourself on profiles.

**Comment by philipobenito** [comment]
> You can map it yourself on profiles. 

How? I don't see it as a specific mapping, and I obviously don't have a guide button to press on custom mappings.

**Comment by MSeys** [comment]
Are you talking about the Hotkeys section? You're not looking in the right section at all.

**Comment by MSeys** [comment]
![IMG_20240106_175556](https://github.com/Valkirie/HandheldCompanion/assets/32166289/f1536e59-df36-417e-8dd2-b4241c225c20)
Actual remapping is on the profiles. You enable "Controller layout" and press on the block to get to it.

**Comment by philipobenito** [comment]
Ah excellent, thanks @MSeys

**Comment by philipobenito** [comment]
One last question @MSeys 

I've got that working perfectly in default profile, but I created a profile for a game and it didn't pass through to that profile, the Default profile isn't listed as a sub profile either, so am I missing something there?

**Comment by MSeys** [comment]
Sub profiles is an entirely different feature. 

You can set the layout in Default profile as "default layout" (see the "make this default layout" checkbox). This will make it copy that layout to new profiles on creation.
