### ISSUE TITLE
Desktop layout or mouse and keyboard remapper does not work when HC or QT is the active window

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#1023]
**Handheld Companinion Version**
0.20.5.5

**Describe the bug**

**To Reproduce**
1. Enable Desktop Mode with a hotkey or button in the UI
2. Try to move the mouse in HCs Window
3. Open another app, mouse works fine

Alternatively, make a profile with mouse and keyboard layout, works in the app, but not when HC Window is active.

**Comment by CasperH2O** [comment]
Updated, UI gamepad navigation now works. Desktop layout mouse navigation does indeed not work in HC as Gamepad UI navigation takes priority.

**Comment by Sev7nrayne** [comment]
enable/unHide: Valve Software Steam Controller

Touchpad/Mouse works

Handheld Companion (0.21.0.1)
