### ISSUE TITLE
KeyNotFoundException QuickProfilesPage

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#1024]
**Handheld Companinion Version**
0.20.5.5

**To Reproduce**
1. Unknown, just opened HC in debug, never seen it before, could not reproduce

**Screenshots**
![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/c3e9b46b-2210-47fd-8d60-c596ea340ccb)

**Comment by Valkirie** [comment]
fixed
