### ISSUE TITLE
ROGAlly "No Virtual Controller Detected"

### ISSUE THREAD

**Issue by kdiddlemarddidle** [Valkirie/HandheldCompanion#1029]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ x] ASUS
- [ ] GPD
- [ ] LENOVO
- [ ] MSI
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
ROGally

**Handheld Companion Version**
0.20.4.1

**Describe the bug**
When attempting to use the emulated Dualshock controller, I am given a notification "no virtual controller detected." 

**To Reproduce**
1. Go to the main HC application while using an ASUS ROGAlly.
2. Click on "Controller"
3. Scroll down to controller type and turn on 
4. See error top of the Page.

**Comment by CasperH2O** [comment]
@kdiddlemarddidle thanks for reporting this. Release 21.0.1 has a fix for this message showing when its not supposed to. Can you try it and let us know if it improves your situation?
