### ISSUE TITLE
The EXTERNAL and CONTROLLER sensor options are grayed out?

### ISSUE THREAD

**Issue by bedogs00** [Valkirie/HandheldCompanion#1057]
**Device manufacturer**
- [x] ONEXPLAYER

**Device model**
ONEXPLAYER MINI PRO 6800U

**Handheld Companion Version**
Version 0.21.0.1

**Describe the bug**
The EXTERNAL and CONTROLLER sensors on the handheld companion are greyed out and I cannot use my physical Xbox controller's GYRO for it. But the INTERNAL sensor option works. Is there any way to use GYRO/ MOTION CONTROLS on any of my gaming controllers using handheld companion?

**Comment by CasperH2O** [comment]
@bedogs00 , thanks for dropping in. The External sensor option is only meant for the USB Gyro sensor, which people who have a GPD Win 3 with no internal gyro use. The Internal is indeed using your handhelds sensor, so that's good.

You can use Controller, but only if you have connected a controller to your device with a gyro sensor. Which external controller are you using? Xbox controllers don't have gyro, but the Dualshock4 and Dual Sense do.

**Comment by bedogs00** [comment]
Thank you so much for replying regarding my concern "CasperH20".
So external sensor are meant for those. Good to know 
And yes, I am using a Gulikit king kong 2 pro controller which has an Xinput, Dinput, pro controller input and even android and yes, it has Gyro buit-in and it works on my Nintendo switch but is there anyway to use this controller to actually have its motion control be used from using handheld companion on my ONEXPLAYER MINI PRO? Cause even if I connect my controller and handheld companion detects it as either an Xbox controller or a pro controller or a generic Bluetooth controller (Wired or wireless via Bluetooth or USB wireless receiver), the controller sensor option is still greyed out. 
Am I missing something?

I hope you can help me out. Thanks! 
    On Saturday, May 11, 2024 at 03:18:26 PM GMT+8, CasperH2O ***@***.***> wrote:  
 
 


@bedogs00 , thanks for dropping in. The External sensor option is only meant for the USB Gyro sensor, which people who have a GPD Win 3 with no internal gyro use. The Internal is indeed using your handhelds sensor, so that's good.

You can use Controller, but only if you have connected a controller to your device with a gyro sensor. Which external controller are you using? Xbox controllers don't have gyro, but the Dualshock4 and Dual Sense do.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by Valkirie** [comment]
>  Thank you so much for replying regarding my concern "CasperH20".
> So external sensor are meant for those. Good to know 
> And yes, I am using a Gulikit king kong 2 pro controller which has an Xinput, Dinput, pro controller input and even android and yes, it has Gyro buit-in and it works on my Nintendo switch but is there anyway to use this controller to actually have its motion control be used from using handheld companion on my ONEXPLAYER MINI PRO? Cause even if I connect my controller and handheld companion detects it as either an Xbox controller or a pro controller or a generic Bluetooth controller (Wired or wireless via Bluetooth or USB wireless receiver), the controller sensor option is still greyed out. 
> Am I missing something?
> 
> I hope you can help me out. Thanks! 
>     On Saturday, May 11, 2024 at 03:18:26 PM GMT+8, CasperH2O ***@***.***> wrote:  
>  
>  
> 
> 
> @bedogs00 , thanks for dropping in. The External sensor option is only meant for the USB Gyro sensor, which people who have a GPD Win 3 with no internal gyro use. The Internal is indeed using your handhelds sensor, so that's good.
> 
> You can use Controller, but only if you have connected a controller to your device with a gyro sensor. Which external controller are you using? Xbox controllers don't have gyro, but the Dualshock4 and Dual Sense do.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>
>   
> 
> |  | Virus-free.www.avast.com |
> 
> 

Hey, we don't support Gulikit Pro controller so that's why you can't pick its sensor. We could send you a tool which monitor inputs from hid devices (like the controller) and cross fingers it's exposing the internal gyro values, so that we could actually support it (or maybe Gulikit has an API).

**Comment by bedogs00** [comment]
No wonder! Ok, thanks! I will gladly accept any help 🥰🙏
Please, send me a link on this tool and I can look and try from there.
Thank you so much for the quick replies and have a great weekend! 👍 
 
  On Sat, May 11, 2024 at 4:14 PM, Lesueur ***@***.***> wrote:   



Thank you so much for replying regarding my concern "CasperH20".
So external sensor are meant for those. Good to know 
And yes, I am using a Gulikit king kong 2 pro controller which has an Xinput, Dinput, pro controller input and even android and yes, it has Gyro buit-in and it works on my Nintendo switch but is there anyway to use this controller to actually have its motion control be used from using handheld companion on my ONEXPLAYER MINI PRO? Cause even if I connect my controller and handheld companion detects it as either an Xbox controller or a pro controller or a generic Bluetooth controller (Wired or wireless via Bluetooth or USB wireless receiver), the controller sensor option is still greyed out. 
Am I missing something?

I hope you can help me out. Thanks! 
On Saturday, May 11, 2024 at 03:18:26 PM GMT+8, CasperH2O @.***> wrote:

@bedogs00 , thanks for dropping in. The External sensor option is only meant for the USB Gyro sensor, which people who have a GPD Win 3 with no internal gyro use. The Internal is indeed using your handhelds sensor, so that's good.

You can use Controller, but only if you have connected a controller to your device with a gyro sensor. Which external controller are you using? Xbox controllers don't have gyro, but the Dualshock4 and Dual Sense do.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: @.***>

| | Virus-free.www.avast.com |


Hey, we don't support Gulikit Pro controller so that's why you can't pick its sensor. We could send you a tool which monitor inputs from hid devices (like the controller) and cross fingers it's exposing the internal gyro values, so that we could actually support it (or maybe Gulikit has an API).

**Comment by Valkirie** [comment]
Please try this: https://1drv.ms/u/s!AleMgLLgxwGJhYolIvQ7B2_m8X1DUA. You'll be looking for anything specific to the controller, like a 2nd hid device listed that seams to pass values on controller movements.

**Comment by bedogs00** [comment]
Ok, Lesuer! I'll try this one immediately and see from there. Thanks a bunch from all the help guys!
    On Saturday, May 11, 2024 at 07:54:16 PM GMT+8, Lesueur Benjamin ***@***.***> wrote:  
 
 


Please try this: https://1drv.ms/u/s!AleMgLLgxwGJhYolIvQ7B2_m8X1DUA. You'll be looking for anything specific to the controller, like a 2nd hid device listed that seams to pass values on controller movements.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by bedogs00** [comment]
After so many attempts.... I FINALLY MADE IT WORK! THANK YOU SO MUCH FOR ALL THE HELP!
Basically, I tried going to the sensor option and tried switching my gulikit kingkong 2 pro controller modes from xbox to android/ios to direct input to finally, Nintendo switch and guess what!... THE CONTROLLER SENSOR OPTION FINALLY BEEN ENABLED WOOOOOOHHH!!!!
Now, I am a happy man! Hahaha!
And I'm kinda new here so can I ask if this message can be seen online for those who need help from the same issues? This might help some folks out there     On Saturday, May 11, 2024 at 09:33:04 PM GMT+8, Nikki jon Bal ***@***.***> wrote:  
 
  Ok, Lesuer! I'll try this one immediately and see from there. Thanks a bunch from all the help guys!
    On Saturday, May 11, 2024 at 07:54:16 PM GMT+8, Lesueur Benjamin ***@***.***> wrote:  
 
 


Please try this: https://1drv.ms/u/s!AleMgLLgxwGJhYolIvQ7B2_m8X1DUA. You'll be looking for anything specific to the controller, like a 2nd hid device listed that seams to pass values on controller movements.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by CasperH2O** [comment]
Glad you found a workable situation @bedogs00 .

On our end we are a bit puzzles why the controller doesnt work in DS4 mode. Can you configure that mode in the controller and with the software tool we shared, find the PID and VID numbers?

**Comment by bedogs00** [comment]
Honestly, I don't know how to use the hidinspector that you sent but I accidentally found the solution by switching modes from my controller and eventually, pro controller for the switch is the one that detects handheld companion as one compatible for the controller sensors then I can use that to emulate DS4 or xbox controls.
My Gulikit Kingking 2 pro controller doesn't have a DS4 mode. Only Switch pro controller, Xinput (XBOX), Android/ IOS and Direct input.
    On Sunday, May 12, 2024 at 02:18:43 AM GMT+8, CasperH2O ***@***.***> wrote:  
 
 


Glad you found a workable situation @bedogs00 .

On our end we are a bit puzzles why the controller doesnt work in DS4 mode. Can you configure that mode in the controller and with the software tool we shared, find the PID and VID numbers?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |
