### ISSUE TITLE
HC doesn't open

### ISSUE THREAD

**Issue by Jokers99** [Valkirie/HandheldCompanion#1068]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] LENOVO
- [ ] MSI
- [ ] ONEXPLAYER
- [x] VALVE

**Comment by CasperH2O** [comment]
Hey @Jokers99 , I'd like to help you but need a logfile. You can find it in: C:/program files/handheld companion/logs

**Comment by ne3nr3a1e** [comment]
hello, my HC doesn't open too. but "C:/program files/handheld companion/logs" there is simply no such file in the program files, or it does not have time to be created

**Comment by CasperH2O** [comment]
Mmmhh, thats obviously not what is supposed to happen. 

Without a log it will be difficult to determine. Do you have visual studio 2022 installed by any chance so you can run from source?

**Comment by ne3nr3a1e** [comment]
> Mmmhh, thats obviously not what is supposed to happen.
> 
> Without a log it will be difficult to determine. Do you have visual studio 2022 installed by any chance so you can run from source?

I was able to run the program via visual studio 2022 what should I do next?

**Comment by CasperH2O** [comment]
Did you open it in release or debug mode? 

If it opened normally without issue, does the installed version do the same now?

**Comment by ne3nr3a1e** [comment]
> Did you open it in release or debug mode?
> 
> If it opened normally without issue, does the installed version do the same now?

I opened it in debug mode, then in release mode and everything started through visual, but the application itself, which I previously installed, still does not start and cannot create a log file

**Comment by CasperH2O** [comment]
Have you tried installing again? Your device can run HC for sure, so that is not the issue.

An alternative is to start the release version from VS and then toggle the start with Windows setting back and forth. It will redirect to start your built version instead of the installed one.
