### ISSUE TITLE
HC seemingly cannot change active power preset

### ISSUE THREAD

**Issue by LadyHylia** [Valkirie/HandheldCompanion#1069]
**Device manufacturer**
- [x] ASUS

**Device model**
ROG Ally Z1(not extreme)

**Handheld Companion Version**
0.21.2.3

**Describe the bug**
Any attempt to select a different power plan for the machine to use through handheld companion is immediately overwritten. This happens in main window and quick tools.

**To Reproduce**
1. Navigate to Profiles tab
2. Change power preset to anything other than default
3. Power preset is changed back to Default after about half a second
4. Receive two windows toast notifications telling me the profile has been changed

**Expected behavior**
Power preset should remain as what I set it to

**Screenshots**
https://github.com/Valkirie/HandheldCompanion/assets/95134341/7abcf8cb-ee48-4c25-884d-c711893b4dc8

EDIT: Watching the video back, it doesn't actually show the active one briefly changing or the toast notifications, but they do occur in person

**Logs file**
[HandheldCompanion-20240530.log](https://github.com/Valkirie/HandheldCompanion/files/15504313/HandheldCompanion-20240530.log)

**Comment by CasperH2O** [comment]
Hey @LadyHylia . Looks like you are having trouble die to the empty profile name bug.

If you close HC and then in my documents, handheld companion, profiles, delete the ".json" file and and Default profiles which are post fixed with numbers you should be fine again.

**Comment by LadyHylia** [comment]
> Hey @LadyHylia . Looks like you are having trouble die to the empty profile name bug.
> 
> If you close HC and then in my documents, handheld companion, profiles, delete the ".json" file and and Default profiles which are post fixed with numbers you should be fine again.

Thank you, that did indeed fix the issue. I must have created a bunch of phantom profiles while trying to add a new one. I was clicking the "plus" expecting a prompt to enter a name, and kept thinking it didn't register the click.

**Comment by CasperH2O** [comment]
@LadyHylia , its not you, this was a bug that was hotfixed in .3

**Comment by aregulus-arch** [comment]
I have the same issue，and the method doesn't work for me. 0.21.2.4  Rog ally.
