### ISSUE TITLE
Windows services GYRO

### ISSUE THREAD

**Issue by Klemci** [Valkirie/HandheldCompanion#1084]
**Device manufacturer**
- [xXx ] VALVE

**Device model**
OLED

**Handheld Companion Version**
Now

**Describe the bug**
No bug, question

**To Reproduce**
Services list

**Expected behavior**
About **GYRO** on Windows (11) what services need to be active?

I mostly disabled services, and will install the **Companion**, but i'm sure GYRO will need me to re-enable some services, like spacial or  sensors.

A known services list can be found ? Please, thanks for all !-!

**Comment by mike908** [comment]
hi i'm new to this but how do i get my legion go trust handheld companion?

**Comment by Klemci** [comment]
Trust ? IDK it worked out of the box, i not even used installer but just copied extracted files in my apps folder, try move it out of "program files" if that's where it's been installed.

**Comment by CasperH2O** [comment]
@Klemci HC does not need services for gyro. What you will require is drivers for your sensor. This can be checked in Windows Device Manager and then under sensors. 

Honestly, the easiest approach is just to install HC and check if it works, if not share a logfile here.

**Comment by CasperH2O** [comment]
> hi i'm new to this but how do i get my legion go trust handheld companion?

@mike908 not sure what you are asking, but are you referring to the UAC pop up you get when starting HC? It looks something like this: 

![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/4a347be9-e7ab-4abf-9251-6847a2c1a0f0)

If yes. You can make HC start with Windows in the HC Settings, you won't get that pop up. Alternatively you can disable it system wide, but I don't recommend that.

**Comment by Klemci** [comment]
> This can be checked in Windows Device Manager and then under sensors.

If HC managed to sync the sensor when i pressed the button (even showed id) that means it found it right ?

I'm good tho !

**Comment by Klemci** [comment]
Now i have to understand all about config the Gyro :p 

A good game to tetest is Skydrift (planes fly 3D game).

**Comment by Klemci** [comment]
> @Klemci HC does not need services for gyro. What you will require is drivers for your sensor. This can be checked in Windows Device Manager and then under sensors.
> 
> Honestly, the easiest approach is just to install HC and check if it works, if not share a logfile here.

![Presse-papier02](https://github.com/Valkirie/HandheldCompanion/assets/90113078/e8d41d22-8fa7-4fce-94ed-171dde80cba4)
I use Drivers Explorer

**Comment by Klemci** [comment]
Going to Discord

**Comment by CasperH2O** [comment]
As dicussed on Discord. Closing.
