### ISSUE TITLE
Main GUI dropdown selection and highlights remain visible when Window is not open

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#1109]
**Handheld Companion Version**
0.20.5.3

**Describe the bug**
Best to see screenshots. Reported by Dixon.

**To Reproduce**
See:

[FloatyNumbers.webm](https://github.com/user-attachments/assets/0a38f129-4d41-49b7-ba52-636e139bca37)

**Screenshots**

![rn_image_picker_lib_temp_85fd44b4-c98b-4691-9854-bfdb12cc8beb](https://github.com/user-attachments/assets/54d1c5e6-3162-4b12-adea-dce6ae8ee5e4)

![20240804_075918](https://github.com/user-attachments/assets/d9870221-f25d-4357-b8cc-eb4d7ba04014)

**Comment by Valkirie** [comment]
Fixed with: https://github.com/Valkirie/HandheldCompanion-EA/commit/c441ef0fa6b1ea4a165a8f4776fa0df2c8fa272e
