### ISSUE TITLE
Glyph color is not applied when target controller is not yet availible

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#1110]
**Handheld Companion Version**
0.20.5.3

**Describe the bug**
Noted by @joshuatam and @Valkirie 

> Make sense ! We need to bring back an event listener to ControllerManager on new targeted controller and update both color and glyphs (DS4/XBOX)

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/308763aa-0b68-4ec2-9b6d-6938d85ba0b9)

![image](https://github.com/user-attachments/assets/9564b76c-beff-4f58-b6b3-a95f6f09cc62)

![image](https://github.com/user-attachments/assets/a06ded49-e707-4544-99f0-a00367323f50)

**Comment by Valkirie** [comment]
Fixed with: https://github.com/Valkirie/HandheldCompanion-EA/commit/8d39d16feea26d67a9f47f2e98056313b2b37e89
