### ISSUE TITLE
Active process not properly detected

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#1111]
**Handheld Companion Version**
0.20.5.3

**Describe the bug**
The active process is not always properly detected, thus game profiles are not applied. It seems to be related to starting games from Steam and Playnite. Reported by trookam on Discord.

**To Reproduce**
1. Start game from Steam or Playnite.
2. Check QT profile tab, "waiting for foreground process" or SteamWebHelper.exe

**Screenshots**
![IMG_4922](https://github.com/user-attachments/assets/bfc4f1cf-5659-4a77-9c7f-2c729b9249fe)

![IMG_4921](https://github.com/user-attachments/assets/185a6543-d39c-4be9-8130-8fadda983e5d)

![remix-3b0986db-58d1-4702-928a-266c845a4e06](https://github.com/user-attachments/assets/9f043cae-3934-4214-ba1a-7b1dd3bee3a8)

**Comment by Valkirie** [comment]
Fixed with: https://github.com/Valkirie/HandheldCompanion-EA/commit/795fb9371ae0708f9a536aa5719ba7b12fabefa8
