### ISSUE TITLE
Desktop mode not active on HC startup until Quick Tools is opened.

### ISSUE THREAD

**Issue by mightyjoeyoungish** [Valkirie/HandheldCompanion#1150]
**Device manufacturer**
Lenovo

**Device model**
Legion Go

**Handheld Companion Version**
0.21.6.0 (this has also occurred on previous public releases, such as 0.21.5.4)

**Describe the bug**
I have "Enable desktop profile on start" enabled. Whenever I reboot my device or restart HC, I am unable to move the mouse cursor with the joystick until I press the quick tools hotkey to open quick tools window, then again to close the window. Only after opening, then closing the quick tools window am I able to move the mouse cursor using the joystick. I remember being able to do this before and recently experienced this bug.

**To Reproduce**
1. Enable 'Enable desktop profile on start' in the HC settings window.
2. Reboot your device, or restart HC. 
3. After rebooting and on startup, you'll hear several Windows device connect/disconnect sounds. 
4. Attempt to move your cursor using the right joystick. It won't work.
5. Press the hotkey to open the quick tools window.
6. Press the hotkey to close the quick tools window.
7. You are now able to control the mouse cursor using the right joystick.

**Expected behavior**
I expected being able to immediately control the mouse cursor on reboot or restarting HC, without having to open/close the quick tools window.

**Logs file**
If applicable, add logs file stored in your install location, logs folder.

[HandheldCompanion-20240929.log](https://github.com/user-attachments/files/17181580/HandheldCompanion-20240929.log)

**Comment by Valkirie** [comment]
Fixed it with forthcoming EA
