### ISSUE TITLE
Nothing is being displayed in the home tab under actions on quick tools

### ISSUE THREAD

**Issue by liammr992** [Valkirie/HandheldCompanion#1186]
**Device manufacturer**
- [ ] VALVE

**Device model**
steam deck oled 1tb

**Handheld Companion Version**
0.22.0.3

**Describe the bug**
Nothing is being displayed in the home tab under actions on quick tools overlay. Cannot find anything in settings to add actions myself i do have hoy keys set up just seems that nothing is being transferred into the actions tab

**Expected behavior**
I expect my actions to be there ready to use as i see on all YouTube videos

**Comment by CasperH2O** [comment]
In the main GUI on the Hotkey s page, you can "pin" hotkeys, look for the Pin icon. 

Then they should show up on your QT home tab.
