### ISSUE TITLE
[onexplayer mini amd] With a Power button set to "turn off display", upon clicking display does turn off, but almost instantly turns back on

### ISSUE THREAD

**Issue by GanJJJJ** [Valkirie/HandheldCompanion#159]
Please note, that it's not the "sleep mode", but only "turning off display" while the device should remain active. 

That issue mentioned in discord channel: https://discord.com/channels/717181357109018694/911978458802958336/981233149403095080

**Comment by GanJJJJ** [comment]
> @GanJJJJ , we made some changes in version 0.10 regarding power and buttons for the OneX Mini. Could you double check if you still have this issue?

version 0.10.0.0
Yep, to be honest there are still 2 issues with HC "on and service running": 
1. With a Power button set to "turn off display", upon clicking display does turn off, but almost instantly turns back on
2. Going to sleep mode (whether by pressing "Sleep" button via Start menu or by gesture; note that hibernation is turned off). - display turns off, but after 3-4 seconds it turns back on (not instantly, but very quickly, yep).

**Comment by CasperH2O** [comment]
@GanJJJJ are you still experiencing this?

**Comment by CasperH2O** [comment]
Closing due to lack of information feedback.
