### ISSUE TITLE
40hz lock screen refresh rate (instead of 60hz) + 40fps game lock (instead of 60fps) - Steam Deck-like

### ISSUE THREAD

**Issue by GanJJJJ** [Valkirie/HandheldCompanion#187]
1. 40hz lock screen refresh rate (instead of 60hz)
2. 40fps game lock (instead of 60fps) - Steam Deck-like
I would just set 40hz+fps limit once and for all and never switched back to 60, so the "quick way to hot-switch" personally for me isn't really important

**Comment by CasperH2O** [comment]
This initially requires a screen that can support different frequencies.

C# code example to get screen info:

https://stackoverflow.com/questions/744541/how-to-list-available-video-modes-using-c/744609#744609 

Alternatively you can check through Windows advanced screen settings. Example:

My laptop only has the 60.052 Hz option
Ayaneo only has 60.000 Hz option

**Comment by CasperH2O** [comment]
Owhhh, EDID overrides of screens through a tool called CRU:

https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU

**Comment by CasperH2O** [comment]
Small update, testing by various other developers / users have turned up that for the Ayaneo 2021, Ayaneo Next and the Ayaneo Air it's either not possible or the screen flickers terribly.

**Comment by CasperH2O** [comment]
@GanJJJJ with the new custom hotkeys, someone connect them to an AHK script to adjust the refresh rates: https://www.youtube.com/watch?v=mNxILJWt_FQ

**Comment by CasperH2O** [comment]
This will arrive soon.

![image-1](https://user-images.githubusercontent.com/14330834/210856768-9a271d97-fad0-4bef-8fe1-3045a01704e5.png)

**Comment by CasperH2O** [comment]
This has been implemented and tested.
