### ISSUE TITLE
HC crashes on devices withouth brightness control

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#251]
Debug mode shows:

![afbeelding](https://user-images.githubusercontent.com/14330834/192136022-91dffe05-e0c3-452e-b97a-44e47306341f.png)

![afbeelding](https://user-images.githubusercontent.com/14330834/192136028-2d3cab43-8c81-4fcc-813e-76e98f3eeb17.png)

So Supported is false when you start, then you call GetBrightness, it will return 100 and not an exception and thus Supported will be true?

If I'm not mistaken this construction is also used for another feature. Don't recall.

**Comment by Valkirie** [comment]
Should be fixed by #280. Please try it.

**Comment by CasperH2O** [comment]
Fixed!
