### ISSUE TITLE
Why it still have winui?

### ISSUE THREAD

**Issue by wherewhere** [Valkirie/HandheldCompanion#252]
Is this a XAML Island project?
https://github.com/Valkirie/ControllerService/blob/main/HandheldCompanion/HandheldCompanion.csproj#L90-L90
![Screenshot_20220927-155651.jpg](https://user-images.githubusercontent.com/27689196/192468101-c564b6ca-2e98-4014-aa0b-7eb1550f5787.jpg)

**Comment by EldritchEevee** [comment]
Xbox support forces WinUI.
