### ISSUE TITLE
Using keyboard button Tab crashes Quicktools

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#291]
Need to investigate...

**Comment by CasperH2O** [comment]
Can't reproduce on Ayaneo 2021 device. Perhaps a laptop/desktop only thing?

**Comment by Valkirie** [comment]
Fixed it. Please try again.

**Comment by CasperH2O** [comment]
Indeed, latest controller branch works fine. Closing.
