### ISSUE TITLE
Edge case with "translate directinput to xinput calls" crashes HC

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#292]
Found the following edge case:

Have game running, with translate directinput to xinput calls enabled (ie DLLs placed in game folder).

Delete profile while game is running.

Create new profile while game is running, results in HC crash.

Most likely, the new profile does not have the tickbox checked, HC tries to remove the DLLs but can't because the game is running and using them.

Will reproduce/investigate with debug run.

**Comment by CasperH2O** [comment]
Running in debug, the following exception is shown:

![image](https://user-images.githubusercontent.com/14330834/200284634-13e213bc-ddea-4e2c-8ca1-abd29ddfd62e.png)

**Comment by Valkirie** [comment]
I believe I fixed this already. Users should not be able to delete a profile from a running app
