### ISSUE TITLE
Keyboard interruption and random pastes on WIN Max 2

### ISSUE THREAD

**Issue by DirkBraakman** [Valkirie/HandheldCompanion#303]
If the application is running (service doesn't have to be running for this to happen), the input of number keys (1-0), lag, don't register and the worst of all, paste randomly. I've only encountered this with the number keys so far. It seems like it'll paste more of the first number typed after startup?? Doesn't matter if the controls are in mouse or xbox360 mode I think...

Could you please look into this, the program is unusable and I'd otherwise love it!

Thanks!

**Comment by CasperH2O** [comment]
Hoi Dirk, thanks for letting us know. I'm assuming you're using the latest 0.12 release? Can you try the latest 0.13 beta 2 and let us know if it reproduces? Quite some rework with hotkeys has been done.

https://github.com/Valkirie/HandheldCompanion/releases/download/0.12.4.0/Handheld.Companion-Release-net7.0-0.13.0.0-Beta.exe

**Comment by DirkBraakman** [comment]
Hi, thank you!

I installed the new beta and the problem seems to be gone. I think it sometimes misses a registration when spamming a number key real fast, but I'm not so sure about that for now.
I think tt's fixed. Looking forward to the new release!

Thanks a lot again!

**Comment by CasperH2O** [comment]
Glad to hear it, thank you for reporting.
