### ISSUE TITLE
QuickTools profile loads values from other profile on active process change

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#315]
Observed while recording a YT video. Tested with beta 0.14.0.3.

Steps to reproduce.
- Have a profile for an application already in HC, be sure this application does not have only the profile defaults so you can tell the difference, open that application.
- Open an application for which there is no profile yet in HC.
- Open Quicktools, create a profile for the new application
- With Quicktools and the new profile open, change to the initial application, with say, alt tab.
- Observe Quicktools loading the profile for the initial application
- Swap back to the newly created profile
- The newly created profile will have the values of the initial application instead of default ones or any newly changed values

See video: https://user-images.githubusercontent.com/14330834/210164051-43a96390-552f-4d8f-9e99-beb36f1ee6c8.mp4

**Comment by Valkirie** [comment]
Fixed with https://github.com/Valkirie/HandheldCompanion/commit/4e069b9aac6465e101c466bf858f648224fd88ad
