### ISSUE TITLE
Crashing on Ayaneo 2 at start

### ISSUE THREAD

**Issue by chris-calo** [Valkirie/HandheldCompanion#317]
I'm seeing a crash at boot on the Ayaneo 2 (32GB RAM, Windows 11 Enterprise). I did a complete uninstall and reinstall of Handheld Companion to no avail. Any preferred method for diagnoses? Can pair with someone on video, if needed to help.

**Comment by chris-calo** [comment]
Found the fix… kinda. If you don't install the latest, provided Ayaneo 2 audio drivers from their site, Handheld Companion would boot at all. Odd requirement, but it solves it. Wonder if there is a workaround?

**Comment by CasperH2O** [comment]
Hey @chris-calo , thanks for reporting this. That's a rather odd workaround! Can you share HCs logfiles located in either the installation folder in program files or mydocuments/handheldcompanion ?

Be sure to use the latest Ayaneo2 build also, that fixes the RC, LC and Ayaneo button usage: https://github.com/Valkirie/HandheldCompanion/releases/download/0.13.0.1/Handheld.Companion-Release-net7.0-0.13.0.1-Ayaneo2-round2.exe

**Comment by Valkirie** [comment]
You might have a crash dump in your Handheld Companion folder within my documents.

**Comment by CasperH2O** [comment]
@chris-calo did you get this resolved, could you share the files we asked for?

**Comment by CasperH2O** [comment]
Closing due to lack of updates/new information. In the meantime release 0.14 has come out, recommend to try again with that version.
