### ISSUE TITLE
Windows 2 accounts? 

### ISSUE THREAD

**Issue by dkswedens** [Valkirie/HandheldCompanion#322]
Hi there, not sure if this is an issue or me just doing something wrong.
Im sharing the steam deck with my son and using handheld companion, works great when im logged into my windows account.

Everything stops working when my son uses his account, we have different accounts and such for our game launchers so having 2 windows accounts are needed.

Is there something I can do to make this application work for both of us?
Thanks!

**Comment by CasperH2O** [comment]
Hey @dkswedens , did you install HC on both accounts?

**Comment by dkswedens** [comment]
> Hey @dkswedens , did you install HC on both accounts?

I did not, I figured its already installed? Im gonna try that once my other problem with the controller works 😁

Thanks!

**Comment by CasperH2O** [comment]
I've added this item to the list for the Inno setup improvements. Closing for now, thank you for suggesting!
