### ISSUE TITLE
Problem HA menu

### ISSUE THREAD

**Issue by dkswedens** [Valkirie/HandheldCompanion#325]
Opening up the menu for adding a profile while ingame, the menu gets stuck and you cant hide it again / interact with it. You cant create a profile here either. Tried reinstalling the program but same problem occured.

**Comment by CasperH2O** [comment]
Can you share a picture or a video (try hosting at Streamable)?

**Comment by dkswedens** [comment]
> Can you share a picture or a video (try hosting at Streamable)?

Im quite new to this, I'll try to post screenshots im not sure how to record a video.
Ill try within an hour or two, kids are up and about! 

Best regards

**Comment by dkswedens** [comment]
Ok well, after restarting the steam deck I havent had this exact issue again so wasnt able to replicate it.
However hotkey (ctrl alr p) did hang the application upon starting recording keyboard output.
Had to restart steam deck. 
Not sure how good of a video this is but its something..
https://streamable.com/ra7ytc

**Comment by dkswedens** [comment]
https://streamable.com/pv1gf2
It happend here, tried to create profile but couldn't and triggering the menu hotkey nothing happen.

Thanks

**Comment by CasperH2O** [comment]
@dkswedens when I visit the videos it says they have been archived and are unavailable currently. Could you double check?
