### ISSUE TITLE
Steam Deck Is the maximum power consumption 15 watts? Can it be higher?

### ISSUE THREAD

**Issue by wututu** [Valkirie/HandheldCompanion#326]
Steam Deck Is the maximum power consumption 15 watts? Can it be higher?

**Comment by CasperH2O** [comment]
Yes, the default range of the TDP slider depends on the device specifications. It can be increased at your own risk.

In the main GUI, go to Settings, near the bottom you can enable a larger range and configure it.

See also this video: https://youtu.be/EvLTGbKW7ms?t=70
