### ISSUE TITLE
OneXPlayer Mini Pro (6800u) Shows Unsupported

### ISSUE THREAD

**Issue by jaburgeson** [Valkirie/HandheldCompanion#329]
Like the title says!

The about section of the app says this handheld is unsupported and the default TDP Values aren't correct and have to be adjusted in the app.

It also appears the Max GPU Frequency isn't correct, only going up to 1900MHz vs 2200MHz like the OXP Player App.

Everything appears to be functioning though!

**Comment by CasperH2O** [comment]
Hey @jaburgeson , that sounds good! We have indeed not found the opportunity to dial in the values of this handheld. Could you help the HC team out?

Attached is a tool (technically a keylogger!) that, when you run it, shows the information required to identify your device in a unique fashion. After it opens, can you press all the device special  keys and share the output of this tool with it? Then we can add it to HC. 

You say everything works? Have you tried the 3D overlay mode? Does it have the right orientation and movement? 

[MotherboardInfo.zip](https://github.com/Valkirie/HandheldCompanion/files/10420352/MotherboardInfo.zip)

**Comment by jaburgeson** [comment]
Thanks for the quick response!

The overlay does work, and the 3d model does move, however it doesn't appear that the movement matches what i'm doing in the real world.  

For the Keylogger, I tried running this by clicking on Motherboardinfo.exe and it just closes with an error.  I did this with Admin as well, same...as well as launching through command prompt.  Is there a certain dependency it requires?

**Comment by jaburgeson** [comment]
I figured it out, I had to unblock the app in the Properties of all the dll's. Standby why I get this info for you.

**Comment by jaburgeson** [comment]
It doesn't appear that the button that is used to launch the OXP Player seems tp be registering


Microsoft Windows [Version 10.0.22621.1105]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\System32>"C:\Users\jabur\Downloads\MotherboardInfo\MotherboardInfo\MotherboardInfo.exe"
[09:37:43 INF] Manufacturer: ONE-NETBOOK
[09:37:43 INF] Product: ONEXPLAYER Mini Pro
[09:37:43 INF] Model: N/A
[09:37:44 INF] Version: V03
[09:37:44 INF] PNPDeviceID: ACPI\PNP0C01\C8
[09:37:44 INF] InstallDate: N/A
[09:37:44 INF] PartNumber: N/A
[09:37:44 INF] Status: OK
[09:37:44 INF] SystemName: ONEXPLAYER

[09:37:45 INF] CPU ID: 178BFBFF00A40F41
[09:37:46 INF] CPU Name: AMD Ryzen 7 6800U with Radeon Graphics
[09:37:47 INF] CPU Description: AMD64 Family 25 Model 68 Stepping 1

[09:37:53 INF] -------- KeyDown --------
[09:37:53 INF] RControlKey at 638093722734242576
[09:37:53 INF] LWin at 638093722734562576
[09:37:53 INF] O at 638093722734562576
[09:37:53 INF] -------- KeyUp --------
[09:37:53 INF] O at 638093722734562576
[09:37:53 INF] LWin at 638093722734562576
[09:37:53 INF] RControlKey at 638093722734562576
[09:38:00 INF] -------- KeyDown --------
[09:38:00 INF] LWin at 638093722800812576
[09:38:00 INF] D at 638093722800812576
[09:38:00 INF] -------- KeyUp --------
[09:38:00 INF] LWin at 638093722800962576
[09:38:00 INF] D at 638093722801122576
[09:38:35 INF] -------- KeyDown --------
[09:38:35 INF] LControl at 638093723154242576
[09:38:35 INF] C at 638093723154242576
[09:38:35 ^C
C:\Windows\System32>

**Comment by CasperH2O** [comment]
Excellent work @jaburgeson , especially figuring out why the tool did not work!

I'll get this info into the app and provide a beta build for you to test shortly.

**Comment by jaburgeson** [comment]
Great!!  Looking forward to it.  Thank you!

**Comment by CasperH2O** [comment]
@jaburgeson please find a beta build for the OneXPlayer Mini Pro here: https://github.com/Valkirie/HandheldCompanion/releases/download/0.14.0.9/Handheld.Companion-Release-net7.0-0.14.0.9-OneXPlayerMiniProBeta.exe

Can you check:
- On the about page, does it now state the device is compatible (it will show a mini as an image)
- The special keys can be used for hotkeys and register as OEM1 2 etc?
- Open the 3D overlay model and see if it moves in accordance with your physical movements.

**Comment by jaburgeson** [comment]
Thanks for the update!!  Just tried it out.

**On the about page, does it now state the device is compatible (it will show a mini as an image)**
Yes!  This looks to be working with the correct info and no longer shows unsupported.

**The special keys can be used for hotkeys and register as OEM1 2 etc?**
This doesn't seem to be working.  When I start the service in HC and have it emulating a PS4 Controller, the left button, that would normally show the desktop no longer works, but I cannot map it either in HC.  The right button that shows the Windows Keyboard, keeps showing the keyboard no matter what I do.  It also seems like I'm getting an "OEM3 Long" added to my hotkeys when I'm configuring them.

**Open the 3D overlay model and see if it moves in accordance with your physical movements.**
This is working as it should be now too!

**Comment by CasperH2O** [comment]
@jaburgeson great, a few steps closer. It seems OneNet has changed the OEM keys a bit in this version. Can you perform the following tests:

Test 1

1. Open the motherboard tool again.
2. Press the following buttons in order:
3. Fan
4. Keyboard
5. Function
6. Function + Volume Up
7. Function + Fan
8. Function + Fan (yes a second time)

In my experience it sometimes easier to just open and close the motherboard tool for each press/release, as it becomes hard to distinguish and do everything correctly in a row.

Test 2

1. In the Main GUI, overlay, disable face camera (see image) 
9. Open the 3D controller overlay, leave it for about 30 seconds with the device facing you. Then perform some motions. Does everything looks correctly? If not, please share a video, if you need to host it, Streamable is very nice.

![image](https://user-images.githubusercontent.com/14330834/212681489-495f1b2e-937d-4853-9bf8-145bbf14844b.png)

**Comment by jaburgeson** [comment]
Ok, I just used the OXP Player Button as the Fan button for your steps.  This time it actually shows up in the keylogging app.

Strangely enough, when I start combining these buttons, the way the function buttons work changes slightly.  It seems the Function button + Fan (OXP Player) takes a screen shot, but if you do it quickly...it actually flips controls a bit!  Either way.  I'm going to attach the log file

**Comment by jaburgeson** [comment]
For the overlay.  It looks like it rotates like it is facedown on a flat surface and stays there.  Here are 2 videos.


https://user-images.githubusercontent.com/4240091/212692186-30231704-1edc-4207-b883-efeb3e6a1dc3.mov


https://user-images.githubusercontent.com/4240091/212692242-0c35a5d2-6abf-4896-a2b5-480bc5a4051f.mov

**Comment by CasperH2O** [comment]
@jaburgeson thank you. An update can be found here:

https://github.com/Valkirie/HandheldCompanion/releases/download/0.14.0.9/Handheld.Companion-Release-net7.0-0.14.0.9-OneXPlayerMiniProBeta2.exe

It includes the TDP and GPU ranges and all the hotkeys you mentioned.

Could you double check they register as: 
Fan (bottom right button) -> OEM5
Keyboard -> OEM2
Function (left button) -> OEM3
Function + volume up -> OEM4
Function + Fan -> OEM1

About your videos, it's hard to make out what the position of the device is in relation to something else and thus gravity, can you place it on a desk?

**Comment by CasperH2O** [comment]
@jaburgeson ok, another round. This is taking longer then expected, apologies. The buttons keep changing per device from OneN.

OEM5 = Works Only if OXP Player Is open. As expected, the app reads some other low level IO and generates the keyboard button, done!
OEM4 = Does not work. My fault, I removed a line of code, please try the update.
OEM3 = Works great! Done.
OEM2 = Does not work. I double checked this one, can't find a fault when compared with what you sent. I did accidentally leave an extra space in the code though... It's the keyboard key, correct? Can you try once more with the Motherboard tool and hit it a couple of times?
OEM1 = Works great but of OXP Player is open, it will trigger OXP Player as well (Not sure if this is really a bug though as I would assume they aren't meant to be ran side by side. OXP Player does have fan control though!). As expected, done!

https://github.com/Valkirie/HandheldCompanion/releases/download/0.14.0.9/Handheld.Companion-Release-net7.0-0.14.0.9-OneXPlayerMiniProBeta3.exe

If you find the time to make that video, I would appreciate it a lot. 😃

**Comment by CasperH2O** [comment]
Hey @jaburgeson we really had a nice back and forth thing going, you ok? 😄

**Comment by danmaxis** [comment]
I've installed this version and the virtual trackpad pops up, but it does not work. Is it somehow related to this incompatibility?

**Comment by CasperH2O** [comment]
> I've installed this version and the virtual trackpad pops up, but it does not work. Is it somehow related to this incompatibility?

@danmaxis I doubt it, how are you verifying the trackpads do or do not work? You can use an application called VSCView or use PS Remote Play.

**Comment by danmaxis** [comment]
Oh, my bad. I've tested with VSCView and they work just fine. 
I was thinking that they were converted to mouse trackpad automatically.

**Comment by danmaxis** [comment]
Now, I do have a real issue (Onexplayer mini pro user).

With Handheld Companion app just opened (service disabled and removed), when I push once OXP Player, keyboard button, it seems that it is pushing twice.

That settings overlay open and closes quickly (it only keeps open when I hold the button).
The software keyboard only opens, but pressing again does not close it.

This seems to happen on system startup when HC starts before oxp.exe.

**Comment by CasperH2O** [comment]
Done, thanks everyone for helping out!
