### ISSUE TITLE
Fan control

### ISSUE THREAD

**Issue by Keriam** [Valkirie/HandheldCompanion#330]
Hello,

I would like to know if fan control will be supported for AyaNeo2 : there is an addin in AyaSpace to do it but i would like to use only HC.

Thanks
Regards,

**Comment by CasperH2O** [comment]
Hey @Keriam thanks for reaching out. Fan control is on the todo list, we have the technical know how and some ideas. Due to limited bandwidth it won't be implemented soon though.

**Comment by CasperH2O** [comment]
Work on fan control has been started. This is a duplicate ticket. See: #375
