### ISSUE TITLE
More Hotkey Modifiers

### ISSUE THREAD

**Issue by updawg** [Valkirie/HandheldCompanion#331]
I think a great addition to the hotkey menu would be to enable a modifier key. That way I can select the modifier key and then have the rest of my buttons be used for different hotkeys. My Ayaneo 2 only comes with 4 buttons that are not used by the standard xbox controller layout. If I had a modifier key it would essentially enable 16 additional combinations.

**Comment by CasperH2O** [comment]
Hey what's @updawg ? Currently there are two modifiers, click and long press, so each button is already usable twice. You can also combine buttons, with for example the DPad or something else you prefer.

Can you explain in more detail what other modifiers you'd like to see?

Do you have any programming experience, could you help with this effort?

**Comment by updawg** [comment]
I'm not sure if you are familiar with Retroarch/Recalbox etc. but they have a modifier key set to select by default. Then select + any key can be used to do various actions such as quitting, brining up the retroarch menu, saving, fast fowarding, rewinding, etc.

I figured have more button combinations could lend itself to the following: increasing tdp, decreasing tdp, changing performance profiles, bringing up the on screen keyboard, act as enter key, backspace key, sending ctrl+alt+del, bringing up task manager, act as scrollwheel up/down. Currently we are limited to 8 actions but could increase this exponentially by allowing modifier keys.

I have very little in the way of actual programming experience. Mainly bash/powershell scripting.

Regardless, I wanted to thank you/team for such an awesome program. Can't wait to see what else you bring.

**Comment by CasperH2O** [comment]
@updawg what you mention is already possible, altough a modifier key is not predefined, it's left up to the user. You can define multiple buttons, so select + up or select + down or start + up etc. Then you can define those as click or long press.

**Comment by grandrew** [comment]
Can you explain in more detail how to do this? I am struggling to get it done/understand the UI on current version on Legion Go

**Comment by grandrew** [comment]
I have found a way that I can do in "Hotkeys" a custom multi-button hotkey and assign to keyboard event, but it seems to trigger specifically on "all button up" event, while I want it to trigger on "all button down" event
