### ISSUE TITLE
OSK can't be used to configure custom shortkey keyboard output. 

### ISSUE THREAD

**Issue by azqlop** [Valkirie/HandheldCompanion#332]
1. When using steamdeck and HandheldCompanion, you cannot use the back button to map the handle button
2. When using custom mapping, you cannot use the soft keyboard provided by the Windows system to record keyboard keys

**Comment by CasperH2O** [comment]
@azqlop thanks for reporting.

1. What do you mean with the handle button?
2. Do you mean as an input or as an output?

**Comment by azqlop** [comment]
> @azqlop thanks for reporting.
> 
> 1. What do you mean with the handle button?
> 2. Do you mean as an input or as an output?

1. In hotkeys → costom→custom shortcut, using the L4/L5/R4/R5 (OEM4567) button cannot be mapped to (ABXY, L123, R123)

2. In hotkeys → costom→custom shortcut,After clicking (press to define keyboart output), the key value clicked with the soft keyboard has no response click

**Comment by CasperH2O** [comment]
1. This is correct, custom key inputs can only be gamepad keys, outputs can only be keyboard. This is also stated in the input box as text. In the near future a remapper will be implemented and you can mix and match OEM and ABXY buttons etc.

2. Indeed, I can confirm this is an issue, OSK does not allow for custom key keyboard input in release 14.1.

**Comment by Taboulet** [comment]
I'm having the same issue. How do we fix it ?

**Comment by CasperH2O** [comment]
Fixed in upcoming build #825. Thank you @mseys!
