### ISSUE TITLE
RDP & HC

### ISSUE THREAD

**Issue by designgears** [Valkirie/HandheldCompanion#333]
When connecting via RDP to my device (Ayaneo 2) HC disables as I would expect, or it's crashing at that point. The problem is when I login on to the device physically HC doesn't enable or crashes at this point.

**Comment by CasperH2O** [comment]
Thank you for bringing to to attention, I'll see if I can reproduce it.

**Comment by CasperH2O** [comment]
Regrettably, both my Aya devices come with Windows Home edition and thus have no inbound RDP support. Won't be able to test this with VS running HC in debug.

**Comment by designgears** [comment]
@CasperH2O I can provide a couple keys if you need.

**Comment by CasperH2O** [comment]
> @CasperH2O I can provide a couple keys if you need.

Thank you for the kind offer @designgears , I'll pick this up when I get my Air repaired.

**Comment by CasperH2O** [comment]
Shared by DesignGears on Discord: [HandheldCompanion.exe.11908.zip](https://github.com/Valkirie/HandheldCompanion/files/10857665/HandheldCompanion.exe.11908.zip)

**Comment by CasperH2O** [comment]
Confirmed to be fixed by @designgears
