### ISSUE TITLE
QuickTools content not loaded 

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#338]
Under certain (currently unknown) conditions, QuickTools only shows it's window but not it's content.

Opening the main GUI will populate the content again. As a workaround the same hotkey for QuickTools, could be used as longpress to open the main GUI when this happens.

Image: 
![afbeelding](https://user-images.githubusercontent.com/14330834/213904726-98823fac-809d-4e26-9018-08da2fb3acbf.png)

**Comment by Valkirie** [comment]
Can you replicate with mapper branch?

**Comment by CasperH2O** [comment]
> Can you replicate with mapper branch?

I can sure try, is the remapper branch stable enough? Reproducing this issue is not straightforward, it just happens every so often.

**Comment by CasperH2O** [comment]
Fixed with 0.15 release.
