### ISSUE TITLE
More custom hotkeys

### ISSUE THREAD

**Issue by vendelocky** [Valkirie/HandheldCompanion#343]
Hi, I am a steam deck user and really love HandheldCompanion! So far it's the best and really appreciate all the works. But just a request (or a question maybe). 

Is it possible to have more custom hotkeys? Currently I only see that we can set up to 10 custom keys to map the controller keys with keyboard keys. With the number of buttons Steam Deck has and the combination of controller keys as the listener, I think we can have a lot more! Unless the feature is already there or it's impossible to add more. 

Cheers!

**Comment by CasperH2O** [comment]
Hey @vendelocky thanks for reaching out, glad you enjoy HC. 

Can you share with us how you've used hotkey 1 to 10 already?

Are you familiar with C#, would you like some pointers on where and how the list can be made longer?

**Comment by CasperH2O** [comment]
@vendelocky how many extra custom hotkeys would you like?

**Comment by vendelocky** [comment]
@CasperH2O , is it not possible to have a flexible list of custom hotkeys that we can keep adding without limit?

If not, then depending on how complex it is to have them, probably 20 would be sufficient enough.
Anyway it is just an extra request if possible :)

**Comment by CasperH2O** [comment]
Increasing the number in a hardcoded way is doable, however I found it's not easy to add proper icons for them as we don't have anything specific for 10-20.

**Comment by CasperH2O** [comment]
Coming next EA, limitless hotkey creation. Closing.
