### ISSUE TITLE
Button Mapping

### ISSUE THREAD

**Issue by HanShuishi233** [Valkirie/HandheldCompanion#344]
I'm a steam deck user，I really like this driver，Here are my suggestions

I want to allow the BackPanel key to be assigned to the X360 controller, and also allow all buttons to be customized and interchangeable

**Comment by CasperH2O** [comment]
Hey @HanShuishi233 this is currently being actively worked on. There will be a beta soon, you can help by testing and providing feedback. 👍

**Comment by CasperH2O** [comment]
Implemented with version 0.15.0.0. Excellent work @Valkirie
