### ISSUE TITLE
Controls don't come back when waking from sleep 

### ISSUE THREAD

**Issue by jamie9090** [Valkirie/HandheldCompanion#348]
Fantastic tool. 

Only issue is that ob steamdeck win 10, experiencing a loss of game pad controls when coming back from sleep whilst in a game. 

Manually restating service, disconnecting controller does not help. 

Would love this! 

Thank you!

**Comment by CasperH2O** [comment]
@jamie9090 thanks for reaching out. When this happens, could you check in a browser if the HC controller is seen by https://gamepad-tester.com/ or another game?

In our experience, a lot of games don't like it when coming back from sleep and then HC connects the virtual controller again. That also explains why restarting the service does not work.

**Comment by CasperH2O** [comment]
Several improvements and fixes have been done for waking from sleep in release 0.15. Several people have confirmed this is working better now. Closing ticket.
