### ISSUE TITLE
Ayaneo LED control

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#354]
Add Ayaneo Air, 2 and Geek LED control support.

Has been figured out by Maya (Mayonnaise#7024 Discord) for Linux and Windows using AHK by GDuck (GDuck#9282)

Example code for Linux: https://github.com/JustEnoughLinuxOS/distribution/blob/dev/packages/sysutils/system-utils/sources/scripts/ledcontrol

Maya is making a Linux version in Rust, will share when ready.

> when I'm done with doing ipc protocol I'll release linux service made in rust

Recommendations for Windows:
> as you either need to just write a driver that would channel ec commands into physical memory where ec ram is mapped into
> or accept there being no security
> or accept poor performance
> as writing to ec's ram with out asm instruction is slow and unreliable

Windows
- https://github.com/shubhampaul/EC-Access-Tool with Winring
- For some reason it had to be set 4 times for it to take effect.
- Command in below screenshot turns LEDs off. More to come.

![afbeelding](https://user-images.githubusercontent.com/14330834/216888636-57551b44-12b5-4c4f-8a8c-a5b31843f854.png)

**Comment by Valkirie** [comment]
Where did we get this ? Can we get details about the structure and values here ?

**Comment by CasperH2O** [comment]
@Valkirie see the link mentioned: https://github.com/JustEnoughLinuxOS/distribution/blob/dev/packages/sysutils/system-utils/sources/scripts/ledcontrol

**Comment by CasperH2O** [comment]
Well, I'm closing this one. Not yet released, but definitely implemented! Ready in 0.19.
