### ISSUE TITLE
No Trackpad Scrolling and Haptics Settings

### ISSUE THREAD

**Issue by Sayo4908** [Valkirie/HandheldCompanion#357]
Hi, it's great software, but if you add ability to scroll something using left frackpad it will be even better. I personally use Steam Deck Tools for now because of it. It will be great too if you add haptics strength settings.

**Comment by Valkirie** [comment]
Next update will bring this up for you along with absolute control over inputs mapping.

**Comment by CasperH2O** [comment]
@Sayo4908 , thanks for reaching out, this will be part of the remapping feature. Closing this as duplicate of #344.
