### ISSUE TITLE
Toggle for CPU turbo on and off

### ISSUE THREAD

**Issue by X-kuro** [Valkirie/HandheldCompanion#359]
The CPU of 6800u does not need to frequently let the CPU turbo change the CPU frequency. I hope to add the one-key opening and closing of the CPU turbo.

**Comment by CasperH2O** [comment]
Can you provide some technical insight in to how this can be done? Can you help program it?

**Comment by X-kuro** [comment]
public static void CloseCPUBoost()
		{
			ProcessStartInfo processStartInfo = new ProcessStartInfo();
			processStartInfo.FileName = "powercfg";
			processStartInfo.WindowStyle = ProcessWindowStyle.Hidden;
			try
			{
				processStartInfo.Arguments = "-setacvalueindex scheme_current sub_processor PERFBOOSTMODE 0";
				Process.Start(processStartInfo);
				processStartInfo.Arguments = "-setdcvalueindex scheme_current sub_processor PERFBOOSTMODE 0";
				Process.Start(processStartInfo);
				processStartInfo.Arguments = "-S SCHEME_CURRENT";
				Process.Start(processStartInfo);
			}
			catch (Win32Exception arg)
			{
				Console.WriteLine("系统找不到指定的程序文件。/r{0}", arg);
				return;
			}
			Common.UpdateOSDCPUBoostEnabled(false);
		}

**Comment by X-kuro** [comment]
public static void CloseCPUBoost()
		{
			ProcessStartInfo processStartInfo = new ProcessStartInfo();
			processStartInfo.FileName = "powercfg";
			processStartInfo.WindowStyle = ProcessWindowStyle.Hidden;
			try
			{
				processStartInfo.Arguments = "-setacvalueindex scheme_current sub_processor PERFBOOSTMODE 0";
				Process.Start(processStartInfo);
				processStartInfo.Arguments = "-setdcvalueindex scheme_current sub_processor PERFBOOSTMODE 0";
				Process.Start(processStartInfo);
				processStartInfo.Arguments = "-S SCHEME_CURRENT";
				Process.Start(processStartInfo);
			}
			catch (Win32Exception arg)
			{
				Console.WriteLine("系统找不到指定的程序文件。/r{0}", arg);
				return;
			}
			Common.UpdateOSDCPUBoostEnabled(false);
		}

**Comment by Valkirie** [comment]
Hey, from a user interface standpoint. What would be your expectations here?
How and where would you expect to turn Turbo Boost ON and OFF?

**Comment by X-kuro** [comment]
I wish it could be put in the settings interface, currently the settings interface in the quick tool doesn't show anything other than volume and brightness on my ayaneo geek.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Valkirie/HandheldCompanion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月14日(星期二) 中午1:11
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Valkirie/HandheldCompanion] switch the CPU turbo on and off (Issue #359)





 
Hey, from a user interface standpoint. What would be your expectations here?
 How and where would you expect to turn Turbo Boost ON and OFF?

**Comment by Valkirie** [comment]
Will implement this in a coming build :)
To add elements to your quick tools page, go into hotkeys page and click on the "Pin" icon.

**Comment by Valkirie** [comment]
Implementing this today

**Comment by CasperH2O** [comment]
Closing. Feature implemented (and it works).
