### ISSUE TITLE
QuickTools game profile creation does not save properly

### ISSUE THREAD

**Issue by iTsMute** [Valkirie/HandheldCompanion#361]
creating a profile while in game does not automatically save. You must manually update the profile created from the profiles tab in HC main menu settings for it to save.

**Comment by CasperH2O** [comment]
Can confirm and reproduce. Great a new profile through quicktools with some adjusted settings. Close HC, open HC again, check profile page in Quicktools for same game. Either there is no profile or settings are default.

Workaround is to create the profile through quicktools, then save it in the main GUI.

**Comment by CasperH2O** [comment]
@iTsMute this one is fixed for me in 0.15.0.3 can you confirm?

**Comment by iTsMute** [comment]
> @iTsMute this one is fixed for me in 0.15.0.3 can you confirm?

I believe it is fixed! Didn't want to close this incase you still were able to reproduce the issue.
