### ISSUE TITLE
Installation succeeded but the program could not start

### ISSUE THREAD

**Issue by Yuuki-Rin** [Valkirie/HandheldCompanion#370]
Installation succeeded but the program could not start
Show only one startup icon
Then see that the taskmgr has no process
Build 0.14.2.0

**Comment by CasperH2O** [comment]
Can you share the HC logfile and or crashdump from /mydocuments/handheldcompanion/logs? @Yuuki-Rin

**Comment by Yuuki-Rin** [comment]
There are only dumps under my /mydocuments/handheldcompany
This is one of the files in the folder
[HandheldCompanion.exe.4792.zip](https://github.com/Valkirie/HandheldCompanion/files/10753444/HandheldCompanion.exe.4792.zip)

**Comment by Mehmet529** [comment]
I have same problem 😓

**Comment by CasperH2O** [comment]
Seems something is wrong with checking for HidHide, which was indeed changed in the 0.14.2 update.

![image](https://user-images.githubusercontent.com/14330834/219335821-5bcdba94-abcf-450d-95a4-d65281ce8901.png)

Can you @Yuuki-Rin and @Mehmet529 double check HidHide is properly installed (and which version)?

**Comment by CasperH2O** [comment]
@Yuuki-Rin and @Mehmet529 , can you reproduce the crash with the debug build found here, it will provide more log information for us to determine what the problem is.

https://github.com/Valkirie/HandheldCompanion/releases/download/0.14.2.0/Handheld.Companion-Debug-net7.0-0.14.2.0.exe

Again, please provide the crash dump from /documents/handheldcompanion/dumps

**Comment by Yuuki-Rin** [comment]
This version can run normally @CasperH2O

**Comment by CasperH2O** [comment]
@Yuuki-Rin in that case, perhaps something went wrong during installation and another install fixed it. Glad it works now.

For regular use, I recommend you do use the normal build, as the debug build is a bit heavier in CPU resources etc.
