### ISSUE TITLE
Service not properly starting with HC main GUI

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#374]
Observed and reported by littlek4za#4028.

> having trouble after update to 0.14.2
> service not starting by itself
> before update, I have uninstall the vgembus driver, hidhide and HC, deleted the documents/handheld companion
> then only proceed to installed the latest version
> have tried toggling with the option "start with companion", but no luck, service not automatically starting when HC is started 
> last time the startup type was in manual right?
> now will need to put it to automatic, only the service will be started when HC is started 
> no issue with 0.14.0.9

![afbeelding](https://user-images.githubusercontent.com/14330834/219554988-3ac7708e-3e62-41f2-9114-bfcf70b9a6d1.png)
![afbeelding](https://user-images.githubusercontent.com/14330834/219555000-15c4214c-32c7-441c-b6f5-12f58e6a4836.png)

https://user-images.githubusercontent.com/14330834/219555097-e32cd430-a2b3-47f5-8510-c13203a1474a.mp4

https://user-images.githubusercontent.com/14330834/219555105-784a5726-f6bb-4b03-bc3c-5323838b6081.mp4

**Comment by david-christ** [comment]
Have the same issue, I set "Startup Type" to "automatic" and it works.

**Comment by CasperH2O** [comment]
Can confirm this issue, also, "Automatic" indeed seems like a workaround for now.

**Comment by david-christ** [comment]
I am not 100% clear what impact these two options are supposed to have in HC. I toggled it to automatic, assuming that in that case Windows takes care of starting/stopping the daemon, instead of HC?!

**Comment by Valkirie** [comment]
I'm almost certain I fixed this issue with the next update but I'll double check. Setting service startup to Automatic means Windows will take care of starting it rather than leaving this task to HC UI.

**Comment by CasperH2O** [comment]
Seems fixed with 0.15.0.0. Can't reproduce. Thank you @Valkirie
