### ISSUE TITLE
Fan control

### ISSUE THREAD

**Issue by X-kuro** [Valkirie/HandheldCompanion#375]
```
Common.ECRamWriteWM2(1098, 1);
 Common.ECRamWriteWM2(1099, speedData);

public static void ECRamWriteWM2(ushort address, byte data)
		{
			if (Common.ols == null)
			{
				Common.OlsInit();
			}
			if (Common.ols == null)
			{
				return;
			}
			byte value = (byte)(address >> 8 & 255);
			byte value2 = (byte)(address & 255);
			try
			{
				Common.reg_addr = 78;
				Common.reg_data = 79;
				Common.ols.WriteIoPortByte(Common.reg_addr, 46);
				Common.ols.WriteIoPortByte(Common.reg_data, 17);
				Common.ols.WriteIoPortByte(Common.reg_addr, 47);
				Common.ols.WriteIoPortByte(Common.reg_data, value);
				Common.ols.WriteIoPortByte(Common.reg_addr, 46);
				Common.ols.WriteIoPortByte(Common.reg_data, 16);
				Common.ols.WriteIoPortByte(Common.reg_addr, 47);
				Common.ols.WriteIoPortByte(Common.reg_data, value2);
				Common.ols.WriteIoPortByte(Common.reg_addr, 46);
				Common.ols.WriteIoPortByte(Common.reg_data, 18);
				Common.ols.WriteIoPortByte(Common.reg_addr, 47);
				Common.ols.WriteIoPortByte(Common.reg_data, data);
			}
			catch
			{
				Common.OlsFree();
			}
		}
```

OLS is WinRing0x64.dll

**Comment by CasperH2O** [comment]
@X-kuro thank you for sharing. We have plans to add LED and fan control to HC soon. 🙂

**Comment by CasperH2O** [comment]
winmax2 EC Address（4E,4F）：Control:0x275，0-auto，1-manual；Speed Set-0x1809，from 0 to 184，Max184-100%；Speed Read-0x218，0x219，real rpm，0x218-high byte，0x219-low byte。
That's the ec address. EC API I will upload tommorrow.

ayaneo2 & Geek EC address（4E,4F）：Control:0x44A，0-auto，1-manual；Speed Set/0x44B，0-100， Max100-100%；Speed Read:0x1809，0-255，Max255-100%

Air & Air pro are a little different.
ayaneo air & air pro EC address（4E,4F）：Control:0x44A，0-auto，1-manual；Speed Set/0x44B，0-100， Max100-100%；Speed Read:0x1803，0-255，Max255-100% 

onexplayer2 EC address（4E,4F）：Control:0x44A，0-auto，1-manual；Speed Set:0x44B，0-184，Max184-100%；Speed Read:0x1809，0-184，184-100%

onexplayer mini pro & aokzoe EC address（4E,4F）：Control:0x44A，0-auto，1-manual；Speed Set:0x44B，0-255，Max255-100%；Speed Read:0x1809，0-255，255-100%

win4 EC address（2E，2F）：Speed Read：0xC880,0xC881，C880-high byte，C881-low byte；Control：0xC311，0-auto，>0:manual，Set Speed from 1 to 127，127-100%.

**Comment by CasperH2O** [comment]
Has been implemented and verified to be working for various devices.
