### ISSUE TITLE
Steam deck  secondary external screen rotated when application opened first time. Can not be restored - reverted!

### ISSUE THREAD

**Issue by Szab0t** [Valkirie/HandheldCompanion#377]
When installing it on Steam Deck. My external screen rotated 90 degree clockwise. Steam deck screen cloned to the external screen. 
After after uninstalling the Controller Companion this issue still remain.
Windows reporting that the external screen is still in landscape mode. Whatever I tired so far this setting can not be reverted trough the Windows or AMD display settings. The controller companion possibly did something kernel level which **can not be reverted.** on the Steam Deck.

**Comment by CasperH2O** [comment]
Hey @Szab0t this Github is for Handheld Companion, not controller companion. You can find controller companions website here: 

http://controllercompanion.com/
https://store.steampowered.com/app/367670/Controller_Companion/

**Comment by CasperH2O** [comment]
Closing issue, does not seem to be a HC issue and no response from poster.
