### ISSUE TITLE
Add Steam Deck as virtual controller

### ISSUE THREAD

**Issue by david-christ** [Valkirie/HandheldCompanion#379]
How hard is it for you to add new controllers? I wonder whether it would be possible to emulate the Steam Deck's built-in controller in a way that Steam recognises it as such.

Currently there are two virtual controllers, Xbox and DS4. When using the Xbox controller, Steam will show ABXY button prompts, but of course the controller does not have a Gyro or Trackpads. The DS4 has a gyro and a trackpad, however Steam shows triangle, circle, square, X button prompts.

The Steam Deck's build-in controller has two trackpads (HC already has virtual trackpads, or you could use the whole screen of a compatible handheld with touch screen), and it has back pedals (some handhelds have separate buttons, like LC and RC on Ayaneo 2/Geek). This would allow the full range of possible inputs from a non-Steam-Deck handheld to map on Steam-recognised controller inputs.

**Comment by CasperH2O** [comment]
Currently HC makes use of Vigem to simulate controllers. Vigem currently has support for Xbox360 and DS4. 

I don't fully understand your use case, but it's also possible with HC to set the virtual controller to disconnected and then perhaps just use your SteamDecks controller?

**Comment by david-christ** [comment]
My use-case is that I have an Ayaneo 2, but am primarily running Steam Big Picture Mode, so it would have been nice if I could present the Aya hardware as Steam Controller (instead of Xbox or PS controller) to Steam.

Would only have been a nice to have, but if it is technically not easily doable right now, I'll close this.
