### ISSUE TITLE
Add time to overlay

### ISSUE THREAD

**Issue by david-christ** [Valkirie/HandheldCompanion#380]
Currently the bottom "status bar" of the overlay only shows battery information. It would be great if it could show the current time also.

E.g. like this:

![overlay](https://user-images.githubusercontent.com/90661517/221763284-7a10450b-e3c9-44c0-b517-4335fe3bfade.png)

**Comment by CasperH2O** [comment]
Agreed. Would be a nice feature. Are you skilled in programming by any chance? We'd welcome a PR.
