### ISSUE TITLE
App won't start on Steam deck

### ISSUE THREAD

**Issue by Mehmet529** [Valkirie/HandheldCompanion#381]
app is installed properly but won't start
Is there any program I need to install?

**Comment by DennisTarr** [comment]
Im on Steam Deck with Windows 10 and the complete Installer works just fine. Apart from the Docking Station bug and various cosmetic issues everything works fine

**Comment by CasperH2O** [comment]
Closing due to lack of response from issue creator. 

Please try the newest release (0.15.0.3) and let us know if you still have this issue.
