### ISSUE TITLE
"Cannot start service 'ControllerService"

### ISSUE THREAD

**Issue by SevenNatLor** [Valkirie/HandheldCompanion#382]
![Capture](https://user-images.githubusercontent.com/126664481/222104692-11bbdbb9-d339-4cc9-a94f-67ee1ffc79a8.PNG)

I don't really know what's caused this besides changing the root folders directory from within a folder to outside said folder but still the same drive. 

I started up Skyrim but decided to quit to add another mod. When I started it again, I first noticed the cursor suddenly appearing and didn't think too much about it until I realized none of the controls were working. This was caused by me not starting the service but when I did I got the error. Eventually after restarting it did work, or at least seem to, but turns out it didn't. Afterwards I exited the companion and decided to use the normal steam deck controls but they weren't working either. I went into big picture mode and apparently steam wasn't detecting the internal controls but they were still working. Booted up the companion app again and tested both 360 and ds4 inputs and steam showed the corresponding button layouts but only the thumbsticks and the A B buttons were working. 

I plan to completely reinstall windows since everything important is stored on an sd so this is more an offer to use my deck as a guinea pig for possible solutions. Ran in admin, only thing that changed with the deck were the skyrim files, latest update, fresh install of Companion, no signs of anything wrong beforehand.

**Comment by CasperH2O** [comment]
I have a really hard time understanding what you are trying to say. There might be a language barrier, please be patient with me.

Can you share the Handheld Companion logfiles in: C:\Users\K<username>\Documents\HandheldCompanion\logs ?

**Comment by SevenNatLor** [comment]
I don't have the logs file, oddly enough

**Comment by SevenNatLor** [comment]
Checked steam controls by clicking the Steam button at the top left, went down to controllers
