### ISSUE TITLE
TDP not sticking anymore (Steam deck)

### ISSUE THREAD

**Issue by iTsMute** [Valkirie/HandheldCompanion#383]
It seems going lower then what is needed it will stick but trying to adjust above what is actually needed it will not do. 

Playing control I have FPS capped at 40 with no tdp override this requires 8w TDP. if I try to put it at 10w TDP it will not go above that 8 w TDP, if I put it down to 6w TDP it will go to that. On remote play I try to put it above 4w TDP and it will not budge. I messed with windows power profiles and it would fluctuate finally above 4 tdp but would drop right back down to 4w tdp even if I set the minimum globally to higher then that or within the profile for the application. It's just refusing it.

**Comment by CasperH2O** [comment]
How are you adjusting TDP? Through hotkeys?

**Comment by iTsMute** [comment]
No hot Keys. I've done it through quick access menu per game profile tab. I've don't the workaround where you go to main gui and update the profile. I've done it in global settings as well.

**Comment by CasperH2O** [comment]
Mmmhhh, this is with release 0.14.2? Can you make a screencast, I'm having trouble understanding?

**Comment by CasperH2O** [comment]
After having watched the video's I don't see anything out of the ordinary, some games don't max out the TDP especially with FPS caps on. 

Best to check with a greedy game with uncapped FPS and having an OSD like RTSS showing TDP. Emulators or FPS games come to mind.

**Comment by iTsMute** [comment]
The tdp over ride is not supposed to stick above what is required even if it is being told to do so? I thought that was the point of over riding?

**Comment by TheStalwart** [comment]
The point of TDP override is to sacrifice performance to get more play time _when APU utilization is close to 100%_. If you're hitting desired FPS limit, it means APU utilization is <100%. It's not a space heater, it will only consume power when there is a task to perform

**Comment by iTsMute** [comment]
Well my point has been proven regardless. The tdp is now sticking above what is required when I tell it to. So whether I'm right or wrong myself. Something still isn't working properly. If it's not supposed to do it, then it is now doing it. If it is supposed to do what I thought initially, then it wasn't before. 🤷

**Comment by iTsMute** [comment]
I believe this discussion ca
