### ISSUE TITLE
Ayaneo Geek - OEM1 Button defaulting to Xbox guide/PS not working

### ISSUE THREAD

**Issue by sombody88** [Valkirie/HandheldCompanion#393]
On 0.15.0.2 with an Ayaneo Geek

With the latest update, the new improvement _OEM1 will be defaulty mapped to Xbox Guide / Sony PS buttons_  seems to not be working. Pressing ayaneo button which was OEM1 is not doing anything. I would prefer to still have the option to set the Xbox guide button to whatever we want even if the Default value is OEM1. In this newer version there is no way to set hotkey for the xbox guide button.

**Comment by mikeustin** [comment]
Ayaneo 2 confirm the problem

**Comment by CasperH2O** [comment]
@sombody88 @mikeustin , in release 0.15.0.4 the guide button was moved to the profile remapper. Please double check your profile is correctly configured.

![image](https://user-images.githubusercontent.com/14330834/228836974-a5198900-2af1-45e2-800e-951d6e689d42.png)

**Comment by CasperH2O** [comment]
No response for original ticket creator. OEM buttons and layout remapper have been significantly reworked since then. Closing ticket. Feel free to reopen if this is still an issue.
