### ISSUE TITLE
Space Key Name?

### ISSUE THREAD

**Issue by xt234** [Valkirie/HandheldCompanion#394]
Not really a bug but im trying to map a button pad on the steam deck to be the space key using the desktop layout editor tho im not sure what its called there.

**Comment by CasperH2O** [comment]
@xt234 I'm not sure. It's probably the "empty" entry beneath "Mode Change"? Perhaps @Valkirie can tell us?

**Comment by xt234** [comment]
Mb for the late comment but yeah it is the empty entry beneath mode change.

**Comment by CasperH2O** [comment]
Great, thanks for confirming.
