### ISSUE TITLE
PageUp and PageDown buttons for remapping

### ISSUE THREAD

**Issue by eugenov** [Valkirie/HandheldCompanion#398]
Hello!
First of all, its awesome handheld app i use heavily every day!
In last update (0.15.03) I didn't notice pageup/pagedown mappings. Could you add them?
Thanks!

**Comment by CasperH2O** [comment]
Indeed, interesting, I don't see them in the list either. Not sure if this is a bug or a missing item. I see various duplicates and keys I don't recognize in the list though.

**Comment by Havner** [comment]
They are as "Next" and "Prior".
The names on the list of keys sound strange, but it looks likes a list from some external lib/define. And those they are marked as such, e.g. on MacOSX.
Also "Alt" is "Menu" :-)

**Comment by CasperH2O** [comment]
Thanks @Havner , glad you got it working @eugenov . We can close this one, but I'll make a new one as an improvement ticket for improving the naming in that list.
