### ISSUE TITLE
GPD WinMax 2 "9" and "0" buttons stopped to work

### ISSUE THREAD

**Issue by eugenov** [Valkirie/HandheldCompanion#399]
After 0.15.0.3 update cannot type 9, 0, ( and )
I guess its because on my winmax there is 2 mappable oem buttons, they usually print 9 and 0. Right now buttons 9 and 0 print oem2 and oem3 in HC mapper

**Comment by CasperH2O** [comment]
Yes. This is "expected" behaviour, as HC captures the hotkey. Are you using those buttons for hotkeys in HC?

**Comment by Valkirie** [comment]
I'll look into this

**Comment by Valkirie** [comment]
Fixed it on next build.
