### ISSUE TITLE
PS home button stops working after toggling "Desktop mode"

### ISSUE THREAD

**Issue by iTsMute** [Valkirie/HandheldCompanion#403]
- open remote play/chiaki
- test ps button (special) should work
- toggle on "Desktop mode"
- toggle off "Desktop mode"
- test ps home button (not working) 
-close remote play/chiaki 
-make sure "Desktop mode" toggled off
-open remote play/chiaki again
-test ps button (works again)

Will tag this in the discord with a video

**Comment by Valkirie** [comment]
Couldn't reproduce it using a different software. Can you have a look at your default profile, does it have a strange path linked to it?

**Comment by iTsMute** [comment]
Just checked it has no profile path way. The profiles I have created Do. For some reason even after a fresh install of windows and disabling (onedrive) my profiles always find there way into a one drive folder. I have no clue why.

**Comment by iTsMute** [comment]
Not since I last checked (yesterday). Will check once more today. If it's still not working I'll close this ticket since I'm the only one who seems to be effected by it. I can just use my work around for now I don't mind.

**Comment by iTsMute** [comment]
Issue still present (closing) due to workaround being super simple. 

Work around: Open chiaki with controller profile enabled and desktop layout disabled.
