### ISSUE TITLE
Sleep issue (High CPU usage, idle TDP, Mouse sensitivity)

### ISSUE THREAD

**Issue by iTsMute** [Valkirie/HandheldCompanion#404]
Very high CPU usage from Handheld companion and controller service after device has been left in sleep mode with services running. Idle TDP also sits at 10w instead of the normal 3w during this. Cause fan to ramp up.

Steps to Reproduce
- have HC started/running
-sleep your device over night
-upon waking your mouse sensitivity on joystick will be super high
-check task manager for CPU usage
-check HWinfo for high TDP (CPU package power) 

Possible workaround (for now) stop services before sleeping. 

 (high CPU usage, High idle TDP and high sensitivity mouse) anytime I see the mouse sensitivity is abnormally high I always check cpu usage and it's very high. I also always check my "CPU package power" and it is high aswell sitting at 10w instead of the normal 2w to 3w.

**Comment by Valkirie** [comment]
I'm on it. Might have a test build ready today.

**Comment by DennisTarr** [comment]
Cool! :)
On a side note: did some testing and the issue only occurs when in sleep mode for >30 min. When only in sleep for a few minutes HC goes up to <10% for a few seconds and then everything works fine.

Maybe it would be a usable workaround to just restart the service when HC detects waking up from sleep? Or just stopping service when going to sleep (if that is possible)

**Comment by Valkirie** [comment]
I can indeed get the service to halt on sleep and restart on resume but I want to circle the issue rather than bypass it :)

**Comment by DennisTarr** [comment]
There is no testbuild yet Im not just blind?

**Comment by CasperH2O** [comment]
> There is no testbuild yet Im not just blind?

No test build yet. The code is in though, so you can compile it yourself if you want.

**Comment by CasperH2O** [comment]
@iTsMute can you confirm the test build no longer has this issue?

**Comment by CasperH2O** [comment]
@DennisTarr the test build can be found here: https://github.com/Valkirie/HandheldCompanion/releases/download/0.15.0.3/Handheld.Companion-Debug-net7.0-0.15.0.3.exe

**Comment by DennisTarr** [comment]
Thanks! Just testing it now. Waking up after 30 min works fine with now rising in CPU load. Now will leave it for a few hours and see. So far so good :-)

**Comment by iTsMute** [comment]
@CasperH2O I can confirm. It's fixed. Slept the device over night with servifes running, no issues upon wakinn device. Will be closing this ticket.
