### ISSUE TITLE
Change default desktop layout

### ISSUE THREAD

**Issue by xt234** [Valkirie/HandheldCompanion#405]
so the app currently doesnt use gamepad mode when using the modified desktop layout. And in gamepad mode the trackpad click on the steam deck doesnt work.

**Comment by CasperH2O** [comment]
You can change the layout of Desktop mode on the HC GUI Controller page. 

![afbeelding](https://user-images.githubusercontent.com/14330834/226170745-0f2a06a6-5625-4af0-81ab-a90f07ed108b.png)

**Comment by xt234** [comment]
that is not the default desktop layout.

**Comment by CasperH2O** [comment]
HC now has the option to tick "use this layout as template" on the layout page, making it easier to reuse an existing configuration.
