### ISSUE TITLE
Disconnecting a controller can bug out the target controller selection

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#416]
Happens on a SteamDeck with 0.15.0.4 if that is important.

Steps to reproduce:
1. Run the HC
2. Service enabled
3. Disconnect the controller (on target controller selection)
4. Exit HC
5. Restart HC
6. When service is launched the controller selection comboboxes are empty and the spinner on the image with 3 controllers spins indefinitely.

Restoring all the settings (deleting Documents/HC directory) doesn't fix that. I had to reinstall. After reinstall it was still reproducible. Had to reinstall again.

**Comment by Valkirie** [comment]
Looking into it.
