### ISSUE TITLE
Desktop mode: unmapped controls are passed on as selected target controller

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#418]
Reproduced on SteamDeck with 0.15.0.4.

Controls in desktop mode that are unmapped (set to None) are passed on as selected Target Controller buttons. This can clearly be seen with joy.cpl.

Funny thing is that (as a workaround) setting them from None to Button/Trigger in the left combo box but not specifying anything in the right combo box can mitigate this.

This issue causes some issues on windows 10 apps as some controller buttons are mapped for whatever reason.
E.g.: Windows 10 settings application. Right and left triggers scroll up and down.

**Comment by CasperH2O** [comment]
This reads like it's working as intended, not remapping buttons make them behave as the actual buttons. However, I agree that setting it to "None" can also imply that it does not get used at all i.e. is inactive. 

Wording and thus user expectation should be improved.

**Comment by Havner** [comment]
Yeah, definitely an option to be Disabled is needed there. When I have mouse buttons on Soft Pull I really don't expect any other option (like the full trigger) to be doing anything (or at least I need an option to mark them not to be doing anything). Same when I bind up/down/left/right on a joystick I don't expect the whole joystick to work. And this is how it behaves now.

Disabled and Passthrough sounds great.
