### ISSUE TITLE
Applying a desktop layout to game profile links them

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#419]
Reproduced on a SteamDeck with 0.15.0.4

Steps to reproduce:
1. Create a new game profile
2. Apply a desktop profile to it
3. Scroll down in the profile and eneter Controller Layout
4. Change something and go back
5. Enter Controller menu -> Desktop Layout -> Edit
6. Changes made in the game profile are now in Desktop profile

The link gets broken on app restart.

**Comment by CasperH2O** [comment]
@Havner what do you mean with step 2, applying a desktop profile to it?

**Comment by Valkirie** [comment]
Can reproduce. Will fix.

**Comment by Havner** [comment]
> @Havner what do you mean with step 2, applying a desktop profile to it?

From the templates. The last template is the desktop configuration that is being continually updated when desktop configuration changes.

**Comment by Valkirie** [comment]
Fixed https://github.com/Valkirie/HandheldCompanion/commit/35359377c7e6e2473f3032b00de82f37c5246dc8
