### ISSUE TITLE
Mouse scroll is overly sensitive, even set to 5.

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#420]
This happens on SteamDeck with 0.15.0.4. Windows mouse settings are default. They work well with a physical mouse connected.

Mouse scroll assigned to either joystick or touchpad (both left in my case) is overly sensitive, even on the lowest setting of 5.
One doesn't need to look far as with such a setting it's difficult to even control page position in the HC UI itself. It's so sensitive that it's hard to scroll by partial page, even with very little movement it often scrolls more than one window height.

**Comment by CasperH2O** [comment]
Indeed, need to adjust the range / multiplier in the back end and adjust slider range accordingly.

**Comment by CasperH2O** [comment]
Pushed a commit to improve this, also found the reason why it was so far off, the sensitivity multiplier was applied twice. 

Needs proper rework in the future, split mouse movement and scrolling sensitivity from one another.

**Comment by Havner** [comment]
This indeed works much better now, so for a quick fix that's much better.

In details there are still few things.
1. The usable range is pretty low for a touchpad, 90-100.
2. The sensitivity for a touchpad seems to define the amount of touch input required to trigger the scroll. IMO this should define the output speed (not sure if the scroll here is treated as on/off or analog)
3. Similar to 2 is the joystick. It would be ideal if you could achieve a situation when very little joystick deviation is very slow scroll and full deviation is very fast with all the speeds in between. Right now when I set the sensitivity to 35 (which I found is the closets to usable for me) I get few scrolling speeds for various deviations but only 2-3 and they don't differ much.
4. And most important, scrolling in the HC app is still very difficult but it seems it's the fault of the HC UI, rather then this bug. The minimal scroll amount is like half the height of the window, so precise scrolling in the app is still impossible.

Up to you what to do with it. I'll open a separate bug for the 4. The rest can be left for "future rework" I suppose. It's usable now. Thanks!

**Comment by CasperH2O** [comment]
I also noticed point 4, no clue why that is though. Not that familiar with WPF, but it works in other applications like Notepad++ and FireFox just fine.

As mentioned the whole thing needs proper rework.

**Comment by Havner** [comment]
I've fixed point 3 in #446

**Comment by Havner** [comment]
1 and 2 are fixed in #449

**Comment by Havner** [comment]
I feel this can be closed. Points 1 and 2 from my list are fixed with #449. I've made a separete bug report for point 4.

And I'm not really sure what you mean by "split mouse movement and scrolling sensitivity from one another". They are separate. Every Action has its own sensitivity.

**Comment by Valkirie** [comment]
All good indeed. Good job ! Closing.
