### ISSUE TITLE
Please make a feature to export game’s layout as a template

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#426]
As in title. That would greatly improve adding new games and new profiles if we could easily create our own templates. 

And BTW. Thank you for this software. It’s the first one so feature complete that I can play mouse/keyboard games without using steam remapper.

**Comment by Valkirie** [comment]
This is how things should look like. (Manually created a community template).
![image](https://user-images.githubusercontent.com/934757/228798896-f7201dc4-ed74-42a5-a504-5b6b17f763b6.png)

**Comment by Havner** [comment]
Implemented and working
