### ISSUE TITLE
Not working with Tchia

### ISSUE THREAD

**Issue by jordansoper** [Valkirie/HandheldCompanion#428]
hello

bit of a strange one.

I have a onexplayer mini amd, and with HC open, I can get to the menu, the controller works to skip cutscene and the 'press any button' prompt, but won't work in the menu or ingame.

running game in admin makes no difference

**Comment by Valkirie** [comment]
Can you try and create a profile for the game, then into this profile change check the DInput checkbox.

**Comment by jordansoper** [comment]
That worked perfectly, thank you
