### ISSUE TITLE
Profiles are not being applied on game start

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#430]
I've got impatient for the newest release so I compiled it myself.

Tested on SteamDeck on [655a4fc](https://github.com/Valkirie/HandheldCompanion/commit/655a4fcaa684d9e0e2c18f637476e77cb5e39750)

There is a new switch on the profile's layout menu. I presume its purpose is to enable controller remapping in a profile. Unfortunately, regardless of the state of that switch the profile is not being applied on game start. I start the game, I still have the default profile. I use the default profile for desktop to have auto switching when I start/stop the game.

**Comment by CasperH2O** [comment]
Thanks for letting us know @Havner , if I can summurize, basically you're saying, when the remapper toggle is set to enabled, no remapping is done for the applicable game?

**Comment by Valkirie** [comment]
Can reproduce

**Comment by Valkirie** [comment]
@Havner are you hitting the **Update profile** button once you've toggled Controller layout switch ?

**Comment by Havner** [comment]
> @Havner are you hitting the **Update profile** button once you've toggled Controller layout switch ?

I do. I have to use the "Desktop" profile due to the other bug I've reported, but I do.

**Comment by Havner** [comment]
Tested on 6287e7e

It works with notepad. It doesn't work with full screen games (I've tried Disco Elysium and Hollow Knight).

It doesn't switch profiles to those games. It doesn't detect them running in the foreground.

1. Open GOG galaxy window
2. Run notepad from the start menu
3. Quicktools -> notepad profile is visible

1. Open GOG galaxy window
2. Run game from this window and wait for it to display in fullscreen
3. No toast notification
4. Open quicktools -> you can still see GOG galaxy.exe there

So the bug doesn't seem to be with profile switching, but detecting full screen foreground games broke since 0.15.0.4

**Comment by Havner** [comment]
Can you reproduce it?

**Comment by Valkirie** [comment]
> Can you reproduce it?

I'll have to install GOG galaxy.

**Comment by Valkirie** [comment]
Can't reproduce with Noita
![image](https://user-images.githubusercontent.com/934757/230337446-f2a8ea0c-e7c7-4312-9141-1d0303b63b39.png)

**Comment by Havner** [comment]
> > Can you reproduce it?
> 
> I'll have to install GOG galaxy.

You don't. It's not a matter of galaxy. I just happen to run it through it, but I just as well could have run it directly.

And I meant a fullscreen game. Maybe lack of frames for detecting window params is a key here. I tried at least 3 fullscreen games and none worked.

**Comment by Valkirie** [comment]
I was able to reproduce it !

**Comment by Havner** [comment]
> I was able to reproduce it !

You don't even know how happy that makes me :-D That's the biggest blocker for me for using the latest git version with all the recent fixes :-D

**Comment by Valkirie** [comment]
Long story short, we've got multiple ways to capture running processes.

- Listen for created window(s) : Seams to fail with fullscreen app.
- Hook foreground window changes : This one can capture any app.

To reduce code duplication, I made sure that when we detect a window change, we wait for the asynchronous "created window" call which tends to come later. But in the case of full screen applications/games, this call never arrives. I will fix this regression.

**Comment by Valkirie** [comment]
You might want to try now: https://github.com/Valkirie/HandheldCompanion/commit/54448787fff902335a3cccbaa172bc2f7a8d4fa6

**Comment by Havner** [comment]
I will when I get back home today. Thanks!

**Comment by JustAKat** [comment]
Hi, not sure if opening a new issue would be required, but though this has fixed the issue of fullscreen apps in general, there is still one edge case where it does not work with.

One such example would be Genshin Impact, which due to its anticheat, would run in administrator mode.

With one of the recent builds, [Build 0.15.1.0](https://github.com/Valkirie/HandheldCompanion/releases/tag/0.15.1.0), when switching to the game in question, the third tab will display nothing for the app field at all, and the Create profile button will be disabled.

![Image depicting the issue](https://i.imgur.com/zyH0mD3.png)

This is in spite of a profile existing for it, too.

![Image showing that a profile does exist for it](https://i.imgur.com/93OeDON.png)

Is there a way for HC and/or its service (when in automatic mode) to run in administrator, to properly detect games that may also run in admin (perhaps due to their anticheats)?

**Comment by Havner** [comment]
HC is running as admin. This issue has to be related to something else.
