### ISSUE TITLE
Clicking "update profile" disables the default profile.

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#431]
Tested on [655a4fc](https://github.com/Valkirie/HandheldCompanion/commit/655a4fcaa684d9e0e2c18f637476e77cb5e39750)

I use the default profile as a desktop profile to have auto profile switching when I start/stop the game. With such a use case with the default profile active do as follows:

1. Open some profile (other than default)
2. Make sure the new switch on the Profile's layout at the bottom is turned on.
3. Hit update profile.
4. The default profile gets deactivated.

**Comment by CasperH2O** [comment]
Thanks for letting us know @Havner , when you are talking about 2. is that the new toggle switch to enable/disable the remapper? In point 4, do you mean the remapper toggle or the profile active toggle?

**Comment by Havner** [comment]
In point 2 I mean the new toggle.
In point 4 I don't mean any toggle. I mean the mappings themselves. Like I said, the default profile is my main profile for using the desktop. And when I hit "update profile" it simply stops working. Maybe the profile I'm updating gets activated? I cannot move my mouse anymore. I have to fallback to the "Desktop" profile with a hotkey.

**Comment by Havner** [comment]
Confirmed fixed with https://github.com/Valkirie/HandheldCompanion/commit/c30e3af4af1f0e5238500a58740a88124fe9ed4f
Thanks!

**Comment by Havner** [comment]
I've tested it with https://github.com/Valkirie/HandheldCompanion/commit/c30e3af4af1f0e5238500a58740a88124fe9ed4f
Not reproducible anymore. Thanks!
