### ISSUE TITLE
Make the currently active profile clearly visible somewhere

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#432]
It would be very useful if the currently active profile (Desktop/Default/Game's) be very clearly visible somewhere. Like e.g. the application window title and bottom bar of quicktools (next to battery info).

I had some issues with profiles not always applying properly on 0.15.0.4 which I cannot narrow down quite exactly. When new version release and there are still some issue it would help profoundly to narrow that down.

Also this is useful for the user as well to make sure he did everything right while creating profiles.

**Comment by CasperH2O** [comment]
The currently applied profile can be found in the Main GUI on the profile page (it get's automatically loaded for convenience) and in the QuickTools profile tab. 

During debugging, I use SnakeTail to tail the HC log, which also states which profile is being applied. 

http://snakenest.com/snaketail/

**Comment by Havner** [comment]
The quicktools I'll have to test, thanks. Forgot about it.

The main GUI I feel is not exactly enough as something that's being updated realtime would be useful.

**Comment by Havner** [comment]
I've tested the QuickTools. It shows apps/profiles on the fly, but it's lacking a crucial info, when the profile falls back to the default one.

**Comment by CasperH2O** [comment]
From a "simple" user experience perspective, I'd prefer not to add this, simply because it should simply work automagically. 

Obviously, if there's an issue and when debugging or trying to figure out whats wrong it's helpful to have this extra information.

**Comment by Havner** [comment]
With latest fixes for profiles and Toast notifications (I did not know about them at the time) I think this can be closed.
