### ISSUE TITLE
OEM buttons used in remapper input both the remapped button and their keyboard chords

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#433]
As reported on Discord, perhaps also explains some other reported issues.

Steps to reproduce. 

- Make a new profile for your browser with a device that has OEM1 for the guide button (default configuration for most)
- On gamepadtester.com, use OEM1, this will show button 16 being pressed (xbox guide button)
- On https://www.keyboardtester.com/, use OEM1, this will show Win+Ctrl+F12 being pressed (in case of Ayaneo Neo OEM1).

Probably better of OEM chords are also captured when they are used by the remapper, same as for hotkeys?

**Comment by Valkirie** [comment]
I'm on it.

**Comment by Valkirie** [comment]
Fixed with https://github.com/Valkirie/HandheldCompanion/commit/a1b8222455981a66773c5b20b6dbd0aedaea8730
