### ISSUE TITLE
Sometimes when quitting a game the profile doesn't fallback to the default automatically

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#434]
Tested on SteamDeck, 0.15.0.4.

It doesn't happen always. But sometimes when quitting the game the profile doesn't automatically switch to the default one. Especially when there is no other window and when quitting the game you go back directly to desktop.

I have to open some window for the HC to find its bearings and switch to the default profile.

This is one of those bugs with profiles I mentioned. I can't find a 100% reproducible path but it happens quite often for me.
Probably the best I can is something like:

1. Have a default profile active (e.g. with mouse cursor).
2. Have a clean desktop, no windows.
3. Run some game with a profile (e.g. controller emulation).
4. Quit the game
5. Mouse cursor doesn't work. The game profile is still active. Need to open some window and even them alt-tab few times for HC to go back to the Default profile.

**Comment by CasperH2O** [comment]
I can confirm this bug, quitting a game will leave that profile active until a new game/process for which a profile exists is detected. Ran into this one some time ago when checking TDP. 

In short, HC does not properly detect a game exiting.

**Comment by Valkirie** [comment]
> In short, HC does not properly detect a game exiting.

Yes it does but we're not informing the layout manager.
Nor a we applying default profile on application startup.

I need to fix both

**Comment by Valkirie** [comment]
Should be fixed with: https://github.com/Valkirie/HandheldCompanion/commit/c30e3af4af1f0e5238500a58740a88124fe9ed4f

**Comment by Havner** [comment]
Can't fully really test it without #430.

**Comment by Havner** [comment]
Tested the https://github.com/Valkirie/HandheldCompanion/commit/c30e3af4af1f0e5238500a58740a88124fe9ed4f
Cannot reproduce this with a few tries so looks good, thanks!
