### ISSUE TITLE
When there is no foreground process (e.g. on app start) the Default profile should be applied

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#436]
Happens on 0.15.0.4

When the HandheldCompanion application starts and there is no window on the desktop (e.g. after the windows start) there is no active profile. In quicktools I can see: "waiting for foreground process". The Default profile is not active then. IMO it should. Otherwise I have to fallback to the Desktop profile, run some app and only then Default profile triggers.

**Comment by CasperH2O** [comment]
As discussed in #434, this is indeed a bug that requires fixing.

**Comment by Valkirie** [comment]
Should be fixed with: https://github.com/Valkirie/HandheldCompanion/commit/c30e3af4af1f0e5238500a58740a88124fe9ed4f

**Comment by Havner** [comment]
I'll test this together with #434 in the evening.

**Comment by Havner** [comment]
> Have a proposition: Desktop mode have to be auto enabled.

No. By default you have a Default profile. And it's fine as it is now IMO. You can use this as your main desktop mode. This way you don't have to turn off anything when entering a game. It switches automatically.

The whole confusion IMO comes from a fact that Desktop mode is named as such. I think some sort of Fallback/Override/Emergency mode would've been a better name for it.

**Comment by CasperH2O** [comment]
> Have a proposition: Desktop mode have to be auto enabled.

That's a decent suggestion, although that could be realized by configuring the Desktop template for the Default profile.

The current predicament of that not working is not helping the situation.

The design of "mouse mode" took some doing, as quite a few handheld users are used to having a button of sorts to toggle it on and off, where as me personally I prefer the way @Havner has set it up, if no (game) profile is loaded I want to move the mouse with my joysticks.

**Comment by Havner** [comment]
> Thanks. I'll test this together with #434 in the evening.

It's hard for me to fully test this with #430 broken.

**Comment by Havner** [comment]
> What could be useful though is to have the Default's profile layout remapper enabled by default when starting HC for the first time ever so the mouse is automatically working for a new user.

Or not. I just realized that the default profile is configured as a controller anyway. So disregard this notion :-)

**Comment by Havner** [comment]
Tested again with https://github.com/Valkirie/HandheldCompanion/commit/c30e3af4af1f0e5238500a58740a88124fe9ed4f
Seems to work properly. Thanks!

**Comment by Havner** [comment]
> Have a proposition: Desktop mode have to be auto enabled.

#457
