### ISSUE TITLE
Vibrations not wokring on most games in steam

### ISSUE THREAD

**Issue by ejnduka** [Valkirie/HandheldCompanion#438]
After updating to latest build I have found that vibration is not working in most of my games in Steam but is functioning in my emulators such as RPCS33 and PCSX2. I can have the vibration setting at 55% and it works when I start HC

**Comment by CasperH2O** [comment]
Better check your Steam configuration for the DS4, if it works everywhere else it does not seem like a HC issue.

Closing ticket.
