### ISSUE TITLE
In layout template list, all the templates (but the desktop) are listed twice

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#442]
The list looks like this:

1. All the gamepad/keyboard profiles
2. The desktop profile
3. All the gamepad/keyboard profiles again.

I've checked, I don't have duplicate files in the templates directory.

**Comment by CasperH2O** [comment]
Is this on the same device where you have Visual Studio and compile etc? I usually have this if @Valkirie makes tweaks/changes to the code of the templates and it generates new ones.

**Comment by Havner** [comment]
No, I don't have visual studio on the deck. Also I haven't seen this in 0.15.0.4.

I also closed HC, removed the template files and restarted HC. It recreated all of the files and still lists the twice.

**Comment by Valkirie** [comment]
Remove all layouts from the layout folder. We're no longer storing embedded layouts there, except Desktop.

**Comment by Havner** [comment]
> Remove all layouts from the layout folder. We're no longer storing embedded layouts there, except Desktop. We'll be using this folder for community layouts exclusively.

I have, and I could've sworn they got recreated there again. But tried again and all is fine :-)
