### ISSUE TITLE
Escape key to close QuickTools?

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#444]
When they are focused of course, not globally.

**Comment by CasperH2O** [comment]
You can use the same hotkey that you use to open QuickTools to close it again. QuickTools also has a X, like every application to close it. Is that not sufficient? 🤔

**Comment by Havner** [comment]
The hotkey to trigger quicktools should not be easily accessible as not to trigger it accidentally during gameplay. Hitting X requires mouse movement. Esc (when you have it bound somewhere and I usually do is pretty quick). Sufficient is a subjective term here. Adding Esc here has no drawbacks (I can think of) and can be useful to some (like me). So is there a reason against?

**Comment by CasperH2O** [comment]
> The hotkey to trigger quicktools should not be easily accessible as not to trigger it accidentally during gameplay.

Indeed, that's why you can use a gamepad button combination or dedicated OEM keys.

> Hitting X requires mouse movement. 
Or you can use your finger on the touch screen. 

Esc is actually an OEM key on my primary development and gameplay handheld, the Ayaneo 2021. But you can use Esc to bring up QuickTools and Close it if you want, just configure it using a keyboard.

**Comment by Havner** [comment]
> Indeed, that's why you can use a gamepad button combination or dedicated OEM keys.

I know I can. I'm not saying there is a feature lacking. I'm saying it could be improved. Like the windows' notification area. It can be closed with Esc.

> Or you can use your finger on the touch screen.

Which is still much slower and requires more hand movement than Esc,

> But you can use Esc to bring up QuickTools and Close it if you want, just configure it using a keyboard.

This would have a **serious** drawback of triggering QuickTools every time you use escape for anything else.

I don't get why are you so against it. Does it have any drawbacks? Would that hinder something?

**Comment by CasperH2O** [comment]
> I don't get why are you so against it. Does it have any drawbacks? Would that hinder something?

I'm not against it, it was not my intention to give you that impression. I'm just not for it in light of currently available alternatives. It's up to @Valkirie though.

**Comment by Havner** [comment]
Implemented with #453
