### ISSUE TITLE
Invert axis does not work correctly on joysticks in joystick mode

### ISSUE THREAD

**Issue by ShadowFlare** [Valkirie/HandheldCompanion#454]
I was trying to implement joystick rotation to play games in portrait and was getting some odd behavior, so I went back to a regular build and realized that even the existing invert axis option is broken on joystick mode.

Tested on a build compiled from commit fc9c192, with invert axis on, the joystick flips somewhere in the wrong direction at some spots, which can easily be seen when making a circle with the stick. Mouse mode doesn't seem to have this bug.

The controller I'm testing on is the GPD Win 4's built-in.

**Comment by CasperH2O** [comment]
Hey @ShadowFlare when you say invert, do you mean up down get swapped and left right get swapped or that the direction get rotated so to speak, meaning pressing left will become down (if rotating clockwise)?

**Comment by ShadowFlare** [comment]
Sorry, just realized I didn't explain it completely properly, but it's with the existing "Invert axis" option when you expand the options on a joystick in joystick mode, and the bug makes it so you can't do a proper full circle with the option enabled (no issues when disabled). With it enabled when moving the stick around in a circle, looking at it in a gamepad tester, at various points along the circle it will just suddenly jump in the wrong direction, consistently in the same parts of the circle.

It's expected that up and down get swapped and left and right get swapped (which effectively just rotates it 180 degrees), and that's what it does, except for along the problem points.

Checking it out again, I see that on the tester when it goes near the top-middle, the Y coordinate stops being inverted, and toward the right-middle, the X coordinate stops being inverted. Perhaps something is either canceling the inversion under certain conditions or something is applying it again, effectively negating it.

**Comment by ShadowFlare** [comment]
Just had a suspicion that it might be some kind of wrapping around going on, so I enabled "improve circularity" and it's working just fine. Not sure if the wraparound is coming from Handheld Companion or elsewhere, but that option works around whatever is causing it. Now that I've realized that's what it was doing, I've also tried not moving the stick full tilt to the side, and I see it only wraps around when it reaches past certain sides but not if I don't move it all the way to those sides.

**Comment by ShadowFlare** [comment]
Together with that workaround, I've tested my 90 degree rotation option, tested both standalone and together with the invert axis option to make 270 degrees, and it's working great for a portrait mode game I'd wanted to have full screen with rotated controls (but it didn't have controller remapping on its own).

**Comment by CasperH2O** [comment]
> 



> Together with that workaround, I've tested my 90 degree rotation option, tested both standalone and together with the invert axis option to make 270 degrees, and it's working great for a portrait mode game I'd wanted to have full screen with rotated controls (but it didn't have controller remapping on its own).

Sounds intriguing. Did you include it in the GUI of the remapper with an option? Do you want to make it into a formal PR? We can discuss stuff live on Discord if you'd like?

**Comment by CasperH2O** [comment]
Concerning the bug, when inverting the following:

short.MaxValue = 32767
short.MinValue = -32768

The MinValue would result in 32768, which is not possible. 

We're missing a math.clamp(value, short.MinValue, short.MaxValue) in a few spots.

**Comment by CasperH2O** [comment]
Fixed by @ShadowFlare
