### ISSUE TITLE
Rotation options for joysticks

### ISSUE THREAD

**Issue by ShadowFlare** [Valkirie/HandheldCompanion#456]
Mentioned a little in #454 because I ran into that bug in the process of trying this out, but I think it would be nice to have full capability for rotating the joystick output on controller mappings in 90 degree increments, especially 90 and 270 degree rotations for when a device is in portrait mode for games that use it (and that don't have per-direction remapping or even any remapping at all).

I've already implemented a 90 degree rotation toggle, and it can be combined with the existing invert axis toggle to get 270 degrees for the other portrait orientation. Now if it's fine just like that, I could just share what I've got, for it to be included as it is or with some modifications. Or it could possibly even have both options combined into a single rotation option with settings for 0, 90, 180, and 270 degrees.

**Comment by CasperH2O** [comment]
@ShadowFlare I guess we can close this one as your PR was merged.
