### ISSUE TITLE
GPD Win 4 "9" and "0" keyboard keys not working when app is open.

### ISSUE THREAD

**Issue by Questinghero** [Valkirie/HandheldCompanion#459]
I am running 15.0.4 Win4 build, and when I have the app open (even if I have the service stopped), the "0" and "9" keys will not work on the built in keyboard OR an external USB keyboard. This is only the row of numbers across the top of a keyboard and NOT the num pad, but it also includes the "(" and ")" keys that you press shift to access (I had to close the app to write this post). On the built in keyboard pressing "Fn" and what is now F9 and F10 works fine.

I have looked at all the settings and hot keys, and I don't think I have anything turned on that should be causing this.

**Comment by ShadowFlare** [comment]
Are you using the build that's for the GPD Win 4? That may have 9 and 0 set as "OEM" keys that you are intended to set as the back buttons. Personally, I don't think it should be this way, especially with the device having a built-in keyboard.

**Comment by CasperH2O** [comment]
@Questinghero what have you configured in the GPD app for the back buttons?

**Comment by Questinghero** [comment]
1. I am using the build made for the Win 4.
2. I am not sure where the back button is set, sorry.
3. The only Hotkey I have set is the Xbox/Menu key, and it is set to summon quick tools menu.
Does this help?

**Comment by CasperH2O** [comment]
> 1. I am using the build made for the Win 4.
> 
>     2. I am not sure where the back button is set, sorry.
> 
>     3. The only Hotkey I have set is the Xbox/Menu key, and it is set to summon quick tools menu.
>        Does this help?

To my knowledge GPD provides an application to configure/program the backbuttons, are you not using that?

**Comment by Questinghero** [comment]
Sorry, I assumed "Back Button" was something in Handheld companion. You are correct, you set them with "WinControls", and they are not currently set to anything. I do set them as F11 or Esc when I do set them.

**Comment by CasperH2O** [comment]
@Questinghero ok, thanks for explaining. Next iteration I will replace the GPD OEM keys to F11 and F12. It will be up to the end user to configure those buttons initially to that in the first place, then HC takes over from there.

**Comment by Questinghero** [comment]
Please don't use F11 and F12, those are the switch screens on Citra. Maybe use some of the keys on the NumPad, though I guess you would have to plug in a keyboard to configure them. Or you can set them to be several buttons so maybe something like "ALT+A+G+L", something you would never accidently press.

**Comment by Questinghero** [comment]
![image](https://user-images.githubusercontent.com/5230341/231506755-2e900afa-185d-4327-aa93-132b898cd26e.png)

**Comment by CasperH2O** [comment]
For both the GPD Win4 and other GPD devices I've changed the hotkey chords to F11 + L and F12 + R. Once merged they will be in the next release.

**Comment by CasperH2O** [comment]
Thank you everyone for providing feedback and insight into this device, as I don't own it myself, it's much appreciated.
