### ISSUE TITLE
Layout exporter, summary

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#464]
1. the gear icon for exporting suggests there are some options there while it immediately gives you the export window. Probably some "share" icon would be better there
2. when exporting any profile its name in the export layout window is prefixed with " - "
3. The desktop.json is still in the layout directory 😉 We talked about moving it away somewhere else not to confuse it with Community Layouts
4. When exporting you see "Layout template was | was updated". Not a big issue, but it probably would be nice to show: "$LAYOUT_NAME layout has been exported".
5. When deleting a layout file while HC is running it doesn't notice the file missing, it still shows it in the layout picker
6. The layouts listed are sometimes oddly indented
7. Open export layout window, focus name element, open on screen keyboard, hit any key on the OSK. Export layout window disappears. Which means I cannot rename a profile with OSK
8. All the text fields in Export layout window are completely ignored. Whatever you put there the filename and the name of the profile inside the file will still be based on the name/author of the original profile (with default description)?
9. Maybe profiles on the list should be sorted? Right they are either alphabetically but reversed (probably due to file order loading) or unsorted.

Images for point 6:

![image1](https://user-images.githubusercontent.com/6246347/231862667-85e3bd56-9111-4f57-a7b8-42665b0ced52.png)
![image2](https://user-images.githubusercontent.com/6246347/231862671-8118598d-ab0c-4ca0-8ad7-3671ed713979.png)

**Comment by Havner** [comment]
Ad. 7. When tried to reproduce it again it didn't. So not sure. But it did happen initially.

Ad. 2. I get where that " - " comes from. Cause it's taken from: "$PROFILE_NAME - $GAME_NAME". But when you create new profile the layout applied to it has no name. So exporting one results in " - $GAME_NAME". 
When you apply some other profile it gives it that name. But when you have a profile for a game you can't really change/set that internal name in any way so not sure it should even be there, or at least it shouldn't be really used in that way.

**Comment by Valkirie** [comment]
1. Fixed
2. Fixed
3. Fixed
4. Fixed
5. Might look into it later, hard to implement properly
6. Fixed
7. No idea how to fix
8. Fixed
9. Yes, but lazy right now

**Comment by Havner** [comment]
And if you need to store product cause that's the format you had before just store it and ignore it everywhere. Don't display it, don't use it to name the file, just like it's not there. Same with `Executable`, it's there but like it wasn't.

**Comment by Havner** [comment]
I'll retest this all later on and update the issue. After a quick look and with #471 most seem to be fixed.

**Comment by Havner** [comment]
Excluding 5 and 9 this is fixed. I guess those 2 we can treat as feature requests for the future.

Closing.
