### ISSUE TITLE
winmax2 joysticks not working since 0.15.1.0

### ISSUE THREAD

**Issue by eugenov** [Valkirie/HandheldCompanion#490]
Hello!
I use emulated PS4 controller and its sticks stoped to work. Other keys seam to be fine. Hiding won't help.
Thanks!

**Comment by ShadowFlare** [comment]
With that release a feature was added to have the desktop profile enabled by default, which has some default bindings for various things, including the sticks. Make sure you're not still in desktop mode, either by turning it off through the quick tools window or a hotkey, or by turning off the desktop mode at start in the settings.

**Comment by ShadowFlare** [comment]
I think desktop mode overriding whatever is in a profile is by design, so you can get mouse control at any time if needed. It's just that it wasn't enabled on start by default on previous versions.
