### ISSUE TITLE
HC break the AMD driver in Onexplayer2

### ISSUE THREAD

**Issue by cpak00** [Valkirie/HandheldCompanion#492]
I know that Onexplayer2 is not officially supported in HC.
But I can still use the controller function.
However, I found that the power control may break the AMD driver. The graphic driver issue immediately disappeared when I uninstalled the HC. So I believed that it is due to the graphic card clock control or the TDP control function in HC.
Thanks very much

**Comment by CasperH2O** [comment]
Hey @cpak00 thanks for reporting in.

1. What do you mean with Power Control? TDP control?
2. What is the "graphic driver issue"? What does this look like, how can I reproduce this, which version of the AMD driver?
3. HC's default settings do not adjust TDP or GPU Mhz. Does the problem start when just running HC or do you enable TDP or GPU control?

**Comment by cpak00** [comment]
> Hey @cpak00 thanks for reporting in.
> 
> 1. What do you mean with Power Control? TDP control?
> 2. What is the "graphic driver issue"? What does this look like, how can I reproduce this, which version of the AMD driver?
> 3. HC's default settings do not adjust TDP or GPU Mhz. Does the problem start when just running HC or do you enable TDP or GPU control?

Thanks for your response!
1. Sorry. What I mean is TDP control.
2. The screen freezes and then turns white. The graphic driver will be disabled after reboot.
3. After I submitted the issue, I try to install the HC again. The game works well at first. But soon (about 1 hour) there was a problem again. I will run further tests until I confirm that this is really caused by HC. The TDP and graphic card clock control of HC are available and would not break the graphic card driver.
4. I have tried the stable 22.5.1 and the recent 23.4 version. They all have this issue.

**Comment by cpak00** [comment]
The system is stable after I close the TDP & GPU clock control in HC. Thank you! But this function is really good so I will still expect it to work on my device.
Looking forward to supporting Onexplayer2 to use the OEM button.
Thanks for your hard work!
