### ISSUE TITLE
Auto Shut Down when used  Desktop Layout on steam deck.

### ISSUE THREAD

**Issue by LordHunterz** [Valkirie/HandheldCompanion#498]
HC always Shut Down every time i open apps/games that need admin permissions when desktop layout/controller is on. . I need to turn off desktop layout/controller first everytime i want to open apps/games that need admin permissions. Idk if this issue only happened to me.

**Comment by LordHunterz** [comment]
[HandheldCompanion20230421.log](https://github.com/Valkirie/HandheldCompanion/files/11288258/HandheldCompanion20230421.log)

**Comment by Valkirie** [comment]
Oh yeah OK. @Havner has pushed a fix for this issue in the forthcoming release.

**Comment by CasperH2O** [comment]
@LordHunterz can you check if you are still experiencing this issue with 0.16.0.5?

**Comment by LordHunterz** [comment]
Already tested. . No more problem after updated to new version. . Thanks to all dev. . I've been waiting for this problem solved for long time. . 😄
