### ISSUE TITLE
Issues with Fifa 23

### ISSUE THREAD

**Issue by acidfrehley** [Valkirie/HandheldCompanion#509]
So I just got a Steam Deck and the main purpose was to play Fifa 23 on it (yeah, I know). Already installed Windows 10 and had a few matches on Fifa before trying the handheld companion. 

As soon as I tried to launch the game after running it, it just pops up a black screen and nothing happens. Whenever I shut the companion off, the game start running normally again. Don't know what could be causing it. It only happens with Fifa aswell.

**Comment by Valkirie** [comment]
Hard to tell what's going on. May I invite you to create a profile within HC and point it to Fifa23 executable, then turn on the Extended compatibility, click Update profile and try to start the game again?

I should hide the "virtual" nature of the controller.

**Comment by CasperH2O** [comment]
No reply after 2 weeks. Possible solution provided. Closing ticket.
