### ISSUE TITLE
Weird rumble implementation in Steam Deck

### ISSUE THREAD

**Issue by DiegcD** [Valkirie/HandheldCompanion#514]
Hello, I just installed this app on it's newest version on a Steam Deck and I'm trying it with different games.

At the moment in Marvel's Spider-Man remastered the game has rumble settings in a slider from 0 to 10 and there is no rumble at all in slider options 0, 1 and 2.
Also when pressing A in air to get a boost in speed the rumble sounds and feels too harsh compared to other rumble actions in-game.
Another one in Spider-Man: when you charge the jump with RT+A the controller is supposed to softly vibrate until the jump is fully charged, but even with the vibration on 10 it doesn't happen.

Is that natural from the game or is the HC rumble implementation not that polished?

In Forza Horizon 5 the rumble feedback is non existent except when you crash against certain objects like road signs and barriers. But the game has rumble feedback according to your tire grip and also when crashing against vehicles but with HC it doesn't work correctly.

Is something I can do to fix this? Every vibration works normally on Steam Deck Tools but Handheld Companion has stuff SDT hasn't.

**Comment by Valkirie** [comment]
Hey, we came to the same conclusion and I'll definitely be looking into this before next public release.

**Comment by Havner** [comment]
Actually the current implementation based on SetHaptic2() (taken from SDT) + #533 gives really nice results. I'd like someone else to speak on that matter but I'm pretty content with the feel. It's stronger than steam inputs but quiet and not erratic/crazy like the previous one.

**Comment by Valkirie** [comment]
Should be addressed in forthcoming release (with Patreons right now).

**Comment by CasperH2O** [comment]
Closing, has been improved (a long time ago).
