### ISSUE TITLE
Layout not changing when application is running (Keeps using Default layout)

### ISSUE THREAD

**Issue by TheDoomCider** [Valkirie/HandheldCompanion#515]
I've been having issues on and off on my steam deck with the controller layout not changing when an application is running. It tends to stick to the default configuration for some reason. This is fine for xbox games. However, I'm trying to map my steam deck controls to keyboard inputs to play an old unity web game via uniplayer 1.34. I didn't seem any issues like this so I apologize in advance if this is a duplicate. I attached screenshots of my settings and exported my uniplayer layout. 
Note: I'm launching all of my games using Playnite not steam.

![uniplayer profile](https://user-images.githubusercontent.com/24508166/235303725-6a66cae2-65c1-47fc-b920-fa8707f7e05f.PNG)
![global](https://user-images.githubusercontent.com/24508166/235303722-f9238206-71de-42a7-aa9d-261974cf8e74.PNG)
![layout](https://user-images.githubusercontent.com/24508166/235303724-9690003a-56d9-4b3d-b39e-5ca26ebe35a4.PNG)
![controller](https://user-images.githubusercontent.com/24508166/235303721-c42537e1-3ddd-41ff-a5a8-837e0eaf81d3.PNG)

[Gamepad (XBOX) - UniPlayer 1.34_Deck.zip](https://github.com/Valkirie/HandheldCompanion/files/11359223/Gamepad.XBOX.-.UniPlayer.1.34_Deck.zip)

**Comment by Havner** [comment]
Are you sure you mean the Default profile and not the Desktop layout? The latter doesn't change automatically. It's a global override over everything else.

**Comment by TheDoomCider** [comment]
Thanks, it was the desktop profile. Did not know it didn't change automatically. I disabled it and everything is working as expected now!

    On Saturday, April 29, 2023 at 07:17:42 p.m. ADT, Havner ***@***.***> wrote:  
 
 


Are you sure you mean the Default profile and not the Desktop layout? The latter doesn't change automatically. It's a global override over everything else.
