### ISSUE TITLE
Gyro triggering might not work in rare cases

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#517]
The gyro triggering is done on the service level and with recent changes around this code the controller state is not fully passed to the service.

E.g. if the button A is not mapped as output anywhere and A is used as gyro trigger it won't work.

The 0298a46 is a workaround for this regarding virtual buttons, but it needs to be properly implemented on the HC level anyway.

Check for the button state in physical controller for a combo that enables gyro on the HC level and just send *bool* info to the service when gyro should be enabled.

**Comment by Havner** [comment]
I guess it's fixed by 03f0863? I have no means to test it as I have issues with gyro.

@Valkirie you want to close it?

**Comment by Havner** [comment]
@Valkirie ?

**Comment by Valkirie** [comment]
It works fine now.
