### ISSUE TITLE
Print button not in the controller setting

### ISSUE THREAD

**Issue by Taboulet** [Valkirie/HandheldCompanion#526]
we can't set a button to press the "print" button

**Comment by CasperH2O** [comment]
@Taboulet do you mean you are trying to make a custom hotkey that presses the PrtScr button? Or do you mean the PrtScr button is not part of the layout remapper?

**Comment by Taboulet** [comment]
The second one

**Comment by Taboulet** [comment]
Sorry i didn't mean to close it

**Comment by Valkirie** [comment]
I'd rather make it a hotkey than an input for layout mapping.

**Comment by Valkirie** [comment]
https://github.com/Valkirie/HandheldCompanion/pull/569
