### ISSUE TITLE
Handheld Companion causing The Division 2 (Ubisoft Connect) to hardcrash minutes into playing.

### ISSUE THREAD

**Issue by Br7an547** [Valkirie/HandheldCompanion#528]
The game boots and it gets to the open world but it crashes a few minutes into playing, causing the Deck to hardcrash. 

I have tried cloaking and not cloaking the Deck to no avail. I thought it was my graphics settings but trying custom, medium, and low does nothing. The only method that works for xinput is the notepad method.

When it does work, it works well however there is no rumble in-game.

**Comment by Br7an547** [comment]
> 

By hardcrash I mean it completely crashes the Deck. No blue screen of death it just shuts down the deck and I have to manually boot into Windows. Running on Windows 10.
[HandheldCompanion20230512.log](https://github.com/Valkirie/HandheldCompanion/files/11468318/HandheldCompanion20230512.log)
[ControllerService20230512.log](https://github.com/Valkirie/HandheldCompanion/files/11468319/ControllerService20230512.log)

**Comment by CasperH2O** [comment]
No response from issue creator, don't have this game to reproduce. Closing, regrettably.
