### ISSUE TITLE
Battery charge % limiter (see also G-Helper)

### ISSUE THREAD

**Issue by hifihedgehog** [Valkirie/HandheldCompanion#539]
The ASUS ROG Ally was recently launched and it is confirmed to support and use Armoury Crate for managing its setting. I am so excited about this because this opens the door for adding some great features to Handheld Companion specific to the Ally. How? [Enter G-Helper. G-Helper is a lightweight and bloatware-free open-source alternative to Armoury Crate here on GitHub.](https://github.com/seerge/g-helper) So it is very feasible that sooner or later in your roadmap, you could potentially integrate upstream code from G-Helper. One significant feature that I especially hope for is the battery charge limit that offers finer, single-digit percentage control down to 40%. Listed below are its features. Note that some of its features are irrelevant to the Ally and apply to other ASUS laptops. However, battery charge limiter, refresh rate toggle, and RGB adjustments are most definitely fair game and wholly applicable:

> Performance modes: Silent - Balanced - Turbo (built-in, with default fan curves)
> GPU modes: Eco - Standard - Ultimate - Optimized
> Laptop screen refresh rate 60hz or 120hz (144hz, etc) with display overdrive (OD) and miniled multizone switch
> Custom fan curve editor, power limits (PPT) and turbo boost selection for every performance mode
> Anime matrix control thanks to [Starlight](https://github.com/vddCore/Starlight) + some tweaks from my side including animated GIFs
> Keyboard backlit animation and colors (including sleep animation and support for TUF models)
> Custom bindings for M3, M4 keys and FN+F5 (performance mode) FN+F4 (keyboard animation modes)
> Monitor CPU / GPU temperature, fan speeds and battery discharge rate
> Battery charge limit to preserve battery health
> NVidia GPU overclocking
> ⚙️ Automatic switching when on battery or plugged in
> 
> Performance modes (app remembers last mode used on battery or when plugged)
> Optimized GPU mode - disables dGPU on battery and enables when plugged
> Auto Screen refresh rate (60hz on battery, 120+ hz when plugged)
> Keyboard backlight can be turned off on battery
> To keep auto switching and hotkeys working the app needs to stay running in the tray. It doesn't consume any resources.

**Comment by hifihedgehog** [comment]
For starters, the battery limiter is implemented using https://github.com/seerge/g-helper/blob/0b7dd42a5d0467e1c5ad4eb927fea8641eca51f1/app/Settings.cs#L1686, https://github.com/seerge/g-helper/blob/0b7dd42a5d0467e1c5ad4eb927fea8641eca51f1/app/Program.cs#L13, https://github.com/seerge/g-helper/blob/0b7dd42a5d0467e1c5ad4eb927fea8641eca51f1/app/OptimizationService.cs#L8, and https://github.com/seerge/g-helper/blob/0b7dd42a5d0467e1c5ad4eb927fea8641eca51f1/app/ASUSWmi.cs#L34, and possibly others. The upside too is G-Helper also is written in C#, so that should simplify the integration process immensely. :) I'll try to dive into the other features later on.

**Comment by hifihedgehog** [comment]
I just submitted a feature request to G-Helper to expand the ASUS RGB lighting control in G-Helper to support Ally's two joystick RGB rings. Keep a close eye on this since the updated methods there in G-Helper should allow adding RGB settings for the Ally in Handheld Companion!

https://github.com/seerge/g-helper/issues/372

**Comment by CasperH2O** [comment]
As discussed on Discord. A battery charge limiter can have a positive impact on battery health long term. 

A use case to watch out for though is when this limit is active and the user wants to take his handheld on a trip, there will be less battery life available unless the user is mindful to let it charge to full before the trip.

**Comment by CasperH2O** [comment]
Legion Go charge limit is being added through #1074

**Comment by CasperH2O** [comment]
ROG Ally battery charge limit has been added in the EA branch for next release. 

Thank you @moyogii
