### ISSUE TITLE
Increase the number of Hotkeys assigned to Quick Menu

### ISSUE THREAD

**Issue by rodrigoqueiroz** [Valkirie/HandheldCompanion#565]
Currently, you can only pin 9 hotkeys to Quick Menu.
Would be great to assign more.

**Comment by CasperH2O** [comment]
Hey @rodrigoqueiroz you can adjust the amount here and do a PR if you want? 

https://github.com/Valkirie/HandheldCompanion/blob/7f9994bf330c6b679c36088f3ffeafc474e8439c/HandheldCompanion/Managers/HotkeysManager.cs#L42

How many pins do you want?

**Comment by CasperH2O** [comment]
Increased to 18. Will be included in next release.
