### ISSUE TITLE
Interacting with virtual trackpads causes opacity to continuously increase 

### ISSUE THREAD

**Issue by Serhiy1** [Valkirie/HandheldCompanion#566]
Hardware: Aya Neo Air 
Handheld companion version: 0.15.1.1

Repro steps: 
1. Bring up virtual trackpads
2. Start swiping on them in a rapid fashion 

screenshot: 
<img width="942" alt="Screenshot 2023-05-20 101710" src="https://github.com/Valkirie/HandheldCompanion/assets/28574129/7638549d-3c48-4122-a309-0b7705934d1e">

**Comment by CasperH2O** [comment]
Very interesting! I'll have a look shortly to see if I can reproduce this.

**Comment by CasperH2O** [comment]
@Serhiy1 can confirm this is reproducible with 0.16.0.3 also. Just keep tapping and or sliding over the virtual trackpad to see it grow darker.

**Comment by CasperH2O** [comment]
As discussed on discord, increasing and decreasing opacity is done relatively -/+ 0.1 based on touch / no touch. It would be better to increase relatively and reset to an absolute value.
