### ISSUE TITLE
Microsoft flight sim 2023

### ISSUE THREAD

**Issue by Fireflyrob** [Valkirie/HandheldCompanion#572]
I have Microsoft flight sim running on Xbox and my steam deck (through Windows 11). It runs very well on steam deck other than one issue. On my Xbox, if I push the joystick forward the plane will pitch towards the ground (and vice-versa). However, using handheld companion joystick emulator, the same input just zooms in and out of the plane! I have tried many different ways of changing this but with no success…any advice please

**Comment by Valkirie** [comment]
Looks like you have desktop mode enabled.
- You might want to disable auto desktop mode on startup from settings.
- You might want to disable desktop mode from quicktools or using a hotkey.

**Comment by Fireflyrob** [comment]
Already did that… no luck!

**Comment by Fireflyrob** [comment]
I use hotkeys to disable desktop mode before I run MSFS

**Comment by Valkirie** [comment]
Can you head to : https://gamepad-tester.com/ and check if virtual controller is behaving fine and physical controller is properly hidden ?

**Comment by Fireflyrob** [comment]
Ok I’ll give that a go. Part of the problem I think is MSFS itself as there are so many terms in respect of inputs. There is drone, external and internal cameras and so much more so actually finding the correct (or incorrect) input and changing it is confusing! It’s my fault as I am new to SteamDeck/MSFS/HandheldCompanion!
but thank you for helping☺️

**Comment by Fireflyrob** [comment]
Thank you. MSFS exe file is hidden so using a profile is difficult

**Comment by Valkirie** [comment]
Use quicktools to create the profile.

**Comment by Fireflyrob** [comment]
It is greyed out!

**Comment by CasperH2O** [comment]
@Fireflyrob as a workaround you could adjust the default profile. Upcoming release 0.16 will feature some improved process detection, hopefully that will help.

**Comment by Fireflyrob** [comment]
Tried many times. Cannot get the left hand joystick to perform as it does on the Xbox version. On that version it pitches forward and vice versa…on steam deck it zooms in and out

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CasperH2O** [comment]
@Fireflyrob as a test, could you try if you still have this problem with release 0.16.0.5? We have improved the application detection and most likely if that works well, you should be able to make a layout for this game in any way you'd want.

**Comment by Fireflyrob** [comment]
I solved. I deleted my config on Xbox and all works fine now…must have been a problem with the sync. Many thanks ☺️

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CasperH2O** [comment]
Excellent, happy gaming!
