### ISSUE TITLE
HWinfo started with HC has multiple pop ups

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#579]
HWInfo, when started with HC has multiple pop ups:
1. How the user wishes to start the app, I have sensors only ticked and then I hit start
2. A new beta update was made available today, so it pops up this, there are two check boxes to tick, one for beta channel and one for checking for updates, default both are off.

Perhaps update/adjust HWInfo's settings file during HC installation or through HC itself?

**Comment by Valkirie** [comment]
We're doing it already. Try and configure HWiNFO outside HC so that it behaves fine and share your HWiNFO.ini file.

**Comment by CasperH2O** [comment]
Ok, the first pop up is this setting, show welcome screen and progress:

![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/a0be5a74-5300-400a-bdec-e9ecaf467cd0)

The second are these two:

![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/ae187d07-c55c-49c5-a7ea-6ef167ac5d47)

Best I can tell form the INI file it's these:
`ShowWelcomeAndProgress=0`
`AutoUpdateBetaDisable=1`

The check for updates toggle always reverts back on my installation, but I have a somewhat out dated version.
