### ISSUE TITLE
inpoutx64.sys error with RIOT VANGUARD on latest updates

### ISSUE THREAD

**Issue by kuniimitsu** [Valkirie/HandheldCompanion#595]
Hi all, I have a pretty niche issue.

So basically, I'm using this program to emulate my Steam Deck controller as a PS4 controller and then use the emulated PS4 controller with reWASD to use it on Valorant.

The latest program I've been using where it still works is 0.14.2.0

However, I've tried updating the program as I haven't used it in a while and now Riot Vanguard is showing that it's disabling inpoutx64.sys, I've isolated the program to be Handheld Companion. whenever that happens the DS4 emulation doesn't work as intended and I'm unable to use it on reWASD.

Would I be able to do anything? I'd like to get it updated as I read on the changelogs that the trackpads are now better (which is what I'm using for Valorant)

Thank you!

**Comment by CasperH2O** [comment]
@kuniimitsu what are you additionally doing with reWASD?

**Comment by kuniimitsu** [comment]
> @kuniimitsu what are you additionally doing with reWASD?

Essentially the same thing, I use the “emulated ds4 touchpad” to emulate mouse movements using reWASD so I can use Steam Deck’s trackpads to aim and the buttons to move shoot etc.

One thing I’ve noticed on the old version is that even if inpoutx64.sys gets blocked the DS4 emulation still works and I can still use it in game.

On the latest versions however I think Handheld Companion stays stuck in the Desktop mode of controls when inpoutx64.sys gets disabled and doesn’t emulate DS4 controls as intended.

**Comment by CasperH2O** [comment]
@kuniimitsu have you tried disabling Desktop mode, either through QuickTools or the main GUI?

![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/19e148d2-7521-4c00-888c-02a7167ac9a3)

**Comment by kuniimitsu** [comment]
> @kuniimitsu have you tried disabling Desktop mode, either through QuickTools or the main GUI?
> 
> ![image](https://user-images.githubusercontent.com/14330834/241576982-19e148d2-7521-4c00-888c-02a7167ac9a3.png)

Looks like that worked, thank you! However I still keep getting the inpoutx64 error, would that be still related with Handheld Companion? as I only get the error when I install the new versions of it

**Comment by CasperH2O** [comment]
@kuniimitsu the inpoutx64 is a part of HC for various SteamDeck related usage. As such it can't be worked around.
