### ISSUE TITLE
Improve AutoTDP increasing TDP with minimal or no improvement in FPS

### ISSUE THREAD

**Issue by nixtar** [Valkirie/HandheldCompanion#602]
Hi,

The new Auto TDP functionality is very neat!

However I find myself turning back to the various bat based solutions in cases where I'd like to limit the tdp ceiling.

Such cases are games that are not really capable of 60fps even at max tdp in certain scenarios.

Example is the new GTA 3, VC, SA remasters, they run at 60fps 95% of the time on my Win4 with an 18 tdp limit, however in the times the game dips down to the 50s even a tdp of 30 wont help.

With HCs current implementation this causes the tdp to raise up unnecessarily.

It would be awesome if a Max tdp could be specified with the auto tdp.

**Comment by CasperH2O** [comment]
AutoTDP follows the same TDP range constrains as the manual range. The manual range can be adjusted at the bottom of the main GUI settings page. It's obviously not ideal, as that will also constrain your manual range.

Thank you for the feedback.

**Comment by CasperH2O** [comment]
@nixtar the TDP range controls are not in the QuickTools section. Indeed, when activating AutoTDP, manual TDP get's disabled and vice versa.

**Comment by nixtar** [comment]
Had some shower thoughts about this.

I wonder we have a target fps with a buffer/acceptable fps target where it will only increase with very small increments when its in the "acceptable" range.

Eg
Target FPS: 60
Acceptable FPS: 50

Playing a badly optimized open world game like the Gta remasters, enter a built up area and the game slows down a bit while things buffer, auto Tdp starts slowly reacting as the game remained within acceptable range. However the game has now finished loading or you've moved past the "slow area".

**Comment by CasperH2O** [comment]
I strongly dislike the idea of making a buffer area where we make AutoTDP do it's job "worse" or more cautious. It's already challenging enough to keep FPS within an acceptable margin of say -/+5 FPS during dynamic situations.

I'm more inclined to further investigate the following two situations and determine if we can make a way that it automatically copes with them:
1. TDP max reached, FPS target not met, try to reduce TDP to see if it can be a little bit lower but still be around the average that it stalled at.
2. TDP increase has very minimal increases in FPS

**Comment by CasperH2O** [comment]
@nixtar if you could help me out, I'd like to collect the TDP to FPS ratio of the game you mention. Could you note down the FPS at the various manually set TDP values? Then I can make a graph like this.

![afbeelding](https://github.com/Valkirie/HandheldCompanion/assets/14330834/7fe2426f-5752-4e71-b82a-8c0d5612add2)

**Comment by nixtar** [comment]
Will do, might not get a chance until Sunday however.

**Comment by CasperH2O** [comment]
Idea to cope with scenario 1, graph above used for TDP/FPS relation.

User sets target FPS to 60, auto TDP maxes out TDP at 25, actual FPS stalls at 54.

Controller, after detecting the stall for 5 seconds, adjusts target FPS behind the scene with -5 to 55, TDP remains maxed out, stalled at 54. Remembers the stalled average FPS value of the last 3 loops (1 sec interval) of 54.

This repeats as 55 is is also not achievable...

Controller, after detecting the stall for 5 seconds, adjusts target FPS behind the scene with -5, to 50, TDP goes down to ~18 Watt. Remembers the stalled average FPS value of the last 3 loops (1 sec interval) of 54.

Controller monitors actual FPS, once it goes above stalled average ie >54 indicating the scene has become easier to handle, the FPS target is reset to user requested FPS.

The -5 is chosen arbitrarily, could use some thinking.

**Comment by nixtar** [comment]
That sounds like a interesting idea, getting the timings right might be tricky and I'm not sure there will be a one size fits all method.

PS
I'm still planning on capturing some TDP/FPS stats for you. Work is killing me atm and I can't find any motivation to even play games recently.

**Comment by CasperH2O** [comment]
I've decided to make it possible to combine the max TDP limit we already have in the GUI with the AutoTDP. It's nothing automatic fancy, but should get the job done and adds no new UI clutter.

**Comment by CasperH2O** [comment]
Implemented the possibility to limit the max TDP range per profile by utilizing the manual TDP slider. Closing ticket.
