### ISSUE TITLE
GPD Win 4 - Unresponsive Volume Buttons

### ISSUE THREAD

**Issue by nixtar** [Valkirie/HandheldCompanion#605]
Hello,

Occasionally I'm running into an issue where the physical volume buttons on the Win4 stop working while HC is running.

I'm using HC just for its TDP/AutoTDP capability and have disabled the controller aspects as much as I make out. (I have the controller in HC disconnected and leave the physical controller connected.)

However even with this the the volume buttons randomly stop working. I can't narrow down the exact reproduction steps. However, when it does happen, stopping HC always brings them back to life.

For my use case a setting that fully disables all the hid related things would be nice to have. However that would just be a workaround for the actual issues. (this is assuming that the hid related features are where the issue lies)

Let me know if there is any additional details or anything you would like me to try.

**Comment by CasperH2O** [comment]
This is strange indeed. To our knowledge there currently is a bug when it comes to volume control and HC, it's only possible to adjust volume by 1 or 2 when clicking. Holding a volume button has no further effect. This is a bug with the hotkeys that adjust volume.

**Comment by CasperH2O** [comment]
@nixtar the latest release of HC has removed the volume hotkeys, which caused some conflicts. Could you check and confirm they now work properly again on your device?

**Comment by CasperH2O** [comment]
@nixtar could you check if you still have this issue? Otherwise we can close this as I'm pretty sure it was fixed with the change mentioned.

**Comment by nixtar** [comment]
Sorry for being MIA, I've had some time to test the latest HC release and it appears to no longer be an issue.

If end up reproducing it again I'll post back with the details.

Thanks again for your efforts on this app. 👍
