### ISSUE TITLE
Volume adjustment hold button to increase/decrease does not work

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#613]
Observed by several users, easy to reproduce. Using the volume buttons without HC running, a user can hold the buttons to keep on incresing or decreasing the volume. With HC open, it only adjusts the volume by 2% and the user has to click repeatedly.

**Comment by TAGE7** [comment]
can confirm this issue with [Build 0.16.0.5](https://github.com/Valkirie/HandheldCompanion/releases/tag/0.16.0.5)
on the Aya Neo 2

**Comment by CasperH2O** [comment]
Fixed.
