### ISSUE TITLE
Roblox crashes with Handheld Companion

### ISSUE THREAD

**Issue by docdoggo** [Valkirie/HandheldCompanion#617]
Hey I'm here with Windows 11 on Steam Deck, Handheld Companion works great!
but it seems that Roblox's new Anti-Cheat hates it
After about a minute of gameplay Roblox will crash with an unexpected error
and this is only with Handheld Companion open.

**Comment by CasperH2O** [comment]
@docdoggo do you have extended compatibility ticked with a profile for Roblox, are you using HC's fan control?

**Comment by docdoggo** [comment]
Extended Compatibility (XInputPlus) is turned off
No I don't think I'm using HC's fan control

**Comment by docdoggo** [comment]
@CasperH2O How do I disable the fan stuff in HC?

**Comment by CasperH2O** [comment]
@docdoggo it's off by default. You can enable it through QuickTools, the tab with the battery icon. It's a toggle and a slider.

Two other things you could try, maybe the game does not like virtual controllers. You can disconnect the virtual controller and unhide the physical one. Or, in this games profile, allow this game access to the physical controller.

**Comment by docdoggo** [comment]
doesn't work
