### ISSUE TITLE
Issues bugs tdp all

### ISSUE THREAD

**Issue by unknownv080** [Valkirie/HandheldCompanion#624]
when i enable tdp or auto tdp than windows keeps bluescreening or random shutdowns without users command hope u guys can fix the issue that we can able to use tdp again

**Comment by CasperH2O** [comment]
@unknownv080 sorry to hear about your troubles, can you tell me which version you are using?

**Comment by unknownv080** [comment]
> @unknownv080 sorry to hear about your troubles, can you tell me which version you are using?

im using the latest version 16.0.5

**Comment by CasperH2O** [comment]
@unknownv080 thanks for confirming. We have a ticket here that discusses the same problem: #603 . We've made some improvements for the next release. In the mean time I recommend you don't use AutoTDP.
