### ISSUE TITLE
PS remote play without Chiaki

### ISSUE THREAD

**Issue by mmdanvar** [Valkirie/HandheldCompanion#628]
Hi, i tried using Handheld Companion on my ROG ally to use PS remote but i cant get it to work. If anyone is able to fix this for me im willing to pay. No chiaki. Thanks

**Comment by CasperH2O** [comment]
@mmdanvar to our knowledge the only option we found to be working is with a certain for of Chiaki. 

https://www.youtube.com/watch?v=HkX_AJZwGdk&t=4s

What you could try, if you don't want to use Chiaki, if you have access to it is reWASD. They have an option for a workaround for PS Remote Play to support virtual controllers. But I don't have that software so I don't know if it works together with HC.

https://forum.rewasd.com/forum/rewasd/announcements-aa/236045-ps-remote-play-connection-is-fixed-on-rewasd-6-5-1

**Comment by 618116** [comment]
PS Remote Play before 5.5 version will work with HC virtual dualshock.

**Comment by Valkirie** [comment]
> PS Remote Play before 5.5 version will work with HC virtual dualshock.

Do you have a "proper" link you could share ? I guess this whole discussion around PS Remote is worth it's own Wiki page @CasperH2O

**Comment by CasperH2O** [comment]
Information is compiled here: https://github.com/Valkirie/HandheldCompanion/wiki/PlayStation-Remote-Play

Closing, as there is no (easy) HC solution for this.
