### ISSUE TITLE
Auto TDP greyed out

### ISSUE THREAD

**Issue by ROLHISHIOUS** [Valkirie/HandheldCompanion#635]
Hi,

In my rog ally i got auto tdp greyed out.
How do i fix it? I already disable armour crate to not conflit with it but still happens

**Comment by trippyone** [comment]
Ally Rog is officially supported with v0.16.2.1. This version is available for Early access patreon members.

**Comment by CasperH2O** [comment]
@ROLHISHIOUS most likely you are using the current public build 0.16.0.5 which does not have support for the APU in the ROG Ally. 

We will be releasing the update to the public upcoming Sunday (if all goes well). Closing ticket.
