### ISSUE TITLE
Automatic TDP Greyed Out

### ISSUE THREAD

**Issue by aharper14** [Valkirie/HandheldCompanion#643]
As the title says. Not sure what's going on. I couldn't find anyone having a similar issue anywhere. TDP limit is also greyed out. I'm on an ROG Ally. Screenshot attached.
<img width="960" alt="help" src="https://github.com/Valkirie/HandheldCompanion/assets/88669313/4d9bed8e-d2a6-47e7-8378-af4be4cb5808">

**Comment by CasperH2O** [comment]
@aharper14 the ROG Ally support, including TDP came in release 0.16.1 and newer. Currently in Early Access, we're aiming for a public release this Sunday.
