### ISSUE TITLE
Custom Resolution added to Profile

### ISSUE THREAD

**Issue by EmperorKalEl** [Valkirie/HandheldCompanion#653]
No way to select a custom resolution to a specific profile

**Comment by CasperH2O** [comment]
Hello @EmperorKalEl , not having a custom resolution per game is as intended. Because profiles apply automatically, this would quickly cause your machine to switch resolutions very often. If you want a specific resolution for a game, recommend you use (if available) the games internal settings.

**Comment by EmperorKalEl** [comment]
I am on a steam deck and after every boot I have to go into HC and change
resolution in order to remove black bars on both left and right side. If I
could set a custom resolution in profiles it would automatically adjust
after boot.

**Comment by EmperorKalEl** [comment]
Yes that is correct the 800p is probably native to non docked gaming, I
game in docked mode so when I start my steam deck on every boot it starts
on that 800p with the two black side bars. I have to open HC and adjust the
resolution to 1080p manually. Once I do that black bars are gone and the
onscreen image looks so much better but the issue is that I have to
manually adjust on every boot. If HC had an option to adjust and save a
custom resolution in HC I would boot to that specific profile.

**Comment by CasperH2O** [comment]
@EmperorKalEl thanks for explaining in more detail. This is really strange, with a regular Windows machine and my experience with other handhelds (ROG Ally, GPD and Ayaneo) is that if you connect an external screen prior to boot, Windows will just scale accordingly.

Perhaps its a Windows setting or a Windows on SteamDeck specific issue? Might be worth while to ask on the SteamDeck Windows Discord also.

**Comment by EmperorKalEl** [comment]
Hi

It's probably a Windows thing because people running steam os don't have
this issue but I haven't found any information on this anywhere.

Before HC I was playing 1280x 800 resolution after installing HC I was able
to scale 1080p, no other options in windows or the TV helped. HC is an
amazing tool, I will keep looking for a permanent solution but do you think
the option for resolution in profiles could ever be implemented?

Thank you for looking into this
