### ISSUE TITLE
Rog Ally, TDP stays stuck at 15w when enabling and disabling autotdp

### ISSUE THREAD

**Issue by azodev** [Valkirie/HandheldCompanion#664]
Hello, 
With all profiles (default one also) at autotdp and tpd overide set at off, I can't swith to 25w or 30w till HC is running , if I enable on time autotdp or tpd overide on the current game or default profile, disabling it return tdp control to command control or armoury crate.

to be more precise, if I switch to 30w, it goes to 30w for 2 sec, then return to 15w ( despite the fact command control showing 30w).

I'll try to make to make a video tomorrow , it's not difficult to reproduce since it's happening all time to me ;) .

Last Patreon version 1.6.2.2

**Comment by CasperH2O** [comment]
Hey @azodev thanks for dropping in and asking questions.

Can you confirm I understand you correctly?
1. You have both HC and AC running at the same time
2. Using HCs manual TDP control, set to 30 Watts, will only have it apply for 2 seconds, then it drops to 15 W
3. Using HCs Auto TDP, the TDP goes to 15 Watt and stays there

**Comment by azodev** [comment]
Not exactly,
1: Yes at least I have AC services running, the window is closed, but
command control (bottom left button) is always on. Also Gamebuzz.exe (asus
overlay) is messing with profile, can we blacklist this exe from HC
quicktool?
2: no, after I use AutoTDP or tdp override in HC, in default profile or a
game profile, I switch it off, it falls back to 15 w , and AC tdp control
is not working properly, I set to 30w in AC , the overlay show 30w  for 2
sec and fallback to 15w (with the according fps count), despite the fact
that AC is still set to 30w. In HC everytdp controls are set to off.
3: autotdp is ok, the issue is that switching autotdp off doesn't give
control back to AC, if HC is still running.

**Comment by CasperH2O** [comment]
> Also Gamebuzz.exe (asus overlay) is messing with profile, can we blacklist this exe from HC quicktool

Yes, thanks for mentioning that. It's Gamebuzz.exe with 2 Zs?

2. That makes sense, when you disable it in HC, it will default back to a manufacturer default we have listed in HC, but... it should stop setting it after it does it once.

3. Ah ok, similar to 2, switching it off defaults it to 15 (that's correct), but then keeps enforcing it still (that's incorrect).

I'll double check.

**Comment by azodev** [comment]
Yes Gamebuzz.exe
C:\Program Files\ASUS\ARMOURY CRATE SE Service\GameBuzz\Gamebuzz.exe

**Comment by brutaljelly** [comment]
facing the same problem, i have to restart the ally to solve this issue. when it works it works great though

**Comment by philipjholm** [comment]
Mine get stuck as well randomly but it seems to happen when I unplug/plug the device (so that the power profile change) or edit/change power profile manually. It also stops working other times but havent really undestood why yet.

**Comment by brutaljelly** [comment]
> Mine get stuck as well randomly but it seems to happen when I unplug/plug the device (so that the power profile change) or edit/change power profile manually. It also stops working other times but havent really undestood why yet.

for now i have uninstalled it, i will install it again after couple of HC upgrades, in time this will get better No doubt

**Comment by CasperH2O** [comment]
This has been improved/fixed with https://github.com/Valkirie/HandheldCompanion/commit/6b44cd4a88a0ae38dd350e2ab39c03dfb64c519a

**Comment by brutaljelly** [comment]
> This has been improved/fixed with [6b44cd4](https://github.com/Valkirie/HandheldCompanion/commit/6b44cd4a88a0ae38dd350e2ab39c03dfb64c519a)

okay, maybe im doing something wrong

also please note that game loading time has been drastically increased, when i clikc on continue, now it takes 2x or 3x time

**Comment by CasperH2O** [comment]
@brutaljelly I doubt you're doing anything wrong. The fix has not made it's way into a build yet, unless you built from source?

It's possible you are experiencing longer load times, if you were previously gaming at 30 W and now at 15 W.

**Comment by brutaljelly** [comment]
@CasperH2O no, i was just using the latest version

also is it possible for you to implement manual fan curve into HC? that would be awesome

**Comment by CasperH2O** [comment]
Fixed in 0.15.2.5 (finally!).
