### ISSUE TITLE
Translation into other languages

### ISSUE THREAD

**Issue by Crover81** [Valkirie/HandheldCompanion#668]
Can I help translate this project into other languages? I would like to be able to use this program in Italian and of course I would like to help to do so

Thanks

**Comment by Valkirie** [comment]
Absolutely! While there are still a few hardcoded English label within the code you could return us those three files translated:

1. https://github.com/Valkirie/HandheldCompanion/blob/main/ControllerCommon/Properties/Resources.resx
2. https://github.com/Valkirie/HandheldCompanion/blob/main/ControllerService/Properties/Resources.resx
3. https://github.com/Valkirie/HandheldCompanion/blob/main/HandheldCompanion/Properties/Resources.resx

**Comment by CasperH2O** [comment]
@Crover81 I plan to do a large localization update (converting hardcoded English to variables), if you'd still like to help out with the translation best to wait until after upcoming Friday.

**Comment by danmaxis** [comment]
Hey there Casper. I just finished Brazilian Portuguese for these files after your latest localization commit.
Would you kindly add them properly to the project?

Controller Common: https://pastebin.com/Qd95jbrB

Controller Service: https://pastebin.com/K8XCw0ed

Handheld Companion: https://pastebin.com/HuzkdEEW

Thanks 😁

**Comment by CasperH2O** [comment]
@danmaxis on it.

**Comment by CasperH2O** [comment]
@danmaxis your files were added, it was very straightforward, thank you!

**Comment by CasperH2O** [comment]
@MiguelLedesmaC I see you have a fork of HC with a Spanish translation, do you want it added to the main repo?

**Comment by danmaxis** [comment]
Thanks! I thought it would be easier for you that has the project environment all set.
Perhaps a further review might be need when testing, to see if some terms need shortening.
It was really interesting because I had to read all HC is capable doing 😁 and read about aviation control terms in portuguese hehe I even will try it with Ace Combat and Forza to check these features.

**Comment by MiguelLedesmaC** [comment]
Well I eliminated the English language and added the Spanish, if you want I
can pass you the resources and add it to the main

**Comment by CasperH2O** [comment]
@MiguelLedesmaC sounds good! Can you share the 3 resx files with me, I'll take care of the rest.

**Comment by Crover81** [comment]
I have completed the Italian translation of the software, there may be some interpretation errors, but I hope they are few

Controller Service: https://pastebin.com/U3hTmNdp
Controller Common https://pastebin.com/dKE6GDzg
Handheld Companion: https://pastebin.com/rKxj7cxe

**Comment by MiguelLedesmaC** [comment]
Sorry with the children's vacations I have little time, I have the files
ready, I leave them below. The same as the previous companion, there may be
interpretation errors or words that sound different that need to be
polished, but the important thing is that it will be more readable for the
Spanish.

**Comment by CasperH2O** [comment]
@MiguelLedesmaC thank you, we do what we can in the time we have, your effort is appreciated. It seems you forgot to attach the files though?

**Comment by MiguelLedesmaC** [comment]
Sorry, I did it in a hurry, what I tell you, children lose us! hahaha

HandleCompanion: _https://pastebin.com/xQDB8sKD_

ControllerService: _https://pastebin.com/R1n1QWhk_

ControllerCommon: _https://pastebin.com/g3TiqDT3_

Done, it's a pleasure to be a contributor to this project, go ahead it's a great application.

Greetings.

**Comment by CasperH2O** [comment]
@Crover81 @danmaxis @MiguelLedesmaC thank you all very much for contributing to the translation of HC. I have added all your files to the code and it should be included in the next (public) release. 

Since we keep adding things to HC, I've added English placeholders to the respective language files for anything that was missing. If you find anything missing or in need of translation, that should make things easier.

**Comment by danmaxis** [comment]
Hello there Casper,
I saw the new lines, I hope I can deliver you up to date files before the end of the day

**Comment by danmaxis** [comment]
Here it is. 
An updated version including new strings and some adjustments (moved tdp acrononym definition to description).

Handheld Companion Resources.pt-BR.resx
https://pastebin.com/KM38Zt4P

**Comment by CasperH2O** [comment]
Thank you everyone who contributed to the additional languages. I'll close this ticket for now and make new ones for individual languages when applicable. 😄
