### ISSUE TITLE
Steam deck control on steam

### ISSUE THREAD

**Issue by Taboulet** [Valkirie/HandheldCompanion#669]
When i first installed windows on my steam deck, the controller wasn't working in any game (which is logical) expect on steam where he recognized the steam deck button. When i installed handheld companion i was able to play any gale by using the xbox controller emulator but it wasn't showing the steam deck layout on steam even when the handheld companion app wasn't open. So now, i need to make a new controller profile only for steam. Can you please fix that ?

Cheers ^^
Taboulet

**Comment by CasperH2O** [comment]
@Taboulet that's strange. HC should automatically change this behind the screens so that you have your SteamDeck controller within Steam.

Which version did you use? Did you use an older version in the past that did work?

**Comment by Taboulet** [comment]
With every version that i used it didn't work. But i forgot to mention that when i launch a steam related game when hc is open in the background nothing is working at all but when hc is not open only the d-pad, the menu button (not the steam button,the menu one) and the a,x,b and y button

**Comment by CartoonistDude** [comment]
Also ran into this issue, I use to have control in steam and what I find odd is that it sees an xbox controller but still can't control it. Is there anyway to make it so xbox controller is for pretty much any other game outside steam and steam goes back to steam inputs? Maybe I'm just not picking the correct settings in this case.
Using the latest version of the HC

Only other information I can give is I was previously using Steam Tools, before hand and disable them to start at boot. But could it be causing a conflict even though it not running?

**Comment by Taboulet** [comment]
Someone can help ?

**Comment by Taboulet** [comment]
It isn't toggled on

**Comment by Taboulet** [comment]
Did you found something that could cause the bug ?

**Comment by Taboulet** [comment]
Can i get help ? :(

**Comment by Taboulet** [comment]
With the new steam controller hybrid mode i'll close this issue, i'll make another one if it doesn't work
