### ISSUE TITLE
ROG Ally - Pressing OEM M1 or M2 while other buttons are also pressed causes other buttons to disengage

### ISSUE THREAD

**Issue by hifihedgehog** [Valkirie/HandheldCompanion#671]
*Issue description*: I observed today on my ASUS ROG Ally that if I ever accidentally press the M1 and M2 when other buttons are pressed and held down, the pressed state of the other buttons on the virtual gamepad are lost from the controller.

*Steps to reproduce*: Play a game like Mario Kart: Double Dash with the A button held down for the gas pedal in a race. Accidentally press M1 and/or M2 on the Ally. It will cause the A button’s pressed state to be lost from the virtual gamepad unless I remove my finger from the A button and press it again.

*Suggested fix*: Maintain other buttons’ pressed states regardless of button states of M1 and M2 button.

**Comment by CasperH2O** [comment]
Can confirm. This is due to the more unique implementation needs of the Ally. Needs improvement.

**Comment by pinecones-sx** [comment]
There is definitely a lot of weirdness going on with the OEM buttons for ROG Ally.  The back paddle buttons as well as the command center & armoury crate buttons act strangely and unexpected very often.

I especially have issues using the back paddle buttons in combination with the command center & armoury crate buttons to trigger actions.

**Comment by CasperH2O** [comment]
Today ASUS ROG dropped the following update changelog: https://rog-forum.asus.com/t5/changelogs/changelog-august-8-2023-rog-ally/ba-p/948908

With the following interesting remark:

> Bug fix: Fixed a bug where pressing M1 or M2 would cancel inputs from any other buttons if pressed together. 

So perhaps this is a ROG Ally firmware/BIOS issue and not an HC issue. Let's update and find out.

**Comment by ggrensteiner** [comment]
Here's a wireshark capture and python code to put the device into a mode where the back buttons are normal events, not modifier keys. I think it's set to left ctrl F9 and F10 in this example.

[splitback.zip](https://github.com/Valkirie/HandheldCompanion/files/12566706/splitback.zip)

**Comment by ggrensteiner** [comment]
And here's a few more usb packages that, in linux, switch it from default boot mode, to the desktop mode with a hardware mouse on right stick, and that split back mode as well.

I'm still trying to figure out what it's actually doing to maybe unlock more flexibility, but this should give a lot more options for you already with hcc.

[configscripts.zip](https://github.com/Valkirie/HandheldCompanion/files/12566893/configscripts.zip)

**Comment by Valkirie** [comment]
@trippyone

**Comment by Valkirie** [comment]
> Here's a wireshark capture and python code to put the device into a mode where the back buttons are normal events, not modifier keys. I think it's set to left ctrl F9 and F10 in this example.
> 
> [splitback.zip](https://github.com/Valkirie/HandheldCompanion/files/12566706/splitback.zip)
> 

Good job, let me look into it.

**Comment by ggrensteiner** [comment]
This is as far as I'm going to take it. The current scripts put the M1 on KEY_F17 and M2 on KEY_F18 along with some updated notes for other keysyms. It's pretty rough. 
[allycontrollermodes.zip](https://github.com/Valkirie/HandheldCompanion/files/12643369/allycontrollermodes.zip)

**Comment by ggrensteiner** [comment]
Here's a package with M1 on KEY_F17 and M2 on KEY_F18 in normal mode and in mouse mode. I think this is where I'm going to leave off my research on it directly. I may have a peek at the firmware load from MCE which would give me much more control.

[allycontrollermodes1.1.zip](https://github.com/Valkirie/HandheldCompanion/files/12643460/allycontrollermodes1.1.zip)

**Comment by Valkirie** [comment]
Thank you very much for your efforts here. I'll have a look at it and see how to turn this into C#

**Comment by CasperH2O** [comment]
@ggrensteiner I've been going over your files in detail. Am I right in understanding from your transition note that this command would turn M1 into an F17 and M2 into an F18 key?

`5ad1 02082c 020028 00000000000000000000000000000000000000 020030 0000000000000000 000000 0000000000000000000000000000000000000000000000 m1 on KEY_F17 + m2 on KEY_F18 (initbettersplit.py)`

Do you still have that initbettersplit.py file? It wasn't in any of the zips? I'm trying to test this at the moment.

**Comment by CasperH2O** [comment]
This has been fixed, will be included in the next release. Thank you everyone for contributing.
