### ISSUE TITLE
Steam Deck No physical controller detected

### ISSUE THREAD

**Issue by Bigflood92** [Valkirie/HandheldCompanion#674]
I would like to report an issue with the last two versions of the program. It has stopped working on the Steam Deck and displays the error message ‘no physical controller detected’.

**Comment by CasperH2O** [comment]
@Bigflood92 did you by any chance install Gullikit joysticks? We have a beta build on Discord that fixes that.

**Comment by Bigflood92** [comment]
Hi, Yes, I have them installed, the first model of gulikit and works correctly with the beta 3 fix you sent


-------- Mensaje original --------
De: CasperH2O ***@***.***>
Fecha: 1/7/23 13:00 (GMT+01:00)
Para: Valkirie/HandheldCompanion ***@***.***>
Cc: Bigflood92 ***@***.***>, Mention ***@***.***>
Asunto: Re: [Valkirie/HandheldCompanion] Steam Deck No physical controller detected (Issue #674)


@Bigflood92<https://github.com/Bigflood92> did you by any chance install Gullikit joysticks? We have a beta build on Discord that fixes that.

**Comment by Valkirie** [comment]
Fixed with https://github.com/Valkirie/HandheldCompanion/commit/891cf46c1c83a15ac8bb24b4785f90a70ce311d5
