### ISSUE TITLE
HC 0.16.2.3 , hide controller won't work anymore (ally)

### ISSUE THREAD

**Issue by azodev** [Valkirie/HandheldCompanion#676]
Hi, don't know what happened but after waking for sleep mode today, HC won't hide the physical controller anymore.
Now I have 2 XBOX 360 controller displayed in joy.cpl. If I click on hide (in input main page of AC), it hide the controller for 1 sec before it comes back.

Before this issue happened I had 2 input appearing in HC, I rebooted. And now 1 in HC but 2 in windows when service is enable.
If I stop the service , 1 appears now in joy.cpl, but I soon as I start it again, 2 .

It tried to reinstall and keep settings, no changes.

Is there any fix?

**Comment by updawg** [comment]
Have you tried enabling extended compatibility mode on the profile?

**Comment by CasperH2O** [comment]
Perhaps something went wrong with HidHide. With HC open, can you open HidHide Configuration Client, navigate to the second tab and hide the hardware controller. If they are both called xbox 360, set HCs virtual controller to DS4 to make it easier to distinguish.

**Comment by azodev** [comment]
> Perhaps something went wrong with HidHide. With HC open, can you open HidHide Configuration Client, navigate to the second tab and hide the hardware controller. If they are both called xbox 360, set HCs virtual controller to DS4 to make it easier to distinguish.

It's indeed fix the issue in games like Doom eternal, but only for the current session, as soon as I reboot, or wake from deep spleep, I have to manually hide the physical controller in HidHide Configuration Client. This issue seems to be introduced by 0.16.2.3.

**Comment by azodev** [comment]
fixed in new version
