### ISSUE TITLE
installation error on rog ally

### ISSUE THREAD

**Issue by brutaljelly** [Valkirie/HandheldCompanion#682]
![a218ebdd-4ebd-4597-9b1b-11db4454b465](https://github.com/Valkirie/HandheldCompanion/assets/138476118/b0ad1a67-7bcf-44e9-b97c-5d0139d8d6fd)

tried to restart, no matter what i do it wont go past this error

**Comment by CasperH2O** [comment]
@brutaljelly yes, this is a typical issue when using the regular (non offline) installer. For the latest release I did not make an offline installer yet, I'll upload it and you can try again.

Alternatively, try using a stable internet connection and or non firewalled if that is feasible for you.

**Comment by brutaljelly** [comment]
i have 2 internet connections of 1Gbps both having same issue. they stop installing at this exact same spot

**Comment by brutaljelly** [comment]
@CasperH2O nvm, finally it worked with mobile 5g. thanks
