### ISSUE TITLE
DSU Server configurable IP address and port

### ISSUE THREAD

**Issue by trippyone** [Valkirie/HandheldCompanion#685]
How to replicate:

Install HC on device (EX: Rog Ally) and make sure it is running.
Install Yuzu on PC
Go to Controls, Motion, and type in Rog Ally's IP address, port 26760.
Click on Test server. Yuzu will not be able to receive motion infos.

I confirm the network configuration is adequate.

You can try this locally on the Rog, it's confirmed to be working.

I believe HC is binding to a local IP like 127.0.0.1, so it is not allowing external access to the motion sensor server.

![image](https://github.com/Valkirie/HandheldCompanion/assets/137233897/02224be2-1d27-4e70-a5cd-71b7da083967)

**Comment by CasperH2O** [comment]
Yes, in a very early version (0.6?) it was possible to configure the IP address, but it was removed when HC moved to the WPF GUI and is now hardcoded as it was never really needed to adjust this value and all emulators use the same ip and port number. 

Could be improved indeed.

**Comment by CasperH2O** [comment]
@trippyone does the new update in 0.16.2.5 also help for this?

**Comment by trippyone** [comment]
Yep, "bug" fixed.
