### ISSUE TITLE
"Get an app to open this 'ms-gamebar' link" error message on startup

### ISSUE THREAD

**Issue by philipjholm** [Valkirie/HandheldCompanion#686]
I have uninstalled the xbox game bar on my ROG Ally as I dont want to use it. But after doing so the following popup comes up everytime I start HC or exit it. How can I fix this? I've also unchecked the checkbox under windows settings -> gaming -> Xbox game bar.

![rogally](https://github.com/Valkirie/HandheldCompanion/assets/37110163/12065fd6-4bd6-4b6a-80c3-f712f6a161cf)

**Comment by CasperH2O** [comment]
Hey @philipjholm , for me, solution 2 from this website worked.

https://www.makeuseof.com/windows-new-app-ms-gamingoverlay-error/

**Comment by Nikanoru** [comment]
> Hey @philipjholm , for me, solution 2 from this website worked.
> 
> https://www.makeuseof.com/windows-new-app-ms-gamingoverlay-error/

For me, Option #6 worked, doing it via the registry, while Option #2 did not work.

**Comment by jaapbrasser** [comment]
Option 6 fixed it for me, thanks for sharing this!

**Comment by azaryabernard** [comment]
Hi @JunarisAlf I also couldn't solve the problem with the given link, but these commands finally fixed it for me:

 ```
reg add HKCR\ms-gamebar /f /ve /d URL:ms-gamebar 2>&1 >''
reg add HKCR\ms-gamebar /f /v "URL Protocol" /d "" 2>&1 >''
reg add HKCR\ms-gamebar /f /v "NoOpenWith" /d "" 2>&1 >''
reg add HKCR\ms-gamebar\shell\open\command /f /ve /d "\`"$env:SystemRoot\System32\systray.exe\`"" 2>&1 >''
reg add HKCR\ms-gamebarservices /f /ve /d URL:ms-gamebarservices 2>&1 >''
reg add HKCR\ms-gamebarservices /f /v "URL Protocol" /d "" 2>&1 >''
reg add HKCR\ms-gamebarservices /f /v "NoOpenWith" /d "" 2>&1 >''
reg add HKCR\ms-gamebarservices\shell\open\command /f /ve /d "\`"$env:SystemRoot\System32\systray.exe\`"" 2>&1 >''
 ```

(Powershell Admin)

From: [reddit](https://www.reddit.com/r/Windows11/comments/wwc9if/comment/ilodbyj/)
