### ISSUE TITLE
New update rog ally - Quick Menu minimize game

### ISSUE THREAD

**Issue by gogomimigo** [Valkirie/HandheldCompanion#690]
After updating, game no longer minimize when opening quick menu. But when try to click the quick menu, it will minimize the game.

**Comment by CasperH2O** [comment]
This is regular Windows behavior. You can prevent this by setting your game to Borderless or Windowed Maximized or use the gamepad navigation instead of touch on QT.

**Comment by gogomimigo** [comment]
Thank you! It's a bit of getting used to using the gamepad but it's manageable. Hopefully there'll be a fix or patch for this. Your tool has been a miracle for me for my ally.
