### ISSUE TITLE
Windows fonts are effected after HC installation

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#693]
Installing HC (0.16.2.4) effects users font in the rest of Windows.

![afbeelding](https://github.com/Valkirie/HandheldCompanion/assets/14330834/816fef1f-55d0-49db-aa49-00a8fb72d597)

It seems to be font Segoe Fluent Icons.ttf

Removing it makes it worse, installing a fresh font does not resolve it. Inno installer should only install it if it does not already exist. The reason it was added to the installer is because W10 doesn't have this font by default.

Current idea is to update Inno installer to only install if W10 is detected.

**Comment by TRD0118** [comment]
I also had / have this issue, I was able to mostly resolve it by replacing all the fonts with ones from my desktop PC. I say mostly since the task manager icons for efficient and suspended apps (the green leaf and yellow pause ones) are still corrupted into the coloured versions of those rectangles :/ This is on an ROG Ally btw

**Comment by frickingphil** [comment]
Hi, I was also affected by this bug. I was able to fix it after uninstalling HC by restoring my System Restore point I had made before installing HC.

I'd run into this issue before and ended up doing an in-place Windows reinstall to fix it originally, but I'm glad to see that the restore point fixed it for me.

**Comment by rosdan13** [comment]
Found a fix!
In registry search for "segoe fluent icons", and change the value (data) from "segoe fluent icons.ttf" to "SegoeIcons.ttf"

**Comment by Valkirie** [comment]
> Found a fix! In registry search for "segoe fluent icons", and change the value (data) from "segoe fluent icons.ttf" to "SegoeIcons.ttf"

Thanks for sharing. Let us replicate and try to avoid the issue from arising in the first place.

**Comment by frickingphil** [comment]
> Found a fix!
> In registry search for "segoe fluent icons", and change the value (data) from "segoe fluent icons.ttf" to "SegoeIcons.ttf" and reboot.

Can confirm, just reinstalled and performed the fix and it worked just fine. Nice.

**Comment by Valkirie** [comment]
Attached is a fix from @ExCP. Unzip the archive and double click on the file. Restart.
[FixIconsHC.zip](https://github.com/Valkirie/HandheldCompanion/files/12012358/FixIconsHC.zip)
