### ISSUE TITLE
Special key not working properly with emulated DS4 controller

### ISSUE THREAD

**Issue by trippyone** [Valkirie/HandheldCompanion#698]
Requirements:
- Steam big picture
- Rog Ally
- HC + Emulated DS4 controller

How to replicate:

Press OEM1 key while Steam big picture is running. It should normally bring up the Steam navigation menu (like the Xbox guide button) but it's not. If you spam it, it will eventually show up. I did some investigation, it seems we are indeed injecting OEM1 key so I'm not sure what is the issue yet. I have attached my logs.
[logs.txt](https://github.com/Valkirie/HandheldCompanion/files/11994250/logs.txt)

**Comment by trippyone** [comment]
I traced the code up to the service. It appears to be sending the correct key. Is it an issue on ViGEM level?
![image](https://github.com/Valkirie/HandheldCompanion/assets/137233897/63813398-3e0a-42a6-98ad-511198ac5512)

**Comment by trippyone** [comment]
#705

**Comment by CasperH2O** [comment]
Fixed by @trippyone in #705
