### ISSUE TITLE
Weird bug where you control 2 players with 1 controller? 

### ISSUE THREAD

**Issue by planet** [Valkirie/HandheldCompanion#702]
This is especially apparent in 2 player arcade emulated games but I've also seen it in games like TMNT Shredders Revenge. If you press start on the built in controller you end up pressing start for both P1 and P2 and end up starting a game with 2 players.  You will then control both players with the same controller. I looked at Retroarch for example, it sees 2 XBOX controllers when infact I'm only using the built in controller.

Is this a bug?  If it's a not bug, how do I fix this? 
I'm using the ASUS ROG Ally if it matters.

![image](https://github.com/Valkirie/HandheldCompanion/assets/1265868/58949be6-dfb2-4026-bcc9-ea52ee62ca80)

**Comment by CasperH2O** [comment]
It looks like both the virtual controller and the physical hardware controller are visible, have you set your physical controller to be visible on purpose or perhaps you don't need the virtual one?

**Comment by planet** [comment]
@CasperH2O what should the standard configuration be? Should the physical controller be hidden usually?  It seems like when I do that I can't see any xbox controllers available. 

For now I disabled one of the XBOX controller and it seems to work ok.

**Comment by CasperH2O** [comment]
@planet it depends on how you prefer to play and use the system. If you don't need the virtual controller, you can disconnect it and unhide your physical controller.

Glad you found a way it works for you. HC is quite the toolbox.
