### ISSUE TITLE
HC force closes HWInfo if overlay display level is set to disabled

### ISSUE THREAD

**Issue by Igosama2** [Valkirie/HandheldCompanion#703]
Talked straight to Casper and it does make sense. I was using a custom overlay on RTSS and noticed HWInfo was supposedly "crashing" every time I was playing a game and closing HC was solving this issue. The only way to stop this behaviour is simply closing HC or setting "overlay display level" to anything but "disabled".

**Comment by philipjholm** [comment]
Yes, hwinfo is closed seemingly a bit randomly. I would appreciate if it wouldn't close rtss or hwinfo at all as I am using it for other things on the side and need them open all the time. I am voting for a setting to just leave them running no matter what ❤️

**Comment by CasperH2O** [comment]
Thanks to @micdah , HC 0.18 will feature the OSD option "External", which will fix this situation.
