### ISSUE TITLE
RTSS doesn't show CPU Clocks after installing HC

### ISSUE THREAD

**Issue by xLuxSoldi3Rx** [Valkirie/HandheldCompanion#711]
Since i used HC, i am unable to get my Cpu clock shown in Rtss overlay. It's on an A1 Pro 7840u. Tried uninstalling, reinstalling, deleting all folders manually, nothing helps! 
Before i used HC (early access), it worked fine with other Tools like MA or Onexconsole. 

Someone with a solution?

**Comment by CasperH2O** [comment]
@xLuxSoldi3Rx can you provide:
- HC version used
- Physical device type
- RTSS version
- HWInfo version
- Some screenshots of your configuration or RTSS

**Comment by xLuxSoldi3Rx** [comment]
- Early access latest one for A1 Pro
- Aokzoe A1 Pro (32/2)
- Rtss 7.3.4 (latest)
- HwInfo 7.46 and 7.50 
- I can provide rtss screenshot, its running with onexconsole one key button

- Sensor i will send also a picture of source.

There you have all pics like onexconsole for running overlay in rtss, rtss settings (no other stuff changed), the overlay with the missing value and the value code in rtss preinstalled from onexconsole.

(I found one interesting point, if you enable memory integrity in defender and reboot, the value is back again, disabling it and value is gone, but we need to disable memory integrity because of the tool)

![image](https://github.com/Valkirie/HandheldCompanion/assets/138074268/3082fb25-81c9-4948-8695-12f57603d7a8)
![image](https://github.com/Valkirie/HandheldCompanion/assets/138074268/04f1f669-7e58-4189-b892-01fc581f8a65)
![image](https://github.com/Valkirie/HandheldCompanion/assets/138074268/6873181d-7026-4b6c-82e3-699b55d813f3)
![image](https://github.com/Valkirie/HandheldCompanion/assets/138074268/9934888a-b9c7-4c5b-a26e-d4cd488a96ff)
