### ISSUE TITLE
Exclude GamePadCustomizeOSD.exe from foreground process

### ISSUE THREAD

**Issue by azodev** [Valkirie/HandheldCompanion#714]
Hello, can you add  GamePadCustomizeOSD.exe in the blacklist for excluding it from being use as foreground process by HC ? 
It messes with game profiles like cyberpunk. by changing tdp during games (since it make hc go back to default profile).
On Rog Ally , it's part of armoury crate se suite.

Thanks.

**Comment by CasperH2O** [comment]
Thanks for reporting @azodev it's been added.

**Comment by CasperH2O** [comment]
Done.
