### ISSUE TITLE
Need the ability to fully kill any and all controller functionality in HC

### ISSUE THREAD

**Issue by molnizzle** [Valkirie/HandheldCompanion#721]
I followed the FAQ steps in "What if I only want to use HC for Auto TDP" and controller input is still completely busted on my ROG Ally. I followed the steps to a T and my settings look exactly like the FAQ says they should. I still get double inputs navigating Armoury Crate with the d-pad, and games are unplayable due to double inputs or different inputs. 

There needs to be a nuclear option to just kill all of this controller nonsense. I understand that HC needs this stuff on other devices, but there is literally never a scenario where you would want to use this stuff on the ROG Ally. Auto TDP is awesome but it's not much use if I can't play anything. Really bumming me out.

**Comment by CasperH2O** [comment]
Hey @molnizzle . I detect some frustration, sorry about that. It's strange you get double inputs, if the service isn't running, there is no way HC can input gamepad controls in your system.

Are you by any chance also using Steam? Does it have extended compatibility configured?

**Comment by Faandango** [comment]
Hiya, thanks for all your hard work on HC.
But, totally agree with original post.
HC controller is far to complex with all the Hiding & Muting.
I just want to turn OFF all of the Controllers with one foul swoop.
I get Double inputs, crashes etc using them.
I use Steam Deck, with Windows 11 & Steam.
Steam gives me all the controls I need. Full pull, Soft Pull etc.
Thanks!

**Comment by CasperH2O** [comment]
To stop using any controller related features from HC:
- In the main GUI, bottom left, stop service, uninstall service
- In the main GUI, controller page, unhide your physical controller
- Double check the settings that the service is not started at boot

Closing ticket.
