### ISSUE TITLE
Easy way to Turn OFF Controller! Please 

### ISSUE THREAD

**Issue by Faandango** [Valkirie/HandheldCompanion#725]
Hiya, thanks for all your hard work on HC.

HC controller is far too complex with all the Hiding & Muting.
I just want to turn OFF all of the Controllers with one foul swoop.
I get Double inputs, crashes etc using them.

I use Steam Deck, with Windows 11 & Steam.
Steam gives me all the controls I need. Full pull, Soft Pull etc.

Retain all the Hot keys, Popups etc. 

Keep things simple. 
After all, people just want to Play Games. (But with options which you offer) 
Thanks!

**Comment by CasperH2O** [comment]
You can disable all the controller by, on the controller page, disconnect the virtual controller, unhide the physical controller, stop the service in the bottom left corner, remove service in the bottom left corner. 

Make sure your settings are such that the service is not started after boot (main settings).

**Comment by CasperH2O** [comment]
@guybrush-threepwood-the-third I don't fully understand your issues you are having? The instructions above were for an older version that still had a separate service. With the newer app, you only have to disconnect the virtual controller and connect the physical one, that's it.

**Comment by guybrush-threepwood-the-third** [comment]
> The instructions above were for an older version that still had a separate service. 

Ah, okay. The screen shots in the README still show that service element in the UI, so I thought I was missing it.

> With the newer app, you only have to disconnect the virtual controller and connect the physical one, that's it.

The problem I'm having is the app automatically connects with the physical controller on app startup, which is conflicting with my preferred controller desktop app and causes a few different problems.

Is it possible to stop the app from automatically connecting with the physical controller and taking control of it?
