### ISSUE TITLE
Cannot start service rog ally

### ISSUE THREAD

**Issue by DxGleba** [Valkirie/HandheldCompanion#726]
So i just cant start service, when i press start service after few seconds its stop automatically

**Comment by CasperH2O** [comment]
Can you share your logfiles from /programfiles/handheldcompanion/logs ?

**Comment by CasperH2O** [comment]
@DxGleba we release HC version 0.18 where the service has been removed and it's features integrated in the main app. Could you check and confirm if you still have this issue with that version?

**Comment by DxGleba** [comment]
there is no issue now, but when i reinstall windows i didnt have problem
with "start service"

**Comment by CasperH2O** [comment]
@DxGleba thanks for confirming. Closing ticket.
