### ISSUE TITLE
Doesn't start on Rog ally

### ISSUE THREAD

**Issue by Dulcidi** [Valkirie/HandheldCompanion#727]
Hello, it doesn't start on my rog ally...
Nothing task manager, neither in tray
I've tried uninstalling, reinstall, delete files manually, ccleaner, but still nothing...
Has somebody had the same problem ?

**Comment by CasperH2O** [comment]
Can you install HC, try to start it, then share the .dmp and log files from /programfiles/handheldcompanion/logs ?

**Comment by Dulcidi** [comment]
![16896217057912116957144758313838](https://github.com/Valkirie/HandheldCompanion/assets/51060510/097e9e27-5595-4409-8493-2bfa51d7e7e6)
Don't have any log in there :-(

**Comment by CasperH2O** [comment]
Can you open the ControllerService application (with admin rights) and see if that opens a terminal?

**Comment by Dulcidi** [comment]
Nope, nothing seems to happen either.
Just tried installing again, and on SD, but not success on either

**Comment by CasperH2O** [comment]
@Dulcidi are you on Discord, that might work faster? https://discord.gg/4zHuK6wH

**Comment by CasperH2O** [comment]
Checked this with @Dulcidi remotely, could not figure it out, makes no sense.

Aside from installing VS 2023 and running the app from source I have no further ideas.

**Comment by CasperH2O** [comment]
Closing this as a "can't fix", no idea. Works fine on multiple other ROG Ally owner devices. Known issue for HC not starting is having the Tiny Windows OS installation.
