### ISSUE TITLE
More robust FPS cap options to accomodate VRR screens.

### ISSUE THREAD

**Issue by mobiousblack** [Valkirie/HandheldCompanion#737]
Given the ROG Ally's VRR capabilities and the high potential for future handhelds to support the same feature. I would request that the FPS limit be more adjustable for a wider range of choices, either by making a slider that has a selection based on the max refresh rate of the screen with increments of say 5 or have a field where you can select the fps cap manually by inputting the desired number like you see on RTSS.

**Comment by micdah** [comment]
I'm not 100%, but pretty sure HC actually does use the device/screen refresh rate to set min/max values for the slider, and then it has 4 levels, i.e. 1/4, 2/4, 3/4 and 4/4 of the max refresh rate.

Perhaps the number of levels should be increased to giver wider range of values to choose from?

**Comment by AleITDE1990** [comment]
> I'm not 100%, but pretty sure HC actually does use the device/screen refresh rate to set min/max values for the slider, and then it has 4 levels, i.e. 1/4, 2/4, 3/4 and 4/4 of the max refresh rate.
> 
> Perhaps the number of levels should be increased to giver wider range of values to choose from?

I didn't open this issue but I share the request and yes, personally I'appreciate a different method: not dividing the range by X but measuring the rage (60, or 120hz depending on the device) and dividing it by 5 or 10, these are the levels I'd like to have. By 120hz we would then have 5 or 10 fps steps.

**Comment by breakwinz** [comment]
Just adding to this. I was surprised when i coulnt set 40fps on. 60hz screen. 40/45fps can a lot of times be a sweet spot for battery/performance between 30-60

**Comment by NightHammer1000** [comment]
The FPS Slider takes a few Fractions from the Refresh Rate.
I, personally, think that is not a very good approach to that.
Just make the Slider Free-Range between 1 and Refresh Rate and let the User Freely set the Limit.

**Comment by CasperH2O** [comment]
> The FPS Slider takes a few Fractions from the Refresh Rate. I, personally, think that is not a very good approach to that. Just make the Slider Free-Range between 1 and Refresh Rate and let the User Freely set the Limit.

I tend to agree, at the risk of users setting odd values resulting in screen tearing and thus complaints though... 😕

**Comment by NightHammer1000** [comment]
Just make sure to Display the Current Value set in a Small Textbox or Lable under or beside to Slider.
I think nobody will complain their Game runs at 1FPS when theres Lable telling you:
Current Max FPS: 1

If someone is not smart enough for that...
So help them God.

**Comment by CasperH2O** [comment]
> Just make sure to Display the Current Value set in a Small Textbox or Lable under or beside to Slider. I think nobody will complain their Game runs at 1FPS when theres Lable telling you: Current Max FPS: 1

I don't fully understand your suggestion, the current value of what, the screen Hz? Actual game FPS?

> If someone is not smart enough for that... So help them God.

I work under the assumption that everyone is an idiot and if they can mess up HC settings it will lead to complaints and support requests. 

That said, the slider does get odd values like 15... We could improve in this area.

**Comment by CasperH2O** [comment]
This has been improved greatly by @MSeys in Valkirie/HandheldCompanion-EA#113

Closing.
