### ISSUE TITLE
Disconnected virtual controller is re-initialized once a second

### ISSUE THREAD

**Issue by romracer** [Valkirie/HandheldCompanion#738]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [X] AOKZOE
- [X] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
I have logs from ASUS ROG Ally and AOKZOE A1, but probably any device.

**Handheld Companinion Version**
0.16.2.6b

**Describe the bug**
In HC, I leave the virtual controller disconnected.  The following log lines repeat once per second in ControllerService log files:

```
2023-06-29 11:01:06.317 -05:00 [INF] Emulated DualShock 4 controller initialized, Nefarius.ViGEm.Client.Targets.DualShock4Controller
2023-06-29 11:01:07.318 -05:00 [INF] Emulated DualShock 4 controller initialized, Nefarius.ViGEm.Client.Targets.DualShock4Controller
2023-06-29 11:01:08.320 -05:00 [INF] Emulated DualShock 4 controller initialized, Nefarius.ViGEm.Client.Targets.DualShock4Controller
```

It can also say Xbox 360 if using a virtual Xbox 360 controller instead of DS4.

**To Reproduce**
1. Set virtual controller to Disconnected.
2. Exit HC.
3. Start HC.
4. Check ControllerService log file for repeating message.

**Expected behavior**
It should just be logged once.

**Screenshots**
N/A

**Logs file**
Log lines above.

**Comment by romracer** [comment]
The log line appears to come from setting the controller mode (DS4 or Xbox 360) here:

https://github.com/Valkirie/HandheldCompanion/blob/0.16.2.5/ControllerService/ControllerService.cs#L616

which creates a new target and generates the log line here:

https://github.com/Valkirie/HandheldCompanion/blob/0.16.2.5/ControllerService/ControllerService.cs#L218

The repeating once per second is here:

https://github.com/Valkirie/HandheldCompanion/blob/0.16.2.5/ControllerService/ControllerService.cs#L618

I was able to fix the issue by changing the while loop condition at https://github.com/Valkirie/HandheldCompanion/blob/0.16.2.5/ControllerService/ControllerService.cs#L607 to

`while (vTarget is null || (HIDstatus == HIDstatus.Connected && !vTarget.IsConnected))`

but I'm not great at C# so I'm not sure if this is the "right" fix.  The idea being that the while loop should only expect vTarget.IsConnected if HIDstatus is also Connected.  Otherwise, vTarget.IsConnected will never be true.

**Comment by CasperH2O** [comment]
Excellent work @romracer , @Valkirie what do you think of the proposed solution?

**Comment by romracer** [comment]
Not that it's any of my business but is he on vacation or something? :P  I can submit a PR if this is the right fix.  I just wanted to report an issue and confirm it before doing so :)

**Comment by CasperH2O** [comment]
@romracer yes, @Valkirie is indeed currently on (a well deserved) holiday. 😄

**Comment by romracer** [comment]
This code doesn't exist anymore.  Closing.
