### ISSUE TITLE
Customizable OSD

### ISSUE THREAD

**Issue by xexets** [Valkirie/HandheldCompanion#744]
**Is your feature request related to a problem? Please describe.**
I would like to add temperatures to the 'extended overlay' or frequencies to the 'Full' overlay. 

**Describe the solution you'd like**
Being able to do it

**Describe alternatives you've considered**
Using another monitoring software, but integration with HC QT is great

**Additional context**

**Comment by CasperH2O** [comment]
@xexets everything is currently very hard coded. This discussion shows how you can add more entries: https://github.com/Valkirie/HandheldCompanion/discussions/743

**Comment by CasperH2O** [comment]
Some initial prototyping has been done on this subject by @0skillallluck.

**Comment by CasperH2O** [comment]
Done.
