### ISSUE TITLE
Game (Ghostwire Tokyo) doesn't move using HC, other games/apps work fine

### ISSUE THREAD

**Issue by Jarvis343** [Valkirie/HandheldCompanion#749]
ASUS 

ROG Ally

**Handheld Companinion Version**
Release 0.16.2.5

**Describe the bug**
I'm using both Armoury crate and HC.
When I use HC and play Ghostwire Tokyo it doesn't take the virtual gamepad inputs. 
I can see the game is detecting the gamepad but it doesn't take the input: if I touch press on game interface it shows keyboard buttons and if I press on gamepad buttons it switches to the Xbox controller icons.
Issues seems only heppening with this game for now. I tried other Game Pass games, Yuzu, Armoury Crate and Xbox app and all take the HC controller inputs.
If I stop the service and close HC Ghostwire Tokyo take the Xbox controller input normally.
Don't know if this is a known issue.

Thanks!!

**Comment by CasperH2O** [comment]
@Jarvis343 thanks for reporting this. It's "normal" that some games don't work with the virtual controllers (either type) and just the physical gamepad only. Sometimes it's the other way around. 

If you found a workable situation with stopping the service you can play like that. Alternatively you can try making a profile for the game and ticking allow access to physical controller, that should make things easier.

**Comment by Jarvis343** [comment]
Yes thanks! I tried making a profile and it worked. 
I was wondering if could be a way to let the Xbox Game Bar see the physical controller too. I tried creating a profile with the executable of XGB but seems it not accessible.
