### ISSUE TITLE
Support Ayaneo Air Plus Intel 1215u 

### ISSUE THREAD

**Issue by plumlis** [Valkirie/HandheldCompanion#755]
Mine is Ayaneo Air Plus intel 1215u and it seems HC can't recognized this model.
But in changelog it said Ayaneo air plus is already supported.

Anything wrong I did?

**Comment by plumlis** [comment]
https://github.com/Valkirie/HandheldCompanion/releases/tag/0.16.0.5

Features：
…………
Ayaneo Air Plus support: Enjoy seamless compatibility with the Ayaneo Air Plus handheld.

**Comment by CasperH2O** [comment]
I see it will only detect it if the product ID is: "AB05-AMD".

From that name I guess we only have support for the AMD version at the moment. 

Can you help us make the Intel version also compatible? I'd need some info. Can you open the Windows app "System Information" and make a screenshot like this? I need the circled info:

![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/e94e433f-dc7a-402d-8065-80cf602c1fb9)

**Comment by plumlis** [comment]
I'm glad to help HC running on 1215 model.
Here is System Information screenshot:
![image_2023-08-08_18-06-31](https://github.com/Valkirie/HandheldCompanion/assets/6737429/8c433213-0d98-452b-90d2-23dcf83c47f5)
