### ISSUE TITLE
Firmware update breaks OEM buttons

### ISSUE THREAD

**Issue by MercerViruzX** [Valkirie/HandheldCompanion#756]
ASUS ROG ALLY

**Handheld Companinion Version**
0.17.0.0.

After the firmware update the OEM buttons and back buttons do not work. Sometimes it registers as button 3 and long press, never as click. 
Tried to do a fresh install and reboot several times but to no avail.

**Comment by madmatt30** [comment]
Managed after half a dozen attempts to get the right analog stick click in to register.

Can at least get the quick settings menu up with this button press now.

**Comment by MercerViruzX** [comment]
It seems like the new added feature in the firmware update messed up HHC. Is there a way to rollback the firmware update provided by Asus?

**Comment by CasperH2O** [comment]
Can confirm I also have this issue on my ROG Ally after updating the firmware. 

My current suspect is HC not detecting or clearing the pressing of the back buttons once they have been pressed once (either one). The workarounds I have found are not using the back buttons and or starting AC.

Will investigate, upcoming Friday at the earliest.

**Comment by CasperH2O** [comment]
Fixed with PR #757
