### ISSUE TITLE
AutoProfile does not actually apply even if it looks activated by launching the game

### ISSUE THREAD

**Issue by AleITDE1990** [Valkirie/HandheldCompanion#767]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [X ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
ROG Ally

**Handheld Companinion Version**
0.16.2.5

**Describe the bug**
The automatic profile recall for games, including settings like Framerate limiter, AutoTDP, EPP and so on, does not effectively apply these settings as set. It gets automaticall triggered when the game is launched, but one has to deactivate and reactivate the profile manually for it to work. IF you set a frame limiter you will be able to immediately reproduce the issue. 

I have uninstalled the entire Asus SW suite on the Ally and I'm relying on G Helper and Handheld companion. 

**To Reproduce**
Launch a game for which you have set a specific profile and check if it applies. I tried with dying light through Steam.
**Expected behavior**
the profile activates in the Handheld Companion quick toggle UI and it's immediately effective. 

**Screenshots**
I took none but I can if needed

**Logs file**
I took no logs but I can if you cannot reproduce.

**Comment by CasperH2O** [comment]
Hey @AleITDE1990 thanks for reporting in. We just released HC 0.18 with quite a large overhaul of pretty much everything. Could you double check and confirm you still have this issue with that version?

**Comment by AleITDE1990** [comment]
> Hey @AleITDE1990 thanks for reporting in. We just released HC 0.18 with quite a large overhaul of pretty much everything. Could you double check and confirm you still have this issue with that version?

Struggling as I'm affected by the double input issue since I update, and cannot even really lunch the game

**Comment by AleITDE1990** [comment]
Can finally confirm, that the latest versions solved this bug.
