### ISSUE TITLE
HC GPD win4 2023 support

### ISSUE THREAD

**Issue by RyanQQQQQ** [Valkirie/HandheldCompanion#769]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [x ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
Your device model
GPD win4 2023
**Handheld Companinion Version**
0.18.0.1

**Describe the bug**
The X-axis and Y-axis recognition of the gyroscope is reversed

**Comment by CasperH2O** [comment]
Thanks for dropping in @RyanQQQQQ . This actually makes sense as HC currently only supports the initial Win4. 

Could you open the Windows application called System Information and share a screenshot with us?

**Comment by RyanQQQQQ** [comment]
> Thanks for dropping in @RyanQQQQQ . This actually makes sense as HC currently only supports the initial Win4.
> 
> Could you open the Windows application called System Information and share a screenshot of the System Summary with us?
![微信图片_20230830120657](https://github.com/Valkirie/HandheldCompanion/assets/143486865/aac80638-67f6-4310-baff-0f1937525fab)

**Comment by CasperH2O** [comment]
Sorry @RyanQQQQQ but that's not System Information, it might be called different depending on your language. I'm referring to this application: 

![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/90146adc-c6c1-493e-bfe2-7316c5734611)

The following information is required:

![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/d334276e-006c-4458-b1c0-fe20ca7ec795)

**Comment by RyanQQQQQ** [comment]
<img width="853" alt="屏幕截图 2023-09-01 173001" src="https://github.com/Valkirie/HandheldCompanion/assets/143486865/cc685f37-f283-4198-8e50-d51ab4d8f849">

**Comment by CasperH2O** [comment]
@RyanQQQQQ excellent. Based on this it seems the motherboard info is the same as the 6800U edition, so HC is already detecting it. Regrettably the IMU mounting is apparently different for this model, that means more work.

**Comment by RyanQQQQQ** [comment]
Thank you!

**Comment by CasperH2O** [comment]
Done, added for next EA.
