### ISSUE TITLE
Controller type selection in game profiles

### ISSUE THREAD

**Issue by dovcharov** [Valkirie/HandheldCompanion#772]
Hi, and thank you for the cool companion app for handheld gaming PCs.

Is it possible to add a menu to the Profiles section, which would allow to select an emulated controller type for a game? I.e. in case one game or app supports DS4 emulated controller - I could choose DS4, and another game supports only XBox controllers, - I could choose Emulated XBox 360 controller. And the controller type would switch automatically, based on which game I launch.

**Comment by CasperH2O** [comment]
Hey @dovcharov , we already have an open feature request for this: #57 . You request is noted, closing this one as duplicate.
