### ISSUE TITLE
Rog Ally Cant open the installer

### ISSUE THREAD

**Issue by DrCoomerPhD** [Valkirie/HandheldCompanion#774]
When trying to open the exe it 
<img width="719" alt="Captura de ecrã 2023-09-03 223055" src="https://github.com/Valkirie/HandheldCompanion/assets/110489194/84ecb768-696c-43ca-83dd-02d79010b0ce">
It says find an application on the microsoft store and find an aplication to open it.
I dont know what to do someone help

**Comment by DrCoomerPhD** [comment]
Soo i tried opening it on a real computer and it says smartscreen stoped the startup of this unknown application

**Comment by CasperH2O** [comment]
@DrCoomerPhD

For the opening with Microsoft store, several solutions from this websites have helped people. https://thegeekpage.com/youll-need-a-new-app-to-open-this-exe-file/#Method_2_%E2%80%93_Running_Powershell_command

In case of the smart screen, you can click continue and accept the risk. This is a known issue as HC does not have a signed installer currenctly. #43

**Comment by DrCoomerPhD** [comment]
> @DrCoomerPhD
> 
> For the opening with Microsoft store, several solutions from this websites have helped people. https://thegeekpage.com/youll-need-a-new-app-to-open-this-exe-file/#Method_2_%E2%80%93_Running_Powershell_command
> 
> In case of the smart screen, you can click continue and accept the risk. This is a known issue as HC does not have a signed installer currenctly. #43

kinda didnt respond. i had solved it by disabling the windows antivirus.

**Comment by NightHammer1000** [comment]
Yeah for further reference this can happen when you use Trimmed down Windows Versions Like Tiny11 which actually have the app for SmartScreen removed.

This causes this. Windows wants to display a SmartScreen Warning but cant. Thus refusin to launch as a whole.
Only way around is using Full Windows or Disabling SmartScreen all together.

**Comment by CasperH2O** [comment]
> Yeah for further reference this can happen when you use Trimmed down Windows Versions Like Tiny11 which actually have the app for SmartScreen removed.
> 
> This causes this. Windows wants to display a SmartScreen Warning but cant. Thus refusin to launch as a whole. Only way around is using Full Windows or Disabling SmartScreen all together.

Good catch! I'll be sure to remember this.
