### ISSUE TITLE
ROG Ally, GPU and EPP have no effect

### ISSUE THREAD

**Issue by gengjc** [Valkirie/HandheldCompanion#777]
On rogally, adjusting the maximum frequency of the GPU will not have any effect，EPP too

The back buttons M1/M2 wish to be mapped separately

**Comment by CasperH2O** [comment]
@gengjc can you tell us how you are checking/verifying this is being done or not?

Yes, seperate M1/M2 buttons is being investigated: 671

**Comment by CasperH2O** [comment]
Thanks for reporting in, this is a known issue, see: #599
