### ISSUE TITLE
Gyro Toggle On/Off

### ISSUE THREAD

**Issue by dkswedens** [Valkirie/HandheldCompanion#778]
**Is your feature request related to a problem? Please describe.**
I like to play with gyro always on and at times I just want to turn off gyro without holding down a button

**Describe the solution you'd like**
I would like to see a way to toggle the gyro activation on and off without having to hold down a button but by simply pressing a button once to activate and then again to turn it off.

**Describe alternatives you've considered**
I can't think of any other solution without adding in another software to handle it.

**Additional context**
--

**Comment by CasperH2O** [comment]
Implemented by @fighterguard for release 0.19.0.6
