### ISSUE TITLE
Virtual controller does not working when waking device from sleep

### ISSUE THREAD

**Issue by Taboulet** [Valkirie/HandheldCompanion#779]
- [ ] VALVE

**Device model**
Steam deck (Valve jupiter)

**Handheld Companinion Version**
0.18.0.1

**Describe the bug**
After your pc enter sleep mode, if you wake it up the xbox controller wont work at all until reboot

**To Reproduce**
1. Launch hc
2. Put the emulated controller to "Xbox"
3. Put your pc to sleep mode
4. Wake the pc up
You can still use your controller for browsing but when you want to play the controller isn't detected and need to reboot the hole pc to make it work again or to switch to dualshock 4

**Expected behavior**
You should still be able to use the xbox controller

**Comment by CasperH2O** [comment]
@Taboulet thanks for reaching out. There were indeed sleep and SteamDeck related issues in 0.18.0.3 which have been fixed (see changelog). Can you update and check if you still have this issue?

**Comment by Taboulet** [comment]
No, the issue is still there but it's strange, sometimes the xbox controller just doesn't work anymore and sometime it works but it's on "Player 2" so some games don't recognize it

**Comment by Taboulet** [comment]
I mean, now it's working but previously that wasn't working. That strange

**Comment by Taboulet** [comment]
After sometime, i can confirm this works now (i probably had just did something wrong in the setting after the update. thanks !
