### ISSUE TITLE
OneXPlayer Fly F1 Support

### ISSUE THREAD

**Issue by Yoo-O** [Valkirie/HandheldCompanion#780]

**Comment by CasperH2O** [comment]
Hey @Yoo-O thanks for dropping in. We have not had the possibility yet to check the OneXFly device out yet.

**Comment by agusl88** [comment]
Hi! any updates on supporting the OneXFly?

**Comment by CasperH2O** [comment]
@agusl88 when available the HC team will be getting one through Droix to make HC compatible.

**Comment by CasperH2O** [comment]
OneXFly is being shipped, will be adding support shortly.

**Comment by CasperH2O** [comment]
Added support for the OneXFly device today, it's a really impressive device, totally underrated, would have bought it over the ROG Ally had I known. Next release it will be included.
