### ISSUE TITLE
Portable version / Headless install

### ISSUE THREAD

**Issue by leoncvlt** [Valkirie/HandheldCompanion#784]
Are there plans to release a portable version, or an headless option for the installer? I'm working on an automated setup/install script which I would like HC to be a part of, but it doesn't support GUI-based installers.

**Comment by CasperH2O** [comment]
There's nothing planned or in the works. We'd welcome it if you want to work on it?

**Comment by leoncvlt** [comment]
I'll have a look, all the dependencies are available on `winget` so a headless setup doesn't look like an impossible dream!

**Comment by CasperH2O** [comment]
@leoncvlt any insights? Do you need any more information?

**Comment by CasperH2O** [comment]
@leoncvlt I'm closing this one, as it's not planned. If you ever work on it or would like to make changes please come and discuss it with the development team (preferably up front).

**Comment by Barmaid1076** [comment]
a portable version would be great! then we can simply move the entire folder to another device without having to configure anything or download it again!
