### ISSUE TITLE
Can i use the USB IMU (GY-USB002)  device to play plane games?

### ISSUE THREAD

**Issue by Yoo-O** [Valkirie/HandheldCompanion#785]
I saw someone use it to play Forza horizon 5 mapping the gyro to left stick. But I don't know if the up and down direction are effective, if they are, I can use it in plane games, like ace combat.

**Comment by CasperH2O** [comment]
Hey @Yoo-O .

HC supports the USB IMU (GY-USB002). I'm working on a video for the YouTube channel, just plug it in and it should work.

HC does not support airplane games, with steering in both pitch and yaw direction so to speak. We have an open ticket to work on this: https://github.com/Valkirie/HandheldCompanion/issues/100

**Comment by Yoo-O** [comment]
> Hey @Yoo-O .
> 
> HC supports the USB IMU (GY-USB002). I'm working on a video for the YouTube channel, just plug it in and it should work.
> 
> HC does not support airplane games, with steering in both pitch and yaw direction so to speak. We have an open ticket to work on this: #100

Thanks for the reply. Glad to see this feature in the future.

**Comment by CasperH2O** [comment]
Duplicate, see #100.
