### ISSUE TITLE
Constant drift of the GYRO on Ayaneo 2

### ISSUE THREAD

**Issue by phush0** [Valkirie/HandheldCompanion#787]
**Device manufacturer**
- [X] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
Ayaneo 2

**Handheld Companinion Version**
0.18.0.3

**Describe the bug**
When enable virtual Dual Shock 4 and use it in steam for gyro, when press gyro enable button and not moving device, there is constant diagonal downward movement

**To Reproduce**
1. Enable virtual Dual Shock 4
2. In steam enable gyro to joystick (all modes are affected this one is for simplicity)
3. set enable button
4. in game of choice press enable button

**Expected behavior**
Cursor should not move

**Comment by CasperH2O** [comment]
Hey @phush0 let's rule out it's a Steam thing. Do you also have this problem if you only use HCs mouse gyro? It seems best to rule out it's a sensor, HC or Steam issue.

**Comment by phush0** [comment]
Hi, tested with HC settings and there is no drift at all.

**Comment by phush0** [comment]
Tried with motion assistant effect is same with drift, have to try with external controller to confirm or eliminate steam problem

**Comment by CasperH2O** [comment]
@phush0 I'm closing this ticket as it doesn't seem to be an HC issue. If you need help with settings feel free to reopen.
