### ISSUE TITLE
No vibration in starfield or double inputs if xinputplus inject/redirect

### ISSUE THREAD

**Issue by azodev** [Valkirie/HandheldCompanion#791]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ x] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
ALLY Z1 Extreme  (MCU 313)

**Handheld Companinion Version**
0.18.0.3

**Describe the bug**
no vibration in starfield with HC on. When enabling xinputplus inject or redirect, vibration is on BUT it gives double inputs (you can see it with dpad on menus) 
Vibration is also ok with HC closed

**To Reproduce**
1. Start HC (on boot or not)
2. Launch Starfield (steam version) , load game
3. fire any gun, 
4. no vibration.

**Expected behavior**
Vibrations to work as expected

**Screenshots**
none

**Logs file**
none

**Comment by CasperH2O** [comment]
@azodev this is an odd one, can you confirm you only have this with this game or with all games? 

Which setting do you have for:
- Emulated controller type
- Profile controller settings

**Comment by azodev** [comment]
Hi,
Steam input completly disable (always)
Xbox 360 emulated controller
Test 1: no viibration

- Access to phisical controller : no
- Xinput : disabled

Test 2: vibration but double inputs 

- Access to phisical controller : yes
- Xinput : disabled

Test 3: vibration but double inputs 

- Access to phisical controller : yes
- Xinput : injection

Test 4: vibration and no double inputs (seems ok but I don't know but this mode imply for HC controller management)

- Access to phisical controller : no
- Xinput : redirection

So it seems that redirection mode seems ok for Starfield.

In cyberpunk Access to phisical controller was enough to get vibration working.

**Comment by CasperH2O** [comment]
@azodev glad you found a configuration that works. Regrettably this is sometimes needed. Please note that you do not have to use the virtual controller unless you want to use HCs remapper or gyro functionality.

**Comment by azodev** [comment]
Actually I use the virtual controller for the per profile deadzone/anti-deadzone, mostly, and also for the button remap in certain case/
can I disable the virtual controller per profile?
