### ISSUE TITLE
Manual profile switching

### ISSUE THREAD

**Issue by dkswedens** [Valkirie/HandheldCompanion#792]
**Is your feature request related to a problem? Please describe.**
Not being able to change profile hinders me and my son to play the games we want, some of our games are via geforce now and local gamestreaming and not every game is gamepad compatible and since we cannot change profile we have to avoid games that doesnt support gamepad via gfn and other services.

**Describe the solution you'd like**
Personally I would like a feature similar to how TDP -+ is on quick access menu, allow of to bind a custom keybind/s so we can cycle back and forth.
And I would also personally like to have nested profiles so you can have a profile under a main profile.
So you dont have so cycle between all profiles you have.

**Comment by CasperH2O** [comment]
Identified use cases:
- Emulators with different games
- Gefore Now, playing different games

Although the default profile could be (ab)used for this, by changing it per game and not creating a profile for said app, that defeats the whole purpose of having profiles to begin with.

Could possible need:
- Do not automatically switch option
- Some ability to select a profile

**Comment by dkswedens** [comment]
Manual profile switching is what I want added. Using steam has its own hiccups.

**Comment by CasperH2O** [comment]
This has been implemented through the usage of sub profiles, including the requested hotkeys. Happy gaming!
