### ISSUE TITLE
PS4 controller connection and built-in controller vibration problem with AOKZOE A1L

### ISSUE THREAD

**Issue by Syades** [Valkirie/HandheldCompanion#794]
**Device manufacturer**
- AOKZOE

**Device model**
AOKZOE A1L

**Handheld Companinion Version**
0.18.0.3

**Describe the bug**
1. When connected to the PS4 controller, click the connect or unhide button in Controller -> Input devices, and it will load forever and the PS4 controller is unable to use;
2. When starting the handheld companion, there is a chance to cause the built-in controller to vibrate forever, manually adjusting the vibration strength will stop it immediately.

**To Reproduce**
For bug 1: just connect a PS4 controller to the device (AOKZOE A1L), and click connect or unhide, the problem will be seen right away;
For bug 2: start the handheld companion, sometimes the built-in controller starts vibrating and won't stop.

**Expected behavior**
The PS4 controller should work fine when connected to the device, the non-stop vibration issue with the built-in controller needs to be solved.

**Screenshots**
![Handheld Companion (0 18 0 3) 2023_10_14 11_42_36](https://github.com/Valkirie/HandheldCompanion/assets/86201272/4112df76-cf9b-455a-87c3-6d758a81357c)

**Logs file**
[HandheldCompanion-20231014.log](https://github.com/Valkirie/HandheldCompanion/files/12902197/HandheldCompanion-20231014.log)

**Comment by Valkirie** [comment]
Thanks for raising the issue. You'll be glad to know all those issues are fixed in forthcoming early access build.

**Comment by CasperH2O** [comment]
@Syades what does the L stand for in AOKZOE A1L ? Is this a new version?

**Comment by CasperH2O** [comment]
The connection problem has been fixed in 0.19. The endless vibration on Aokzoe and OneXPlayer devices has a ticket here: #818
