### ISSUE TITLE
Layout Remapper option, DS4 trackpad to button click 

### ISSUE THREAD

**Issue by Zain634** [Valkirie/HandheldCompanion#799]
Implement the ability to change ds4 trackpad to button click so we can open maps on battle royales (handheld with no trackpad) Example: pressing the Xbox map button to make a click on the ds4 trackpad,

**Comment by CasperH2O** [comment]
Implemented, albeit some UI bugs might not show the buttons correctly. Has to be double checked after MVVM refactor.
