### ISSUE TITLE
0.18.0.5 is Completely Broken With ASUS ROG Ally

### ISSUE THREAD

**Issue by anzenchitai** [Valkirie/HandheldCompanion#805]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [*] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
ASUS ROG Ally

**Handheld Companinion Version**
0.18.0.5

**Describe the bug**
Latest version is completely broken. None of my buttons work. RTSS and HWINFO won't launch on start with HC.

**To Reproduce**
1. Install HC 0.18.0.5
2. Reboot the OS.

**Expected behavior**

**Comment by anzenchitai** [comment]
Had to install the armory crate for the meanwhile. Instant regret. The ally is filled with chinese bloatware. Even the drivers are chinese made and bloated. Reinstalled w11 and latest HC. So the problems are:

RTSS and HWinfo doesn't launch on start.
Back paddles still don't work.
Buttons 3 and 4 don't work.

Everything else seems to be fine for now. But please remove the ally from supported devices list until it really is properly supported. Also, we would appreciate RGB controls for ally. Best regards.

**Comment by CasperH2O** [comment]
HC 0.18.0.5 works fine on my Ally, except for the backbuttons (M3 and M4), this is being investigated as there were some changes in the recent firmware (331) from ASUS.

RGB controls are coming in the next release, including ambilight effect.

Glad to read the rest of the software works for you.
