### ISSUE TITLE
Rog Ally OEM Keys not working

### ISSUE THREAD

**Issue by kennedyoliveira** [Valkirie/HandheldCompanion#809]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [X] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
RCL7

**Handheld Companion Version**
0.18.0.5

**Describe the bug**
After updating from 0.18.0.3 to 0.18.0.5 the back pedals and armory crate/control keys are not working, I can't add it to hotkeys, can't change its behavior in any profile

**To Reproduce**
1. Install version 0.18.0.5
2. Open the main window
3. Go to Hotkeys
4. Click in 'Press to define trigger'
5. Press any of the OEM keys (back paddle or armory crate/ctrl key)
6. Nothing happens

**Expected behavior**
Should register the key as hotkey

**Screenshots**
Not applicable as it will just not do anything.

**Logs file**
[HandheldCompanion-20231029.log](https://github.com/Valkirie/HandheldCompanion/files/13199658/HandheldCompanion-20231029.log)

The keys itself works outside of handheld companion, like if I start the asus services it will work, if set custom behavior in G-Helper application it does work, only stopped working in handheld companion.

**Comment by kennedyoliveira** [comment]
Rolled back to 0.18.0.3 now it works as expected.

**Comment by CasperH2O** [comment]
@kennedyoliveira have you updated to the latest ROG Ally firmware? HC had to be updated to work with that.

**Comment by kennedyoliveira** [comment]
@CasperH2O yes, I'm on the latest firmware 331, but the old  HC version 0.18.0.3 does work with the latest firmware just the newer ones that do not.

**Comment by k-trahan** [comment]
Having the same issue with the OEM keys on the Ally not working on 0.18.0.4 or 0.18.0.5.

To make sure I have all available updates installed, I re-enabled all ASUS services and verified every available update has been installed in both MyASUS and in Armoury Crate SE. I'm also running BIOS 331. In addition, I made sure I have all Windows Updates installed and all apps updated in the Microsoft Store.

After disabling the ASUS services again and rebooting multiple times, the hotkeys still do not work in 0.18.0.5. I do notice that with the "ASUS Optimization" service running the OEM keys are mappable as hotkeys again and do work however in 0.18.0.3 this was true without any ASUS service running.

**Comment by codevski** [comment]
Same here, trying to assign OEM left button to show tooltip nothing gets registered, but holding that button gives me (alt + ctrl + del) so the button def works and being registered but HC just isn't detecting it.... Also rear buttons used to open up touch pads (still set in settings) but HC cant detect it.

**Comment by Valkirie** [comment]
Fixed with 0.18.0.6: https://github.com/Valkirie/HandheldCompanion/releases/tag/0.18.0.6
