### ISSUE TITLE
X1 / X2 Button on OneXPlayer 2 Pro in Volume Mode

### ISSUE THREAD

**Issue by NightHammer1000** [Valkirie/HandheldCompanion#813]
Setting the EC Address 0xEB to 0xEB switches the X1 and X2 Keys to Volume Control in addition to setting the Turbo to Hotkey mode.

Would it be Possible to Integrate that functionality?

**Comment by CasperH2O** [comment]
@NightHammer1000 I don't fully understand your request. Currently HC already sets some EC addresses to make the Turbo button into a hotkey. Aren't the X1 and X2 already the volume control by default?

**Comment by NightHammer1000** [comment]
Nope. They are still in OnScreen Keyboard and Show desktop Mode-
Thats the Mode when you set the EC Address to 0x40.
This only switches the Turbo Button.

On my 2 Pro it is that way at least-

**Comment by CasperH2O** [comment]
Ah, it's unfortunate that those are the default's. The code is here: https://github.com/Valkirie/HandheldCompanion/blob/3f1844bcac22f4fb415187c55a3e7f09b4bad283/HandheldCompanion/Devices/OneXPlayer/OneXPlayer2.cs#L69

Are you skilled with Visual Studio? You can adapt the code and do a PR?

**Comment by NightHammer1000** [comment]
Will try if that works later.
Will do an PR later.

**Comment by Valkirie** [comment]
Confirmed working and implemented on forthcoming EA. Thank you !

**Comment by NightHammer1000** [comment]
Ohh. Nice. Thanks!
