### ISSUE TITLE
Uninstalling HC and or HidHide results in total lose of input device function

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#817]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [x] ONEXPLAYER
- [ ] VALVE
- [x] LENOVO

**Device model**
Observed with Lenevo Legion Go (2x) and OneXPlayer 2 (1x).

**Handheld Companinion Version**
0.19.0.2 and 0.19.0.2 Legion Go beta

**Describe the bug**
Several users on Discord have reported that upon uninstallation of HC through the Windows uninstaller (regular process) that all HID type devices stop working, controllers, mouse, touch screen, bluetooth keyboard and mouse, wired keyboard and mouse.

Current recovery procedures are either:
- Check device manager, enable disabled HID devices (if you a form of input that does work)
- Install new Windows OS, drivers etc
- https://docs.nefarius.at/projects/HidHide/fixing-a-bricked-system/ (unverified)

**To Reproduce**
1. Uninstall HC, including HidHide

**Expected behavior**
HID devices should remain functional

**Logs file**
Unable access.

**Comment by CasperH2O** [comment]
Initial investigation has been done by @nefarius and @Valkirie but issue has proved to be not easily reproducible.

**Comment by NightHammer1000** [comment]
I could recover by reinstalling HIDHide. Still had access over Rustdesk.
Had to Reinstall, Disable Device Hiding and than it worked again.

**Comment by nefarius** [comment]
Can't reproduce. [Manual correction of the issue is documented here](https://docs.nefarius.at/projects/HidHide/fixing-a-bricked-system/).

**Comment by CasperH2O** [comment]
@nefarius if one were to be able to consistently reproduce this issue, what should we check/verify/log in order to come up with an idea of what is going on?

**Comment by nefarius** [comment]
> @nefarius if one were to be able to consistently reproduce this issue, what should we check/verify/log in order to come up with an idea of what is going on?

I **assume** that the setup doesn't remove the `UpperFilters` values, when uninstalling and **before** the reboot, the registry needs to be checked. Other than that there is no logging in the setup that could be of help.

**Comment by CasperH2O** [comment]
@nefarius thank you. No, HC "simply" runs the HidHide uninstaller, we don't do anything specifically with the register. 

@Valkirie I'm thinking we have two options at this point:
1. Remove uninstalling of HidHide from the HC uninstaller and have users do it themselves if they want to.
2. The uninstaller checks and corrects the registry entries.

I don't like either and I don't feel comfortable coding number 2. What do you think?

**Comment by nefarius** [comment]
> @nefarius thank you. No, HC "simply" runs the HidHide uninstaller, we don't do anything specifically with the register.

I mean my own setup, the HidHide setup 😉

**Comment by nefarius** [comment]
I can skim over the setup project again, maybe something with executing the Custom Actions that take care of cleaning up the registry silently broke in an Advanced Installer update, by now I do not trust this product any further than I can throw it...

**Comment by nefarius** [comment]
What you also could do to help is; when executing the removal, add `/L*V .\install.log` to the process and collect the generated log file, hopefully it captures whatever silently fails.

**Comment by nefarius** [comment]
If an affected user can then retry/reproduce it with this method in place, I can analyze the log file. Other than that we're flying pretty dark I'm afraid.

**Comment by nefarius** [comment]
> Was thinking for possible further debug an app that logs/monitors all changes done during an install/uninstall could perhaps be used like Ashampoo Uninstaller (https://www.ashampoo.com/en-us/uninstaller)

Not recommended to involved any of this 3rd party nonsense, see my remark about generating a log.

**Comment by NightHammer1000** [comment]
![image](https://github.com/Valkirie/HandheldCompanion/assets/1979250/0b8f404c-e388-4c48-a527-6eb6c604038b)
@nefarius 
This is the State of all HID Devices after you trigger the bug.
Seems like something in the Service Dependency Config goes haywire.

**Comment by NightHammer1000** [comment]
Trying to Replace a Driver results in this Error:
![image](https://github.com/Valkirie/HandheldCompanion/assets/1979250/e461133e-a92d-4fee-aec0-cd187ef4d8e8)

**Comment by NightHammer1000** [comment]
The Moment I reinstall HidHide i can just disable and enable the failed devices and they work again.
Putting more weight on the Service Dependency Theroy.

**Comment by CasperH2O** [comment]
> /L*V .\install.log

@nefarius it seems @NightHammer1000 can reproduce the issue pretty at will. You mention the addition of above snippet, where would this needed to be added, in the uninstaller?

**Comment by nefarius** [comment]
> > /L*V .\install.log
> 
> @nefarius it seems @NightHammer1000 can reproduce the issue at will. You mention the addition of above snippet, where would this needed to be added, in the uninstaller?

The official MSI, yeah.

**Comment by nefarius** [comment]
> ![image](https://private-user-images.githubusercontent.com/1979250/290787491-0b8f404c-e388-4c48-a527-6eb6c604038b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NDE0MDksIm5iZiI6MTcwMjY0MTEwOSwicGF0aCI6Ii8xOTc5MjUwLzI5MDc4NzQ5MS0wYjhmNDA0Yy1lMzg4LTRjNDgtYTUyNy02ZWI2YzYwNDAzOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTE1MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDc0MzQ5MzhlNmJmNzJmMTE0NjI2MGFmODAwN2YzODUwYjhmMjA2YWRjODg4OTJmNTIzODY0ZGU5MzQyYTQ5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l4fNgxzR3mINomV88KmLb7JsulTLgfJ0l2bk2HSMmXU) @nefarius This is the State of all HID Devices after you trigger the bug. Seems like something in the Service Dependency Config goes haywire.

I know the error. We do not know **why**.

**Comment by nefarius** [comment]
> Trying to Replace a Driver results in this Error: ![image](https://private-user-images.githubusercontent.com/1979250/290788296-e461133e-a92d-4fee-aec0-cd187ef4d8e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NDE3NTQsIm5iZiI6MTcwMjY0MTQ1NCwicGF0aCI6Ii8xOTc5MjUwLzI5MDc4ODI5Ni1lNDYxMTMzZS1hOTJkLTRmZWUtYWVjMC1jZDE4N2VmNGQ4ZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTE1NzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg3OTVhOWVlZjM4ZDUzMmNkOTBkODI2MjZmYWFjN2MxYWVmZGMyN2VmOTkzNTY1YTkxZmM5MTNiZTY5MDM2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tB9fPovYc0aWOdLJSEZ3lrFVMRpH6ALmyR_nLDj5drE)

This will never succeed until the UpperFilters entry of HidHide is cleaned up. The setup is supposed to do that, we need to figure out **why** it apparently does not for some. Provide a log and maybe we finally see why.

**Comment by NightHammer1000** [comment]
Will try. I can reproduce it now just fine. Will post one later today.

**Comment by nefarius** [comment]
Also for those affected and are not aware of it: [how to recover from this manually](https://docs.nefarius.at/projects/HidHide/fixing-a-bricked-system/).

**Comment by CasperH2O** [comment]
Managed to create a log of HidHide uninstalling (succesfully). The following changes were required to the HC inno setup file:
- Product code was outdated
- Add log arguments, note, don't let the log write to a folder that does not yet exists, this results in issues

From:
`if(ShellExec('', 'msiexec.exe', '/X{BE49B9DE-F8EB-4F54-B312-DD4B601985FC}', '', SW_SHOW, ewWaitUntilTerminated, resultCode)) then  
`

To:

`if(ShellExec('', 'msiexec.exe', '/X{BE49B9DE-F8EB-4F54-B312-DD4B601985FC}', '', SW_SHOW, ewWaitUntilTerminated, resultCode)) then  
`

I have made a test build for HC with this change, if someone who can reproduce the issue can install it, then uninstall it to create the log that would be great.

**Comment by tylergibson** [comment]
> Also for those affected and are not aware of it: [how to recover from this manually](https://docs.nefarius.at/projects/HidHide/fixing-a-bricked-system/).

These instructions do not work.  My device is softbricked from trying to upgrade from 0.19.1.5 to 0.20.3.0

When uninstalling HidHide, no usb connectivity works, and there are no registry keys found with the above link - following to the letter.  I cannot reinstall HidHide through recovery because its bundled inside the HC installer which wont install in cmdline recovery mode.  I cant launch safe mode because all USB devices are disabled.

There are 0 warnings anywhere that you can literally softbrick your device (ROG Ally) by installing HC.

**Comment by CasperH2O** [comment]
Hey @tylergibson , it saddens me to hear you are experiencing this issue and recovering does not seem possible through the instructions. 

HidHide can be obtained separately here: https://github.com/nefarius/HidHide/releases/download/v1.4.192.0/HidHide_1.4.192_x64.exe

I'll make it a priority to default the HidHide uninstall to off in the HC uninstaller and adding a warning when the toggle is ticked. In addition to adding the additional logging.

Please note there is no need to uninstall HC when updating to a newer version, you can install "over" it.

**Comment by NightHammer1000** [comment]
@tylergibson 
If you get it to work again, would you care to tell me your Windows Version?
On a Keyboard Press `WIN+R` and type in `winver` and post a Screenshot of the Windows Version.

I wasn't able to reproduce the Issue after a certain Windows Build. Would like to confirm my suspicion and maybe even install your Build Version and try if I can trigger it again to get some logs.

**Comment by nefarius** [comment]
> > Also for those affected and are not aware of it: [how to recover from this manually](https://docs.nefarius.at/projects/HidHide/fixing-a-bricked-system/).
> 
> These instructions do not work. My device is softbricked from trying to upgrade from 0.19.1.5 to 0.20.3.0

This guide works a 100%, make sure when you're in in WinPE mode to **select the correct disk/partition**.

> There are 0 warnings anywhere that you can literally softbrick your device (ROG Ally) by installing HC.

Bugs like these are not intentional, hence not documented. Filter drivers are **always** risky, that's inherent to the technology. Follow the guide *correctly* and everything will work again.

**Comment by CasperH2O** [comment]
@nefarius here we go, we have a log of a failed uninstall and for good measure of a correct uninstall. I have already taken the liberty of diffing them, but I have no idea what I'm looking at. Hopefully it makes more sense to you.

Attached files.

[HidHide-Uninstall-fail.log](https://github.com/Valkirie/HandheldCompanion/files/14120662/HidHide-Uninstall-fail.log)
[HidHide-Uninstall-succes.log](https://github.com/Valkirie/HandheldCompanion/files/14120664/HidHide-Uninstall-succes.log)

May I ask you to have a look?

**Comment by nefarius** [comment]
@CasperH2O well this sucks. I reviewed them, thanks for that. However all the class filter removal steps are called and returned successfully, so now I have even less of an idea what's going on.

**Comment by nefarius** [comment]
A theory I have; a race condition with the watchdog service. I condensed the logs in the order that could hint at the problem:

```
MSI (s) (7C:EC) [19:25:30:394]: Doing action: RemoveClassHID
Action start 19:25:30: RemoveClassHID.
Action ended 19:25:30: RemoveClassHID. Return value 1.
MSI (s) (7C:EC) [19:25:30:566]: Executing op: ActionStart(Name=RemoveClassHID,,)
MSI (s) (7C:EC) [19:25:30:566]: Executing op: CustomActionSchedule(Action=RemoveClassHID,ActionType=1106,Source=C:\Program Files\Nefarius Software Solutions\HidHide\x64\nefconw.exe,Target=--remove-class-filter --position upper --service-name HidHide --class-guid 745a17a0-74d3-11d0-b6fe-00a0c90f57da,)
MSI (s) (7C:EC) [19:25:31:966]: Executing op: ServiceControl(,Name=HidHideWatchdog.exe,Action=2,Wait=1,)
```

If what I see here I understand correct is as follows:
- The watchdog service is always running, as per design
- The setup executes the filter removal steps successfully
- The still running service detects that the driver files are still there, however the filter entries are absent, therefore reinstates them
- Setup continues with the logic, arriving at the service stop and removal actions
- Setup finishes all tasks successfully, however the registry is now in a broken state due to outlined race condition

This would explain why only a handful of people are affected; it is an extremely timing-sensitive bug. I don't think I can manipulate the execution order of the setup so I need to think of a workaround. This is our best shot IMHO.

**Comment by Valkirie** [comment]
@nefarius I always love a good race condition before the weekend.

**Comment by CasperH2O** [comment]
@nefarius glad to hear the log helped and you have found something worth while to investigate.

My idea for a workaround (ie not a proper solution) would be to check the registry values at the end of the uninstall and set them to the correct values.

**Comment by nefarius** [comment]
> My idea for a workaround (ie not a proper solution) would be to check the registry values at the end of the uninstall and set them to the correct values.

I do not have control over the order of events, what I could do though is add another custom action to stop the watchdog service before the filter removal steps.

**Comment by nefarius** [comment]
Took a bit of tinkering and adding more logging but I think we're on the right track here:

![image](https://github.com/Valkirie/HandheldCompanion/assets/286631/9381e05d-6582-4498-b12f-bf21335ec3c6)

**Comment by nefarius** [comment]
@CasperH2O managed to reproduce it today, it is indeed a race condition with the watchdog service during removal:

![image](https://github.com/Valkirie/HandheldCompanion/assets/286631/58629fa7-ea55-497b-b8d3-fed852c1c06d)

**Comment by nefarius** [comment]
[Fixed release is up](https://github.com/nefarius/HidHide/releases/tag/v1.4.202.0), happy testing.

**Comment by CasperH2O** [comment]
With great reliëf I can state this issue has been fixed. While painful for those who have been affected and those we could not reach with the recovery instructions are least it wont happen anymore in the future.

Note that updating to the new version can still cause this issue when a system is rebooted during the update as it will uninstall the bugged version of HidHide still. Decline the midway reboot request and reboot at the end.

**Comment by nefarius** [comment]
You can also run this PowerShell snippet **before starting the uninstall/upgrade:**

```PowerShell
Stop-Service HidHideWatchdog.exe
```

And you'll be OK.

**Comment by NightHammer1000** [comment]
@CasperH2O maybe add the `Stop-Service HidHideWatchdog.exe` to the Uninstaller right before uninstalling HIDHide.

**Comment by Valkirie** [comment]
> > @tylergibson If you get it to work again, would you care to tell me your Windows Version? On a Keyboard Press `WIN+R` and type in `winver` and post a Screenshot of the Windows Version.
> > I wasn't able to reproduce the Issue after a certain Windows Build. Would like to confirm my suspicion and maybe even install your Build Version and try if I can trigger it again to get some logs.
> 
> I was forced to reimage the Ally.

It suxx but thanks to users reports, the issue was finally sorted. Once everyone has transitioned to the new release this issue will be forever gone.
