### ISSUE TITLE
No fan control for AYANEO 2021

### ISSUE THREAD

**Issue by tiagofassoni** [Valkirie/HandheldCompanion#824]
**Device manufacturer**
- [x ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
AYANEO 2021

**Handheld Companinion Version**
0.18.0.5

**Describe the bug**
Installed HC on my AYANEO 2021 and no options about the fans show up. Is it a limitation of the device? (also, amazing project, loved it). If the problem is the lack of an AYANEO 2021 to develop, is there any way I can help or any path for me to fix the issue?

Thanks.

**Comment by CasperH2O** [comment]
Hey @tiagofassoni , yes, there is no known way to control the fans for the 2021 series. I own one myself, it's my dedicated HC development machine. Ayaspace itself does not have fan control for this device either to my knowledge.

**Comment by tiagofassoni** [comment]
Wow, thanks for the super fast response. One follow-up question: what do the fan settings in ayaspace for that device actually do? They have some weird names, and one definitely spins up the fan

(please note, this is just my curiosity, I fully trust you know what you are saying)

**Comment by CasperH2O** [comment]
@tiagofassoni to the best of my knowledge that is implicitly done through some device power profile. That does not however, allow us the do fan control at say a certain manual speed. 

It's good to be curious! 

Closing ticket, questions answered.
