### ISSUE TITLE
HC 0.19.02-Beta3 sets proqfreqmax to 3900mhz no matter what.

### ISSUE THREAD

**Issue by gennro** [Valkirie/HandheldCompanion#828]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [X ] LENOVO

**Device model**
Legion Go

**Handheld Companinion Version**
0.19.02-Beta3

**Describe the bug**
HC changes proqfreqmax  to 3900mhz everytime you change a window no matter wheather it is set in the performance profile or not. I Deleted the CPUOverrideValue/Enabled from the default.json and it still does it confirmed via powercfg and HC log.

**To Reproduce**
Have HC running and change any window and watch it set proqfreqmax to 3900mhz

**Expected behavior**
Not limit CPU to 3900mhz

**Screenshots**
![image](https://github.com/Valkirie/HandheldCompanion/assets/3684917/52799f5d-db0d-4f25-8138-d615a429c210)
![image](https://github.com/Valkirie/HandheldCompanion/assets/3684917/75e6276e-8d6c-40b2-946f-75536952c8e0)

**Logs file**
If applicable, add logs file stored in your install location, logs folder.
[HandheldCompanion-20231114_001.log](https://github.com/Valkirie/HandheldCompanion/files/13359974/HandheldCompanion-20231114_001.log)

**Comment by CasperH2O** [comment]
Can confirm, there was a hardcoded 3900 Hz from a development phase left in the code. It has since been removed. Will be included in next release.
