### ISSUE TITLE
Hotkey to show/hide On Sceen Display (OSD)

### ISSUE THREAD

**Issue by ibrahimqatar** [Valkirie/HandheldCompanion#829]
**Is your feature request related to a problem? Please describe.**
Since I disabled AC, I cannot show Rog Ally’s default overlay to show wattage consumption, fps, etc.

**Describe the solution you'd like**
The feature is to have a hotkey to show and hide the overlay

**Describe alternatives you've considered**
a quick action button to show overlay

**Additional context**
-

**Comment by CasperH2O** [comment]
A hotkey to hide/show the OSD or perhaps cycle through the current selection of 5 options.

**Comment by ibrahimqatar** [comment]
My request was actually to show Rog Ally's stock overlay..

**Comment by CasperH2O** [comment]
Hotkey to toggle the OSD on/off has been implemented by @cerahmed in Valkirie/HandheldCompanion-EA#137, thank you!
