### ISSUE TITLE
TDP settings not applying correctly

### ISSUE THREAD

**Issue by gmartins-henrique** [Valkirie/HandheldCompanion#831]
**Device manufacturer**
- [x] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [ ] LENOVO

**Device model**
Aya Neo 2s

**Handheld Companinion Version**
0.19.0.2

**Describe the bug**
TDP settings for profile do not apply on startup.
FAN settings start on boot, then completly shuts down, fan does not spin at all, ignoring even hardware settings

**To Reproduce FAN**
1. Set up a profiles with software fan control, and set HC to autostart
2. Restart the device
3. On startup, the fan will spin for 1sec, then stop completly, even ignoring hardware settings.

**Expected behavior**
FAN should spin at the speed defined in the profile, or at least spin via hardware definition.

**To Reproduce TDP**
1. Set up 2 TDP profiles Ex.: one at 10w, and another at 18w
2. Set these 2 profiles for different games that uses more than the defined tdo (to see it go past the setting)
3. open both of these games and check the tdp on the overlay

**Expected behavior**
TDP should be locked at maximum of the profile definition.

**Steps I took to kinda fix it**
Usually I restar HC sometimes to make all of the settings work, restarting sometimes makes the FAN setting work as defined, but TDP only works by opening the quick menu, and toggling the tdp/autotdp limit on and off sometimes until it works.

**Comment by gmartins-henrique** [comment]
[HandheldCompanion-20231117.log](https://github.com/Valkirie/HandheldCompanion/files/13393691/HandheldCompanion-20231117.log)
![rn_image_picker_lib_temp_90e0ebd7-1085-4fd9-9488-fd769f633c73](https://github.com/Valkirie/HandheldCompanion/assets/13962266/e90a9a87-ef07-4f83-9e6d-2ae78973fdfc)
![rn_image_picker_lib_temp_b8466895-b528-413c-9336-08258c0cee8d](https://github.com/Valkirie/HandheldCompanion/assets/13962266/ca6f58a7-f636-4d00-9013-fd8c3d9a5fe7)

**Comment by gmartins-henrique** [comment]
![image](https://github.com/Valkirie/HandheldCompanion/assets/13962266/8526c56b-4835-45b0-935e-f899ae5a0b15)
Chaging this setting makes it so the profiles maxes out at 20w instead of 30w, so it might be pulling the value from this setting instead of the profiles json.

**Comment by gmartins-henrique** [comment]
Changing tdp using hotkeys as such:
![image](https://github.com/Valkirie/HandheldCompanion/assets/13962266/8b030395-b5f1-41ab-be4e-8f6ffbeda699)

Also does not work, need to open que quick menu settings, and change the tdp on the profile up/down, then ot does apply correctly.

**Comment by CasperH2O** [comment]
Checked remotely. The fan does work, the TDP adjustment does not work until it is changed in the settings through QT. Main GUI TDP adjustment or hotkey does not seem to take.

**Comment by CasperH2O** [comment]
Fixed, TDP was not applied when software fan control was enabled die to wrong placement of return statement.
