### ISSUE TITLE
Onexfly 0.19.0.3 (beta5) Bugs

### ISSUE THREAD

**Issue by survivalizer** [Valkirie/HandheldCompanion#832]
**Device manufacturer**
- [X] ONEXPLAYER

**Device model**
OneXFly

**Handheld Companinion Version**
0.19.0.3 (beta5)

**Describe the bug**
Fan Control - The fan curve doesn't appear to be functioning as intended, noticing some inconsistent behavior where the profile does not function or all or seems to read the temp at 0 resulting in only the first point of the fan curve being accounted for.
Haptic Feedback - Upon fresh installation, the haptic motor seems to kick on and remains on until the slider for intensity is adjusted. Additionally, it appears the intensity slider does produce a out of ordinary haptic feedback making it feel inconsistent or damaged in nature when used but, seems to function properly using onxconsole.

**To Reproduce**
1. Upon installation the strange haptic behavior is immediate as soon as the controller becomes connected.
2. The Fan control steps are just setting a manual fan curve of any format and don't seem to trigger any behavior

**Expected behavior**
Fan Control - Increased / decreased fan RPM activity based on temperature
Haptic Feedback - The slider should produce a consistent intensity increase based on incremental movement and shouldn't remain triggered upon fresh install.

**Comment by CasperH2O** [comment]
The vibration is a manufacturer issue for which the work around is to enable the vibration on connect tick on the Controller page.
The fan control works fine on my OneXFly, but I'll double check. Can you share a few screenshots of your performance profile and fan configuration?

**Comment by survivalizer** [comment]
Sounds good on the vibration motor. As far as the fan curve I've attached some screenshots even the defaults curves don't seem to result in any change in fan RPM, al tried at 100% across the board which didn't seem to work either.

![20231118_053510](https://github.com/Valkirie/HandheldCompanion/assets/51409646/6d028515-8072-41f4-8734-25cefb78d296)
![20231118_053539](https://github.com/Valkirie/HandheldCompanion/assets/51409646/d3859c15-7b9f-48b2-a63d-8c1032c4e122)
![20231118_053441](https://github.com/Valkirie/HandheldCompanion/assets/51409646/ae8e2b33-6092-4c0b-9e2a-008ffe42ecde)

**Comment by survivalizer** [comment]
A bit of follow-up, it has started to function but, only seems to be imp;acted by the curve at 0 degrees light it's not reading temps properly.
