### ISSUE TITLE
Detect Asus Rog Ally M1/M2 buttons as separate buttons

### ISSUE THREAD

**Issue by xaviergonz** [Valkirie/HandheldCompanion#836]
**Is your feature request related to a problem? Please describe.**
Armoury Create can detect and assign different actions to the M1 and M2 button if they are not set to "alt action" triggers.

**Describe the solution you'd like**
It would be great if HC could detect them as separate buttons to be able to assign them different actions.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by CasperH2O** [comment]
Already done, will be included in the next release.
