### ISSUE TITLE
Be able to use Asus Rog Allly M1/M2 buttons as chords

### ISSUE THREAD

**Issue by xaviergonz** [Valkirie/HandheldCompanion#837]
**Is your feature request related to a problem? Please describe.**
Armory Create allows you to set button combinations (e.g.) M1 + A to do something, M1 + X to do something else, etc.

**Describe the solution you'd like**
It would be great if HC could detect button combinations. I tried to press both buttons while assigning a shortcut but it didn't work.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by CasperH2O** [comment]
Has been implemented, next release includes split M1 M2 button input which can be used with other buttons for hotkey combo's.
