### ISSUE TITLE
Quick Switch for Emulated Controller

### ISSUE THREAD

**Issue by Bagboii** [Valkirie/HandheldCompanion#846]
I usually have the Problem, that I play both old and new games. XInput doesn't support Gyro, and DualShock isnt supported on many old Games, like GTA IV, or even GTA V (At least, in my Experience)

I'd request a tile to be made, which swaps from DualShock Emulation to XInput Mode. Hotkeyable and also pinnable to Quick Tools.

**Comment by CasperH2O** [comment]
This is being actively worked on, see #850.

**Comment by CasperH2O** [comment]
Has been implemented, will be included in the next EA release. A hotkey and pin quick icon will be available, along with a HID preference in profiles.
