### ISSUE TITLE
Setting up a manual GPU clock is not actually applied 

### ISSUE THREAD

**Issue by hpicard** [Valkirie/HandheldCompanion#851]
**Device manufacturer**
- [X] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [ ] LENOVO

**Device model**
Ayaneo 2

**Handheld Companinion Version**
0.18.0.6

**Describe the bug**
Enabling the manual GPU Clock Control doesn’t actually set the GPU clock the de desired frequency. 

**To Reproduce**
1. Go to Quick Menu Tool
2. Click on Profile and enable manual GPU Control and select a frequency
3. Open AMD Adrenaline panel and go to the performance tab. Here you can see that the GPU frequency is still on auto 

**Expected behavior**
The GPU frequency should be set to the selected value in the panel.

**Comment by CasperH2O** [comment]
Thanks for reporting in, this is a known issue, see: #599
