### ISSUE TITLE
Triggers (L2/R2 or LT/RT) not mappable as buttons/shoulders (L1/R1 or LB/RB) (or non-analog triggers)

### ISSUE THREAD

**Issue by DonutBling** [Valkirie/HandheldCompanion#852]
**Device manufacturer**
LENOVO

**Device model**
Legion Go 8APU1

**Handheld Companion Version**
0.19.0.6

**Describe the bug**
When choosing the category to assign to a buttons or shoulders the "Triggers" (L2/R2 or LT/RT) are greyed out and are not mappable as buttons/shoulders/non-analog triggers.

**To Reproduce**
1. Go to Profiles > Controllers
2. Click on "Buttons"
3. Choose LB or RB (L1 or R1), choose short press or long press
4. Try to either assign them the "trigger" category and it will be greyed out.  Try to assign the "button" category and LB/RB will be absent from the choices. 

**Expected behavior**
Assigning analog or digital trigger inputs as digital button/shoulder inputs.  I assume it needs a 0-100 to 0-1 conversion to be added to achieve this?

**Comment by CasperH2O** [comment]
Will check if this is indeed a bug, or simply a missing feature. Thank you for reporting in.

**Comment by CasperH2O** [comment]
This has been implemented (tested with HC 0.20.5.5), not sure when, but it's now doable with soft and full pull:

![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/50402260-15ed-4e86-91a5-1fe8a6688662)

Enjoy @DonutBling !
