### ISSUE TITLE
OSD - RTSS and HWiNFO not starting with HC

### ISSUE THREAD

**Issue by gmartins-henrique** [Valkirie/HandheldCompanion#858]
**Device manufacturer**
- [ x ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [ ] LENOVO

**Device model**
Aya Neo 2S

**Handheld Companinion Version**
0.19.1.0

**Describe the bug**
Overlay display level doesn't work on HC startup, because RTSS and HWiNFO are not starting with HC

**To Reproduce**
1. Set Overlay display level to any option besides "Disabled"
2. Restart PC
3. Notice that RTSS/HWiNFO do not start together with HC

**Expected behavior**
RTSS/HWiNFO starting together with HC depending on your option in Overlay display level

**Screenshots**
![image](https://github.com/Valkirie/HandheldCompanion/assets/13962266/cb187f06-3a0f-44d2-b1f6-1c03b251167b)

**Logs file**
[HandheldCompanion-20231204.log](https://github.com/Valkirie/HandheldCompanion/files/13548517/HandheldCompanion-20231204.log)

**Comment by gmartins-henrique** [comment]
Don't know if it's related, but FPS lock is also not working, you need to disable and reenable on the game profile

**Comment by gmartins-henrique** [comment]
FPS limit does not seem to be a OS level problem, tryed a CLEAN windows11 install, and the problem persists.

**Comment by CasperH2O** [comment]
This has been fixed in the EA repo, will be included in the upcoming release.
