### ISSUE TITLE
Install Fails with `404` Error

### ISSUE THREAD

**Issue by tsndr** [Valkirie/HandheldCompanion#859]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [x] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [ ] LENOVO

**Device model**
ASUS ROG Ally Z1 Extreme

**Handheld Companion Version**
0.18.0.6

**Describe the bug**
When installing the latest version of Handheld Companion, I'm getting a `404` error when the installer is trying to download `https://github.com/nefarius/ViGEmBus/releases/download/v1.21.442.0/ViGEmBus_1.21.4`, see the screenshot below.

**To Reproduce**
1. Download the latest installer of Handheld Companion [here](https://github.com/Valkirie/HandheldCompanion/releases/tag/0.18.0.6).
2. Run the installer exe-file.
3. Proceed through the installation steps, at some point it will fail with the `404` error.

**Expected behavior**
The installer finishes without any errors.

**Screenshots**
<img width="394" alt="Screenshot 2023-12-05 104917" src="https://github.com/Valkirie/HandheldCompanion/assets/2940127/7a4e061c-8a58-43a2-a7e7-c43bc76739ef">

**Comment by CasperH2O** [comment]
A fix has been committed to the public repo to restore availability of the files. @tsndr can you try installing again?

**Comment by tsndr** [comment]
Hey, thanks for looking into this so quickly :)

Do I have to compile the project to be able to test this, or is there an executable somewhere?

**Comment by thororen1234** [comment]
@tsndr you should just be able to run it from https://github.com/Valkyrie/HandheldCompanion/released/latest aka the newest available release on GitHub.

**Comment by thororen1234** [comment]
@tsndr you should just be able to run it from https://github.com/Valkirie/HandheldCompanion/released/latest aka the newest available release on GitHub.

**Comment by tsndr** [comment]
Can report, it's successfully installing now. Thank you :)

@thororen1234 I guess that's the theme here 😅
<img width="1095" alt="Screenshot 2023-12-05 at 11 20 30 PM" src="https://github.com/Valkirie/HandheldCompanion/assets/2940127/2a8da84e-aa2a-4933-a0e0-4e0b56c0246c">
