### ISSUE TITLE
GPD WIN MINI support

### ISSUE THREAD

**Issue by zl02655931** [Valkirie/HandheldCompanion#862]
GPD WIN MINI is the latest product of GPD, please support it，thank you

**Comment by Valkirie** [comment]
Hey, we don't have any in hands and GPD doesn't support HC whatsoever. If by any chance you have contacts within GPD, feel free to ask them to consider sending us a sample. Otherwise the Win Mini will be relatively low priority while we sort other devices like RogAlly and LegionGo.

**Comment by CasperH2O** [comment]
Initial WIN MINI support is incoming through EA. Initial features programmed, lacking now is fan control

**Comment by CasperH2O** [comment]
Added fan control. Support in next release.
