### ISSUE TITLE
Profile layout button remap selection does not feature current HID device

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#867]
**Handheld Companinion Version**
0.19.1.3

**Describe the bug**
Virtual controller type is set to Xbox 360, but layout remapper button selection shows DS4.

**Screenshots**

![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/9c27d3c6-0475-4ee7-93c6-a9ef64c58c74)

**Logs file**
If applicable, add logs file stored in your install location, logs folder.

**Comment by CasperH2O** [comment]
Theres still the bug that the UI is only partially updated when on the Layout page and the HID mode changes.

**Comment by Valkirie** [comment]
We might want to look into the call chain. We might be having a thread call to UI components, therefore an issue. Maybe we're missing a dispatcher call.

**Comment by CasperH2O** [comment]
@MSeys confirmed this is no longer an issue in the MVVM rework branch, will double check during testing.

**Comment by CasperH2O** [comment]
Fixed, tested virtual controller selection through profile and global. Dropdown selection is adjusted accordingly. Nice!
