### ISSUE TITLE
AYANEO2 LED state restored after charging device

### ISSUE THREAD

**Issue by CoryManson** [Valkirie/HandheldCompanion#876]
**Device manufacturer**
- [X] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [ ] LENOVO

**Device model**
AYANEO 2

**Handheld Companion Version**
0.19.1.4

**Describe the bug**
LED state/colour is restored after plugging in the device

**To Reproduce**
1. Turn LED off in HC
2. Plug device into charger, LED will enable and turn red to indicate charging
3. Disconnect device from charger, LED will stay enabled and turn blue

**Expected behavior**
Red LED charging status is nice to have, though I expected the LED to be disabled again after disconnecting from charger

**Screenshots**

**Logs file**
If applicable, add logs file stored in your install location, logs folder.

**Comment by CasperH2O** [comment]
Hey @CoryManson , im aware of this issue, there is some code in HC to fix this but it obviously doesnt work. Once I get my hands on an Ayaneo with LEDs I can fix it. 

https://github.com/Valkirie/HandheldCompanion/blob/980c2761c15d8bd6a9cb0128970dc9c9ff90001e/HandheldCompanion/Devices/AYANEO/AYANEODevice.cs#L31

**Comment by indiesaudi** [comment]
This is also happening with the Ayaneo Air 1S

**Comment by indiesaudi** [comment]
https://github.com/Valkirie/HandheldCompanion/pull/929
this change should solve the issue.

**Comment by CasperH2O** [comment]
Indeed, closing.
