### ISSUE TITLE
AYANEO2 Invalid LED Effects

### ISSUE THREAD

**Issue by CoryManson** [Valkirie/HandheldCompanion#877]
**Device manufacturer**
- [X] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [ ] LENOVO

**Device model**
AYANEO 2

**Handheld Companinion Version**
[0.19.1.4](https://github.com/Valkirie/HandheldCompanion/releases/tag/0.19.1.4)

**Describe the bug**
HC with AYANEO2 apparently only supports solid colour. When opening the dropdown for LED Effects many options are listed and there's no clear indication that they are unavailable apart from being unselectable.

**Expected behavior**
Only list what's available for the device

**Screenshots**
![20231212_215534](https://github.com/Valkirie/HandheldCompanion/assets/5052021/c4471e87-a04e-40de-be14-808c616c0de6)

**Comment by CasperH2O** [comment]
Seems this is missing from the device file:
`        DynamicLightingCapabilities |= LEDLevel.SolidColor;`

**Comment by CasperH2O** [comment]
Fixed and improved in EA branch.
