### ISSUE TITLE
Rog Ally front oem button outputs M2

### ISSUE THREAD

**Issue by dkswedens** [Valkirie/HandheldCompanion#879]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ X] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [ ] LENOVO

**Device model**
Asus rog ally

**Handheld Companinion Version**
newest release

**Describe the bug**
Right front oem button (long press) output M2

**To Reproduce**
bind long press watch output

**Expected behavior**
expectd output to be different than m2

**Screenshots**

**Logs file**
If applicable, add logs file stored in your install location, logs folder.

**Comment by CasperH2O** [comment]
It would appear that for the M1/M2 programming, there are "duplicate" values that have or do not have an effect on the AC long press button. For example both decimal 4 and decimal 64 result in F3.

Using decimal 8, reprograms AC Long and M2 to F13 but using Decimal 48 then only sets the M2 key back to F18.

Even stranger, setting M1/M2 to default, makes M1, M2 and AC Long have no input, but then setting M1/M2 to F17/F18 will have AC Long behave with F13 again.

A hack at this point would be to set F13 once for both and then F18 for only M2, which would prevent them from having the same value.

**Comment by CasperH2O** [comment]
Revisiting this one, it seems to be a firmware thing for which I have been unable to find a proper workaround. It is what it is. Closing as a won't fix.
