### ISSUE TITLE
Allow to set a minimum TDP when using auto TDP

### ISSUE THREAD

**Issue by Choukajohn** [Valkirie/HandheldCompanion#885]
When using auto TDP in a game which sometimes requires low ressources, the TDP drops to less than 10w and other background programs that require more power do not work properly.
For example, on ROG Ally, the microphone background noise filtering with AI doesn't work bellow 10w TDP.

Allowing the setting of a minimum TDP (in addition to the maximum limit) when using auto TDP would be great and solve the problem.

Thanks.

**Comment by CasperH2O** [comment]
In HCs main GUI, on the Device page, you can set the range of TDP (both upper and lower), you can try setting the lower TDP range to 10 Watt?

**Comment by Choukajohn** [comment]
Ho yes I didn't see this setting. I'll give it a try, thanks.

**Comment by CasperH2O** [comment]
Resolved, provided user with instructions.
