### ISSUE TITLE
UI Navigation functionality to allow for press and hold using dpad/ thumbstick 

### ISSUE THREAD

**Issue by pdarnellmuilman** [Valkirie/HandheldCompanion#888]
**Is your feature request related to a problem? Please describe.**
one must navigate and adjust values in the with a controller one value at a time.

**Describe the solution you'd like**
Request to change UI Navigation functionality to allow for press and hold using dpad/ thumbstick (for example, turning volume up and down, adjusting sliders with multiple values, etc.)

**Describe alternatives you've considered**

**Additional context**
Thanks for the consideration, and all the work you do. Thanks!

**Comment by CasperH2O** [comment]
Has been implemented and will be part of next release. Valkirie/HandheldCompanion-EA#139
