### ISSUE TITLE
Per Axis Gyro Sensitivity 

### ISSUE THREAD

**Issue by ModdingPink** [Valkirie/HandheldCompanion#889]
**Is your feature request related to a problem? Please describe.**
I'd like the left/right gyro sensitivity to be different than up/down so I can better rotate in mouse games

**Describe the solution you'd like**
An option called "Per Axis Sensitivity" that you can turn on which then duplicates the current set of options to be used per axis

**Comment by CasperH2O** [comment]
Hey @ModdingPink , this feature is already in HC, its here:

MainGUI, profile -> motion settings -> additional settings

![afbeelding](https://github.com/Valkirie/HandheldCompanion/assets/14330834/5c9e9245-aae6-4bba-bc67-3c0d547498c6)

It's also in QuickTools under motion settings.

**Comment by ModdingPink** [comment]
Oh, thanks! Apologies for not seeing this. 
Could this still be accessible within the "Gyro" layout here?
![image](https://github.com/Valkirie/HandheldCompanion/assets/62712899/61859062-d79a-47a5-bbcf-df3aa662e62a)

**Comment by CasperH2O** [comment]
You have to scroll a bit up and hit the additional settings button in the gyro motion settings container.

**Comment by CasperH2O** [comment]
Resolved, provided user with instructions.
