### ISSUE TITLE
Lenovo Legion Go - Bluetooth Controllers as Individual Controllers

### ISSUE THREAD

**Issue by ModdingPink** [Valkirie/HandheldCompanion#890]
**Is your feature request related to a problem? Please describe.**
I'd like to use each controller like joycon or wiimotes for simpler point and click games within Yuzu and Dolphin. This would also mean each controller has gyro support using the gyro in the controllers themselves.

**Describe the solution you'd like**
Create new controller profiles, theoretically allowing you to map one physical controller as if it was 2 or more. This would open the door for supporting more local multi games.

**Describe alternatives you've considered**
Just letting both controllers Gyro be useable within Software like Yuzu and Dolphin, as one controller can be mapped over multiple emulated gamepads, Gyro would be the only missing feature (which I mostly need). If there only being one gyro on a single controller is a limitation then the DSU cemuhook protocol like the steam deck could be used? https://github.com/kmicki/SteamDeckGyroDSU

**Comment by MSeys** [comment]
FYI, the controller gyros are not accessible to us (yet). It will depend on Lenovo.

**Comment by ZarifS** [comment]
Hi, wondering if Gyros are accessible yet and if this feature is possible? Would be dope to use the 2 controllers separately like Joycons for gyro games like sports.

**Comment by CasperH2O** [comment]
@ZarifS yes this feature has been implemented. Its present in the latest 0.21.0.1. Be sure to select the controller you want to use for gyro on the Device page.

Closing ticket.
