### ISSUE TITLE
Freezes followed by BSOD "A driver has failed to complete a power IRP within a specific time."

### ISSUE THREAD

**Issue by ModdingPink** [Valkirie/HandheldCompanion#891]
**Device manufacturer**
Lenovo

**Device model**
Legion Go

**Handheld Companinion Version**
0.19.1.6

**Describe the bug**
At seemingly random points, the entire device will completely freeze up and after a minute or two bluescreen with error code `POWER STATE FAILURE`.

**To Reproduce**
Unknown currently.

**Logs file**

```
10: kd> !irp ffffe28bb74e58b0
Irp is active with 6 stacks 4 is current (= 0xffffe28bb74e5a58)
 No Mdl: No System Buffer: Thread 00000000:  Irp stack trace.  
     cmd  flg cl Device   File     Completion-Context
 [N/A(0), N/A(0)]
            0  0 00000000 00000000 00000000-00000000    

            Args: 00000000 00000000 00000000 00000000
 [N/A(0), N/A(0)]
            0  0 00000000 00000000 00000000-00000000    

            Args: 00000000 00000000 00000000 00000000
 [N/A(0), N/A(0)]
            0  0 00000000 00000000 00000000-00000000    

            Args: 00000000 00000000 00000000 00000000
>[IRP_MJ_POWER(16), IRP_MN_SET_POWER(2)]
            0 e1 ffffe28baf1d2dd0 00000000 00000000-00000000    pending
           \Driver\ACPI
            Args: 00000000 00000001 00000001 00000000
 [IRP_MJ_POWER(16), IRP_MN_SET_POWER(2)]
            0 e1 ffffe28bb710d830 00000000 fffff8002bf2cf80-ffffe28bb7563358 Success Error Cancel pending
          Unable to load image amdi2c.sys, Win32 error 0n2
*** WARNING: Unable to verify timestamp for amdi2c.sys
 \Driver\amdi2c    nt!PopRequestCompletion
            Args: 00000000 00000001 00000001 00000000
 [N/A(0), N/A(0)]
            0  0 00000000 00000000 00000000-ffffe28bb7563358    

            Args: 00000000 00000000 00000000 00000000
```

Minidump crash file:
[121823-13984-01.dmp](https://github.com/Valkirie/HandheldCompanion/files/13702793/121823-13984-01.dmp)

**Comment by CasperH2O** [comment]
Were you running HC's AutoTDP or at low (below 10 W) TDP values?

**Comment by ModdingPink** [comment]
I run at a power limit of 40W, although I've had this happen at the regular 30W limit before. 
And no I don't use Automatic TDP.

**Comment by ModdingPink** [comment]
For the time being I've uninstalled HC and reinstalled Legion Space to see if the issues are 100% related, ill report my findings in a few days.

**Comment by CasperH2O** [comment]
I have merged a PR to fix TDP bei g set too frequently, that may also have been a cause.

**Comment by CasperH2O** [comment]
@ModdingPink do you still have this issue? Are you a HC Patreon version user that has this fix implemented?

**Comment by CasperH2O** [comment]
Closing as assumed fix (see above). @ModdingPink if you can reproduce or have feedback feel free to reopen.
