### ISSUE TITLE
Remap Extra Only

### ISSUE THREAD

**Issue by nochlab1** [Valkirie/HandheldCompanion#895]
**Is your feature request related to a problem? Please describe.**

I want to remap the extra buttons on the lenovo legion go

**Describe the solution you'd like**

A lite version that includes just remapping with no extra features 

**Describe alternatives you've considered**

Couldn't find a program that will remap the buttons 

**Additional context**

**Comment by CasperH2O** [comment]
Hey @nochlab1 , there are no plans for a lite version of HC. For button remapping on the Legion Go you can use HC or LS. 

Closing as not planned.
