### ISSUE TITLE
Legion go the back buttons cannot be used in HC

### ISSUE THREAD

**Issue by Livio233** [Valkirie/HandheldCompanion#900]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [x] LENOVO

**Device model**
Your device model

**Handheld Companinion Version**
0.X.X.X

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs file**
If applicable, add logs file stored in your install location, logs folder.

**Comment by CasperH2O** [comment]
@Livio233 I'm tempted to close this ticket right away due to lack of information. But I guess you are just asking for help... Be sure to use the latest version of HC, currently 0.19.1.8. Try configuring the back buttons on HCs Hotkey page first, they should work fine.

**Comment by Livio233** [comment]
I am using the latest version, and the back buttons (Y1 Y2 Y3 M3 M2) cannot successfully map any keyboard or mouse buttons. Sorry I'm not a native English speaker, thanks for your help.

**Comment by CasperH2O** [comment]
To remap the back buttons to keyboard or mouse, you have to make a game profile, then at the bottom of the game profile, go to layout, then on the first tab, Buttons, at the bottom, configure the OEM keys to your liking.

**Comment by Livio233** [comment]
I know exactly how to operate it. In fact, I have been using HC since a year ago on the steamdeck, but the Legion go’s back keys have no response after this update.

**Comment by Livio233** [comment]
![IMG_5848](https://github.com/Valkirie/HandheldCompanion/assets/127551350/1b331638-bee6-4136-807a-ddc3a6381751)

**Comment by Livio233** [comment]
I uninstalled all the files and reinstalled and it's running normally, thank you

**Comment by Livio233** [comment]
Unfortunately, after restarting, I can't use the back buttons again.
