### ISSUE TITLE
Lenovo Legion GO Y2 key change the controller

### ISSUE THREAD

**Issue by Kalmito** [Valkirie/HandheldCompanion#901]
Hi, please disable this function,In my Legion GO if I press the Y2 button change between xbox and ps4 controller.THX!

**Comment by MSeys** [comment]
Did you map Y2 to anything in Legion Space or HC?

**Comment by Kalmito** [comment]
![game1703339591589](https://github.com/Valkirie/HandheldCompanion/assets/21316411/70c00310-0c5c-4676-b9ce-f5ef6fff7443)
![game1703339609937](https://github.com/Valkirie/HandheldCompanion/assets/21316411/e87e367f-76a7-43e4-af70-2446c286c434)

I not have mapped this buttons.

But if i press it, change controller... Ps4 to xbox... 

What js this issue?

**Comment by MSeys** [comment]
Check the Hotkeys section in HC. You must've have it mapped there.

**Comment by Kalmito** [comment]
![game1703341225370](https://github.com/Valkirie/HandheldCompanion/assets/21316411/873db357-cdb8-48aa-8aeb-265fe6a2d3f2)
Now I see, here is the issue!Thank you! :)
