### ISSUE TITLE
DSU Server doesn't work

### ISSUE THREAD

**Issue by alexyao2015** [Valkirie/HandheldCompanion#904]
**Handheld Companinion Version**
0.18.0.6+
Even though release notes and commit history don't show the .net version updated until the 0.19.x series, the binaries on github releases appear to already have the change.

**Describe the bug**
The DSU server for gyro doesn't work in yuzu. Simply downgrading to .net7 on any HC version fixes the issue.

**To Reproduce**
1. Open HC after version [0.18.0.5](https://github.com/Valkirie/HandheldCompanion/releases/tag/0.18.0.5)
2. Open yuzu and attempt to connect dsu server. 

**Expected behavior**
DSU test doesn't give errors

**Comment by CasperH2O** [comment]
Tried just now with PadTest, initially it works, then I disconnect and open Yuzu, it fails the connection test.

**Comment by CasperH2O** [comment]
Testes some more with 0.20.2.7, Padtest works most of the time, Dolphin does a constant disconnected connected every few seconds.

Did a test with Wireshark and captured a packet file. [DSUServer-PortUnreachable.zip](https://github.com/Valkirie/HandheldCompanion/files/13818068/DSUServer-PortUnreachable.zip)

![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/0ee5fffe-2f0c-4540-bb85-5d54c16ae33a)

Checked delta time of messages, seems pretty consistent at 10 msec.

Enabling  "Common Language Runtime Exceptions" for "System.Net.Sockets.SocketException" results in some additional info on the received function. Forcibly closed by the remote host. on ReciveCallback

Unsure how to proceed and fix. Someone on Discord also had a look at the packets in Wireshark for .NET7 and 8 and they seem similar.

**Comment by alexyao2015** [comment]
I think we should revert back to .net7 until this issue is fixed.

**Comment by CasperH2O** [comment]
The clever guys at DS4Windows caught this one some weeks ago, updated HC and initial testing looks good. 

https://github.com/Ryochan7/DS4Windows/commit/483c366daa1b38fba52380051cd7d4aafb44a820

**Comment by CasperH2O** [comment]
Fixed for next release.
