### ISSUE TITLE
Ayaneo Kun: LC & RC are Swapped

### ISSUE THREAD

**Issue by ChthonicCrow** [Valkirie/HandheldCompanion#906]
**Device manufacturer**
- [X] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [ ] LENOVO

**Device model**
Kun 32GB

**Handheld Companinion Version**
0.20.2.5

**Describe the bug**
When assigning actions to the LC and RC bumbers on the Kun, the listing is switched. Options set to LC are triggered when pressing RC and options set to RC are triggered when pressing LC.

**To Reproduce**
1. Open Handheld Companion
2. Navigate to the controller bindings
3. Set RC or LC to "Button"
4. Assign an action or set to vibrate on press.
5. Press the other button.

**Expected behavior**
Actions set to RC should execute when you press RC. Actions set to LC should execute when you press LC.

**Screenshots**
N/A

**Logs file**
N/A

**Comment by CasperH2O** [comment]
Hey @ChthonicCrow thanks for reporting in, I may have either swapped the input detection or the label icon, I'll double check.

**Comment by ChthonicCrow** [comment]
Thanks, I figured it was probably something simple like that.

**Comment by CasperH2O** [comment]
Fixed in EA branch, will come with next release.
