### ISSUE TITLE
Ayaneo Kun: "T" button not registering for Steam Input when bound as Xbox "Menu"

### ISSUE THREAD

**Issue by ChthonicCrow** [Valkirie/HandheldCompanion#907]
**Device manufacturer**
- [X] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [ ] LENOVO

**Device model**
Kun 32GB
**Handheld Companinion Version**
0.20.2.5

**Describe the bug**
The "T" button, the one where Menu/Options should be, has issues when bound as Menu on the virtual Xbox 360 Controller. In order to get it partially working, you must disable the physical menu button in the controller configuration, then bind the virtual controller's Menu function to the T button. Once that is done pressing T will trigger Menu in hardwaretester.com/gamepad and non-steam input games, but attempts to use it within Steam's big picture UI or Steam Input configurations produce no result. If you switch the virtual controller to a Dualshock 4, it will act as expected.

**To Reproduce**
1. Open Handheld Companion
2. Make sure the controller type is set to Xbox 360
3. Navigate to the controller mappings.
4. Bind "T" to be a press of "Menu".
5. Open a browser and navigate to hardwaretester.com/gamepad.
6. Use Sticks/Triggers/Dpad/ABXY to confirm inputs are registering within the website.
7. Press "T", you won't see Menu highlight, but you will see a button get the value 1.0.
8. Go back into controller mappings.
9. Set the physical Menu button to "Disabled".
10. Return to the hardwaretester site, Pressing T should now highlight Menu.
11. Open Steam Big picture.
12. Select a UI object and try to use T as the Menu input to bring up options. This will fail.
13. Go into Steam settings>controller and test inputs.
14. Verify that Sticks/Triggers/Dpad/ABXY are registering in the test.
15. Try using T as the Menu input. This will fail.
16. Open a non-Steam Input game. (I used Diablo 4)
17. Try all the buttons. "T" should trigger Menu as expected.

**Expected behavior**
When T is bound as Menu for the virtual Xbox controller, you would expect it to register as the Menu button within Steam. This would allow you to open the options for the current UI selection or trigger a Menu press within Steam input.

**Screenshots**
N/A

**Logs file**
N/A

**Comment by ChthonicCrow** [comment]
My bad, this appears to be partially user error. I had Xbox extended installed for Steam, and it appears that was causing it to always see the device's controller rather than the remapped HC virtual controller.

**Comment by CasperH2O** [comment]
Thanks for the update @ChthonicCrow
