### ISSUE TITLE
Main window profiles page FPS limit doesn't update when quick tools one does

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#914]
**Handheld Companinion Version**
0.20.3.4

**Describe the bug**
As title, adjusting the FPS limit in QuickTools, the FPS limit in the main GUI does not get updated accordingly.

**Comment by CasperH2O** [comment]
ProfilesPage.xaml.cs has a FIXME for the Combobox update missing: 

```
                // Framerate limit
                cB_Framerate.SelectedIndex = selectedProfile.FramerateValue;
```

But even after correcting that, the problem persists. This seems a likely suspect:

![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/b6d3bc26-be21-4d15-b26a-49018a028fdd)

**Comment by Valkirie** [comment]
Fixed in EA
