### ISSUE TITLE
Enable use of mode and LED buttons as hotkeys on Onexplayer 2

### ISSUE THREAD

**Issue by downerhouse** [Valkirie/HandheldCompanion#926]
The onexplayer 2 (Pro) has two buttons below the right hand analogue joystick called mode and LED

By default they are used as follows:

- mode: press and hold for 1.5 seconds toggles between gamepad / mouse mode
- LED: press and hold for 1.5 seconds toggles LED on and off

I would like to be able to use these two buttons as hotkeys so functions can be assigned.

**Comment by CasperH2O** [comment]
Hey @downerhouse , thanks for suggesting something. I've personally added OXP2 support to HC and at the time, found no way to get information on these button presses in any connected device. My conclusion is that these buttons interface with the joycon firmware and thats it. Would have been nice tough!

Closing as won't fix
