### ISSUE TITLE
HC does not install extra apps for the current user

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#927]
**Handheld Companinion Version**
0.20.2.5

**Describe the bug**
Initial installation shows .net8 being installed, but upon starting HC for the first time it also requires windowsdesktop-runtime-8.0.0-win-x64.exe.

Same for HidHide.

It seems none of the additional apps were installed for the non-admin user from which this setup was started.

**Comment by Metadorius** [comment]
Same with HidHide for all users. The app just silently exits/crashes. I already had .NET 8 installed so don't know whether this happens with it as well.

**Comment by CasperH2O** [comment]
This is an issue with the installer not being run with administrator rights, a fix is in the works.

**Comment by CasperH2O** [comment]
Has been investigated, HC installer no longer offers option to install for other users. If desired, run the installer per user. Not ideal, but it turned out to not be feasible to do it properly.
