### ISSUE TITLE
Easier onboarding of new users

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#93]
New users will want certain information and settings first, some ideas and suggestions.
- HC, set profiles page as home page, users will want to configure a game right away
- HC, profiles page universal motion controls (expanded) at the top of profile settings, not the bottom.
- Autosave profile ie remove save button and just have it apply right away when making changes, it's not super clear that this needs to be done to apply changes, where the rest of the app (other pages and settings) apply stuff right away.

**Comment by Valkirie** [comment]
I'll start by implementing XInputListener at client level. This will allow us to free some memory/cpu bandwith by getting rid of unnecessary pipe messages. This will also give me more flexibility to implement proper input listener on both the Overlay / Profile pages.

**Comment by CasperH2O** [comment]
Updated list, removed two items that have been done.

**Comment by CasperH2O** [comment]
We can close this one for now, improvements have been made.
