### ISSUE TITLE
Citra Canary controller binding lost

### ISSUE THREAD

**Issue by BriaN890501** [Valkirie/HandheldCompanion#931]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ V] VALVE
- [ ] LENOVO

**Device model**
Steam Deck LCD

**Handheld Companinion Version**
0.19.1.8

**Describe the bug**
After version 0.19.x, keybinding on Citra emulator is lost on reboot, controller can be rebinded but still losts on reboot, had to revert to 0.18.0.6

**To Reproduce**
1. Install HC version 0.19.1.8
2. Open citra
3. no input observed
4. rebind controller, which works
5. reboot and binding is lost

**Expected behavior**
Keybinding persists after updating HC / rebooting device

**Comment by CasperH2O** [comment]
@BriaN890501 , thanks for reporting in. Respectfully it sounds like a Citra issue, if HC is running with the same (virtual) controller connected and you start Citra, it should be able to see the same controller to connect as when it closes?

**Comment by BriaN890501** [comment]
My bad. All the previous mentioned "reboot" refers to device reboot (in this case Steam Deck)
It certainly works after rebinding and open / closing Citra

**Comment by CasperH2O** [comment]
@BriaN890501 altough currently the DSU server is broken on the last few HC versions, we have a fix coming for that. Perhaps you could configure a DSU client as controller input instead in Citra, will also allow for touch controls and motion (if applicable for the game)?

**Comment by BriaN890501** [comment]
@CasperH2O  I don't think configure a DSU client as controller input in Citra is available.
However, I think I found the culprit.
Citra seems to bind controller by specific hardware id, as referenced in this Citra issue:
https://github.com/citra-emu/citra/issues/4509

The latest HC seems to be providing different "guid" to Citra on device reboot, thus not recognizing previously binded controller.

**Comment by BriaN890501** [comment]
Yeah, I've done that and rebooted device but it still assigns a new id.
Is it a feature after 0.18.0.6? cause I've only encountered this behavior on newer versions.

Thanks for the active reply!

**Comment by CasperH2O** [comment]
@BriaN890501 yes, it's definitely new. It might also be that disabling it is actually not working: #912

**Comment by CasperH2O** [comment]
@BriaN890501 I recommend you make a HC Profile for Citra and tick the box to allow it access to the physical controller.

**Comment by BriaN890501** [comment]
Tested just now with 0.20.3.1, unfortunately allowing citra to access physical controller doesn't solve the issue, the controller guid in citra's qt.config still changes on device reboot, even with controller management disabled.

Is it possible to add a toggle to disable HC from assigning new id to controller?

**Comment by MSeys** [comment]
@BriaN890501 set the emulated controller type to DualShock 4 for Citra. We only do "random"/ unique Ids for Xbox 360 emulation.

**Comment by BriaN890501** [comment]
Yeah, changing controller type to ds4 in citra profile fixed the issue!
Thanks for the continuous support!
