### ISSUE TITLE
Overlay doesn't work

### ISSUE THREAD

**Issue by ModernLobby** [Valkirie/HandheldCompanion#933]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [x] VALVE
- [ ] LENOVO

**Device model**
Steam LCD

**Handheld Companinion Version**
0.19.8

**Describe the bug**
When opening the Quicks tool menu and going into "Device = Overlay Display Level (Sub menu is disabled/greyed out)
Even when setting up the overlay in the software nothing show on screen.

**To Reproduce**
1. Go to 'Quicktools Menu'
2. Click on 'Device'
3. Option disabled for the overlay.

**Expected behavior**
Setting up the level of information I want with the Overlay.

**Screenshots**
![20240106_220947 (1)](https://github.com/Valkirie/HandheldCompanion/assets/23289966/d941699f-722c-448b-be76-96a9815a8a24)

**Comment by MSeys** [comment]
Do you have RTSS correctly installed? Please add a log file. You can find them in C:/Program Files/Handheld Companion/logs.

**Comment by CasperH2O** [comment]
This can happen if something failed during installation and RTSS and or HWiNFO did not get installed. Please double check if you have those apps and if not, re run the installer?

**Comment by ModernLobby** [comment]
> Do you have RTSS correctly installed? Please add a log file. You can find them in C:/Program Files/Handheld Companion/logs.



> This can happen if something failed during installation and RTSS and or HWiNFO did not get installed. Please double check if you have those apps and if not, re run the installer?

I followed CasperH2O by reinstalling Handheld companion the overlay is working fine now.
I think RTSS did bug or crash, but now it's working thanks you 👍
