### ISSUE TITLE
long press or double press with M1 on asus rog ally for button assignment for quick settings window HC

### ISSUE THREAD

**Issue by Richimaster42** [Valkirie/HandheldCompanion#942]
I suggest implementing M1 button assignment such as long press or double press with to activate the HC quick settings window for the asus rog ally

![imagen_2024-01-12_134302539](https://github.com/Valkirie/HandheldCompanion/assets/156464083/2da7164f-a313-44ca-8849-ced2a49fdae5)

QUICK TOOL WINDOW

![imagen_2024-01-12_134438285](https://github.com/Valkirie/HandheldCompanion/assets/156464083/16527915-28c9-4eb9-a237-57ccf3ed9f64)

HOTKEYS

![imagen_2024-01-12_134522195](https://github.com/Valkirie/HandheldCompanion/assets/156464083/64bb311c-bcfc-4590-8cee-5ae9afd034ec)

I think it would be a great implementation to be able to have more customization options, since these rear buttons do not influence most video games, so it would simply be like a specialized button to activate the quick settings window, which I personally see as those of us who follow using AC and HC at the same time

**Comment by CasperH2O** [comment]
Done.

![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/9e319ab6-4464-4723-afb3-d3c91600a94b)
