### ISSUE TITLE
PC manager and Windows power tools detected as processes

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#947]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
Your device model

**Handheld Companinion Version**
0.X.X.X

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs file**
If applicable, add logs file stored in your install location, logs folder.

**Comment by MSeys** [comment]
Apps are:
- PC Manager
- PowerToys' MouseWithoutBorders

**Comment by moni11811** [comment]
PC Manager:
MSPCManager.exe
PowerToys' MouseWithoutBorders:
PowerToys.MouseWithoutBordersHelper.exe

**Comment by CasperH2O** [comment]
Fixed for next EA. Closing.
