### ISSUE TITLE
Service options not appearing

### ISSUE THREAD

**Issue by mrespn895** [Valkirie/HandheldCompanion#964]
Hello,

I am trying to Handheld Companion working on ROG ALLY.  I seem to possibly get permission pop up questions when trying to get into it, but the service options to start, stop, deploy don't appear at the bottom left.  I can't find anything online on why.  I do get a warning about downloading it whenever I tried, and I don't get the Microsoft runtime pop up on certain steps of the installation as videos show.  Does anyone have any idea on what's going on?  

Thanks

**Comment by MSeys** [comment]
I am not sure what you're talking about. Some videos might be very outdated already.
I don't believe HC works as a Service anymore.

**Comment by mrespn895** [comment]
Sorry, the videos could be outdated but, on the bottom, left in videos and pictures show a few options.  I never see those options and not sure if something isn't functioning right.  Stop, Start, Deploy and Remove.  If they are not meant to that would be great!

Also it asks to turn of an ASUS service to use.  Do we know which one in exactly of the 3 that gets shut off?  
 
![Handheld-Companion-Hotkeys](https://github.com/Valkirie/HandheldCompanion/assets/157531399/727891b7-1546-4eea-828d-a408e5f252ba)

Thank you!!!!

**Comment by MSeys** [comment]
As you can see, it's an incredibly old version. HC is not a Service anymore. Those don't exist anymore.

For the AC services, I don't know. I don't own one myself. @CasperH2O

**Comment by mrespn895** [comment]
Thank you!  First time doing something like this, and things didn't seem perfect from everything and wanted confirmation!

**Comment by MSeys** [comment]
For better assistance, you can always join the HC discord.

**Comment by CasperH2O** [comment]
@mrespn895 I am working under the assumption you watched the installation and configuration video on YouTube? A lot has changed since then, HC no longer has a separate service. 

Are you experiencing any specific issues with the software?

**Comment by CasperH2O** [comment]
No response from original issue reporter. Indeed some of the documentation and videos out there are a tad outdated, such is the price of progress. 😉 

Closing ticket. If you need any further help @mrespn895 it's best to discuss on Discord.
