### ISSUE TITLE
App won’t start on steam deck is any fix for this?

### ISSUE THREAD

**Issue by Kevinoco19** [Valkirie/HandheldCompanion#966]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [x] VALVE

**Device model**
Your device model

**Handheld Companinion Version**
0.X.X.X

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs file**
If applicable, add logs file stored in your install location, logs folder.

**Comment by MSeys** [comment]
Send a log file. We can't help if you don't send one. (C:/Program Files/Handheld Companion/logs)

**Comment by CasperH2O** [comment]
Original issue creator has not responded. Logfiles required to troubleshoot.

@Kevinoco19 feel free to reopen if you are still having trouble. If you find the log and it says HidHide is missing, you can install it from the link.
