### ISSUE TITLE
Switching from software to hardware fan control does nothing until profile is updated

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#968]
This code path is not performed when the user changes the fan control in the GUI.

![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/729f9d05-efeb-40f3-b563-02ffcefafd74)

This code path is never triggered when changing the fan control mode from hardware to software in the GUI on the power preset configuration. Somehow, when setting it to software, it does actually get applied in some other piece of code.
And when changing process window. But setting it to hardware, from software, nothing happens.

**Comment by Valkirie** [comment]
Will fix today.
