### ISSUE TITLE
HC Hotkeys don't work in Rockstar games 

### ISSUE THREAD

**Issue by zhengqing-ml** [Valkirie/HandheldCompanion#970]
**Device manufacturer**
- [x] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
AYANEO 2s

**Handheld Companinion Version**
0.20.3.0

**Describe the bug**
I found HC Hotkeys doesn't work in many rockstar games, including GTA5, RDR2, GTA4, etc. As long as I open these games, looks like that the game will take over the entire controller and hotkey will no longer work. After close these games, HC work back to normal. I didn't find anyone mention this. 

**Expected behavior**
Hotkeys work in these games

**Comment by CasperH2O** [comment]
Closing this as a not planned, various games and even some apps don't play nice with HCs input capturing or remapping, it is what it is unfortunately. Sorry to disappoint @zhengqing-ml
