### ISSUE TITLE
XG Mobile Functionality

### ISSUE THREAD

**Issue by SegaBoy64** [Valkirie/HandheldCompanion#973]
Firstly big thanks for this software, it's truly making up for the woeful docked experience that ASUS currently provides with the ROG Ally.

One last remaining feature that is still dependent on AC is enabling/disabling the XG Mobile, so wanted to see if this is on your roadmap - perhaps in a similar manner to G-Helper?

Thanks for your time and consideration...

**Comment by CasperH2O** [comment]
Hey @SegaBoy64 it is currently not really on our roadmap, although HC has been getting some GPU related updates recently.

Just to confirm, you are not having any issues with HC and the XG Mobile connected? It's just that you wish you could do certain settings from HC?

**Comment by SegaBoy64** [comment]
Hi @CasperH2O - exactly that; HC appears to be the perfect solution for docking the Ally and overcomes a lot of the frustrations/issues faced by the stock setup.

I'm so impressed by what I managed in one evening you have yourself another Patreon supporter; thanks for all of the hard work and effort.

**Comment by CasperH2O** [comment]
Thank you for the kind words @SegaBoy64 , there's still a couple ideas for features concerning docked mode on the horizon.

I'm closing this ticket as not planned.
