### ISSUE TITLE
Unexpected Manufacturer GPUManager initialization

### ISSUE THREAD

**Issue by MSeys** [Valkirie/HandheldCompanion#982]
**Device manufacturer**
Any

**Handheld Companinion Version**
0.20.4.x

**Describe the bug**
GPU initialization can crash when it's an unknown Manufacturer.

**To Reproduce**
Have a custom driver like Super display or Parsec virtual GPU
E.g. https://superdisplay.app/

**Expected behavior**
No crash

**Logs file**
```
Unexpected Manufacturer: Software by KeloCube
```

**Comment by Valkirie** [comment]
Should be fixed with EA

**Comment by CasperH2O** [comment]
This has been fixed. Closing.

**Comment by Shamshala** [comment]
Hello, and is there any version with this fix released? I tried even Patreon without success.

**Comment by CasperH2O** [comment]
@Shamshala , we have an early test build on Discord 0.20.5.1 which improves the situation quite a bit. Ut isnt fault proof yet.

**Comment by Shamshala** [comment]
@CasperH2O I found the v0.20.5.1 mentioned and even link in the discord but it seems to be in restricted channel. Not accessible even for Patreon users or did I miss something?

**Comment by CasperH2O** [comment]
@Shamshala what is your Discord user name?
