### ISSUE TITLE
HC does not always create a logfile

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#991]
**Handheld Companinion Version**
0.20.4.1

**Describe the bug**
Often when HC starts with Windows automatically, no logfile is started/created until HC is restarted or next time during booth. 

**To Reproduce**
Unknown

**Expected behavior**
A log should always be created

**Comment by CasperH2O** [comment]
@romracer pointed out this may indeed by only when HC starts with the OS boot. Still present in 0.20.5.7

**Comment by romracer** [comment]
Fixed in next release

**Comment by CasperH2O** [comment]
Fixed by @romracer in Valkirie/HandheldCompanion-ea#251
