### ISSUE TITLE
Ayaneo Slide home button doesn't open Handheld Companion 

### ISSUE THREAD

**Issue by DevL0rd** [Valkirie/HandheldCompanion#997]
**Device manufacturer**
- [ ! ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
Ayaneo Slide

**Handheld Companinion Version**
0.20.4.1

**Describe the bug**
Unable to open handheld companion using the ayaneo home button, also unable to remap the second custom button, but less important.

**Expected behavior**
I expect handheld companions button mapping to extent to keyboard input so it's more generic and supports the ayaneo home button if I map it.

**Suggested Fix**
The Aya neo home button simulates the keypress
"lctrl + lmeta + F17".
You could support this keyboard combo natively as a quick fix, or fix they keybinds system to include keyboard events instead of just controller keys.

**Comment by CasperH2O** [comment]
Hey @DevL0rd , thanks for dropping in. The Slide has not yet been made compatible with HC, so OEM keys dont work yet.

If you are skilled in C#, you can help adding it?

Example Ayaneo device: https://github.com/Valkirie/HandheldCompanion/blob/main/HandheldCompanion/Devices/AYANEO/AYANEOAIR.cs

**Comment by CasperH2O** [comment]
Here is a nice commit that adds all the basics for a new device.

https://github.com/Valkirie/HandheldCompanion/commit/dfbaae602db8b0b7cee4cf37664407dc83e7127e

**Comment by DevL0rd** [comment]
you know what, I think I will do just that. let me get my dev environment setup.

**Comment by DevL0rd** [comment]
quick question, where do i get a nice image like in that commit?

**Comment by DevL0rd** [comment]
@CasperH2O How do i find the ECDetails for fan control? I have everything else working

**Comment by CasperH2O** [comment]
Done! 😉
